import { defineDisease } from "../define";

export const CARDIO_NEURO = [
  defineDisease({
    id: "acs",
    name: "Acute coronary syndrome",
    icd10: "I24.9",
    specialty: "cardiology",
    department: "Emergency / Cardiology — STEMI pathway",
    urgency: "emergency",
    setting: "Emergency department / EMS now",
    summary:
      "Unstable ischemic heart disease: unstable angina, NSTEMI, or STEMI. Pressure-like chest pain, radiation to arm or jaw, diaphoresis, dyspnea, and nausea. Time to reperfusion saves myocardium.",
    hallmarks: ["chest-pain", "radiating-arm", "sweating", "shortness-of-breath", "nausea"],
    supportive: ["palpitations", "fatigue", "dizziness", "vomiting"],
    occasional: ["syncope", "epigastric-pain", "anxiety"],
    age: [30, 100],
    sexBias: "male",
    vitals: { tachy: true, hypotensive: true },
    comorbidBoost: ["diabetes", "hypertension", "heart-disease"],
    smokerBoost: true,
    redFlags: ["Ongoing chest pressure", "Radiation", "Diaphoresis", "Syncope", "Hypotension"],
    workup: ["ECG within 10 minutes", "High-sensitivity troponin serial", "CXR", "Stabilize ABCs", "Activate cath lab if STEMI"],
    prevention: [
      "Statin, antiplatelet, BP and diabetes control after the event",
      "Smoking cessation",
      "Mediterranean-pattern diet and cardiac rehab",
      "Know the warning symptoms and call emergency services — do not drive yourself",
    ],
    medications: [
      {
        class: "Acute reperfusion and antithrombotic bundle (hospital)",
        examples: ["Aspirin 162–325 mg chewed", "P2Y12 inhibitor", "Anticoagulation", "Primary PCI or fibrinolysis if PCI delayed"],
        notes: "This is an emergency protocol. Do not take leftover nitroglycerin instead of calling EMS if pain is new or severe.",
      },
      {
        class: "Secondary prevention",
        examples: ["High-intensity statin", "Beta-blocker", "ACE inhibitor / ARB", "Aspirin"],
        notes: "Started in hospital and continued as directed by cardiology.",
      },
    ],
    selfCare: ["Call emergency services immediately", "Chew aspirin only if a clinician or dispatcher instructs and there is no bleeding allergy"],
    seekCare: "Call emergency services now — do not wait to see if it passes.",
  }),
  defineDisease({
    id: "stable-angina",
    name: "Stable ischemic heart disease (angina)",
    icd10: "I25.119",
    specialty: "cardiology",
    department: "Cardiology / Internal medicine",
    urgency: "soon",
    setting: "Cardiology clinic promptly; ED if rest pain or crescendo pattern",
    summary:
      "Demand ischemia from atherosclerotic stenoses. Predictable exertional chest pressure relieved by rest or nitroglycerin, often with known risk factors.",
    hallmarks: ["chest-pain", "chest-tightness", "shortness-of-breath"],
    supportive: ["fatigue", "radiating-arm"],
    occasional: ["nausea", "palpitations", "dizziness"],
    age: [40, 100],
    vitals: {},
    comorbidBoost: ["diabetes", "hypertension", "heart-disease"],
    smokerBoost: true,
    redFlags: ["Pain at rest", "Crescendo pattern", "Syncope", "New heart failure signs"],
    workup: ["ECG", "Troponin if unstable features", "Stress testing or coronary CTA per pretest probability", "Lipid panel, A1c"],
    prevention: ["Risk-factor control", "High-intensity statin when indicated", "Exercise within prescribed limits", "Smoking cessation"],
    medications: [
      {
        class: "Anti-anginal and disease-modifying therapy",
        examples: ["Beta-blocker", "Dihydropyridine or non-DHP calcium channel blocker", "Long-acting nitrate", "Aspirin", "High-intensity statin"],
        notes: "Cardiology individualizes anti-anginal stacking and revascularization.",
      },
    ],
    selfCare: ["Stop activity when pain starts", "Track a symptom diary", "Call EMS if rest pain"],
    seekCare: "Same-week cardiology if new exertional pain; EMS if pain at rest.",
  }),
  defineDisease({
    id: "decompensated-hf",
    name: "Acute decompensated heart failure",
    icd10: "I50.9",
    specialty: "cardiology",
    department: "Emergency / Cardiology / Heart failure service",
    urgency: "urgent",
    setting: "ED; many patients require admission",
    summary:
      "Worsening ventricular filling or output: orthopnea, PND, edema, and exertional dyspnea, often after dietary salt, missed diuretics, ischemia, or arrhythmia.",
    hallmarks: ["shortness-of-breath", "orthopnea", "pnd", "edema-legs", "fatigue"],
    supportive: ["cough", "weight-gain", "chest-tightness"],
    occasional: ["palpitations", "confusion", "nausea"],
    age: [40, 100],
    vitals: { tachy: true, hypoxic: true, hypertensive: true },
    comorbidBoost: ["heart-disease", "hypertension", "kidney-disease", "diabetes"],
    redFlags: ["Hypoxia", "Hypotension / shock", "Chest pain", "Syncope", "Pink frothy sputum"],
    workup: ["ECG, CXR, BNP/NT-proBNP", "Troponin", "CBC, CMP, TSH", "Echo if new or unexplained"],
    prevention: ["Daily weights", "Sodium and fluid guidance", "GDMT adherence", "Vaccination", "Clinic follow-up within 7 days of discharge"],
    medications: [
      {
        class: "Acute decongestion and GDMT",
        examples: ["IV loop diuretic", "Vasodilators if hypertensive", "Inotropes only in selected shock", "GDMT: ARNI/ACE/ARB, evidence-based beta-blocker, MRA, SGLT2 inhibitor"],
        notes: "Do not stop GDMT casually. Dosing is specialist-supervised.",
      },
    ],
    selfCare: ["Daily weight; call for +2 lb overnight or +5 lb in a week", "Elevate legs", "Take diuretics as prescribed"],
    seekCare: "ED for rest dyspnea, hypoxia, or chest pain.",
  }),
  defineDisease({
    id: "atrial-fibrillation",
    name: "Atrial fibrillation (symptomatic)",
    icd10: "I48.91",
    specialty: "cardiology",
    department: "Cardiology / Emergency if unstable",
    urgency: "urgent",
    setting: "ED if unstable or new with heart failure; otherwise rapid cardiology",
    summary:
      "Supraventricular tachyarrhythmia with irregularly irregular rhythm. Palpitations, fatigue, dyspnea, or syncope. Stroke risk is independent of whether the patient 'feels' the AF.",
    hallmarks: ["palpitations", "irregular-heartbeat", "fatigue", "shortness-of-breath"],
    supportive: ["dizziness", "chest-tightness", "anxiety"],
    occasional: ["syncope", "chest-pain", "edema-legs"],
    age: [40, 100],
    vitals: { tachy: true },
    comorbidBoost: ["hypertension", "heart-disease", "diabetes"],
    redFlags: ["Hypotension", "Chest pain", "Heart failure", "Stroke symptoms", "Rate >150 with instability"],
    workup: ["ECG", "TSH, CBC, CMP, troponin if ischemic symptoms", "Echo", "CHA2DS2-VASc and HAS-BLED"],
    prevention: ["Treat sleep apnea, alcohol excess, obesity, thyroid disease", "Anticoagulation when stroke risk warrants", "Rhythm or rate strategy with cardiology"],
    medications: [
      {
        class: "Rate control, rhythm control, anticoagulation",
        examples: ["Beta-blocker or non-DHP CCB for rate", "Antiarrhythmics (flecainide, amiodarone, etc.) selected by cardiology", "DOAC (apixaban, rivaroxaban, dabigatran) or warfarin"],
        notes: "Anticoagulation decisions are individualized. Do not start or stop without a clinician.",
      },
    ],
    selfCare: ["Avoid binge alcohol", "Record pulse irregularity", "Know bleeding signs if anticoagulated"],
    seekCare: "ED if faint, chest pain, or severe dyspnea.",
  }),
  defineDisease({
    id: "pe",
    name: "Pulmonary embolism",
    icd10: "I26.99",
    specialty: "pulmonology",
    department: "Emergency / Pulmonology / Hematology",
    urgency: "emergency",
    setting: "Emergency department now",
    summary:
      "Venous thromboembolus in the pulmonary arteries. Sudden dyspnea, pleuritic pain, tachycardia, and sometimes hemoptysis or syncope. Risk: recent surgery, cancer, estrogen, immobility, prior VTE.",
    hallmarks: ["shortness-of-breath", "pleuritic-pain", "calf-swelling", "sweating"],
    supportive: ["palpitations", "chest-pain", "hemoptysis", "dizziness"],
    occasional: ["syncope", "fever", "cough"],
    vitals: { tachy: true, hypoxic: true, hypotensive: true },
    comorbidBoost: ["cancer", "heart-disease"],
    pregnancyRisk: true,
    redFlags: ["Syncope", "Hypotension", "Hypoxia", "Unilateral leg swelling with dyspnea"],
    workup: ["Wells / YEARS", "D-dimer if low probability", "CT pulmonary angiogram or V/Q", "Lower-extremity Doppler", "Troponin/BNP and echo if intermediate-high risk"],
    prevention: ["Perioperative prophylaxis", "Mobilize after surgery", "Do not ignore unilateral leg swelling", "Risk counseling with estrogen therapy"],
    medications: [
      {
        class: "Anticoagulation ± reperfusion",
        examples: ["Heparin/LMWH bridge", "DOAC (apixaban, rivaroxaban)", "Systemic or catheter thrombolysis for massive PE"],
        notes: "Hospital protocol. Thrombolysis is reserved for shock or selected high-risk cases.",
      },
    ],
    selfCare: ["Do not wait at home with sudden unexplained dyspnea"],
    seekCare: "Call emergency services.",
  }),
  defineDisease({
    id: "dvt",
    name: "Deep-vein thrombosis",
    icd10: "I82.409",
    specialty: "hematology",
    department: "Emergency / Vascular medicine / Hematology",
    urgency: "urgent",
    setting: "Same-day Doppler; ED if PE symptoms",
    summary:
      "Thrombosis, usually of the lower-extremity deep veins. Unilateral swelling, pain, and warmth. The feared complication is pulmonary embolism.",
    hallmarks: ["calf-swelling", "calf-cramps"],
    supportive: ["skin-warmth", "skin-redness"],
    occasional: ["shortness-of-breath", "pleuritic-pain"],
    comorbidBoost: ["cancer"],
    pregnancyRisk: true,
    redFlags: ["Concomitant dyspnea or chest pain", "Phlegmasia (threatened limb)", "Pregnancy"],
    workup: ["Wells score", "D-dimer if low probability", "Compression ultrasonography", "Thrombophilia testing only in selected cases"],
    prevention: ["Prophylaxis when hospitalized", "Travel mobility and hydration", "Avoid smoking with estrogen"],
    medications: [
      {
        class: "Therapeutic anticoagulation",
        examples: ["Apixaban", "Rivaroxaban", "LMWH", "Warfarin with bridge"],
        notes: "Duration typically 3 months or longer depending on provoked vs unprovoked and cancer.",
      },
    ],
    selfCare: ["Elevation, ambulation as advised", "Do not massage the calf"],
    seekCare: "Same day for unilateral swelling; EMS if breathless.",
  }),
  defineDisease({
    id: "pericarditis",
    name: "Acute pericarditis",
    icd10: "I30.9",
    specialty: "cardiology",
    department: "Cardiology / Emergency",
    urgency: "urgent",
    setting: "ED to exclude STEMI and tamponade, then cardiology",
    summary:
      "Inflammation of the pericardium, often idiopathic/viral. Sharp positional chest pain worse supine, better leaning forward, with rub and widespread ST elevation.",
    hallmarks: ["chest-pain", "pleuritic-pain", "fever"],
    supportive: ["fatigue", "malaise", "shortness-of-breath"],
    occasional: ["palpitations", "muscle-aches"],
    age: [15, 70],
    vitals: { fever: true, tachy: true },
    redFlags: ["Hypotension / muffled sounds / JVD (tamponade)", "Myocarditis overlap (troponin, dysfunction)", "Anticoagulated patient"],
    workup: ["ECG", "Troponin", "Echo", "CRP/ESR, CBC", "CXR"],
    prevention: ["Treat underlying infection or autoimmune disease", "Colchicine reduces recurrence"],
    medications: [
      {
        class: "Anti-inflammatory regimen",
        examples: ["High-dose NSAID", "Colchicine", "Corticosteroid if contraindication to NSAID or autoimmune cause"],
        notes: "Avoid NSAIDs if myocarditis dominates. Activity restriction until recovered.",
      },
    ],
    selfCare: ["Avoid competitive sport until cleared", "Take colchicine as prescribed to prevent recurrence"],
    seekCare: "ED for positional chest pain — ECG is required to exclude STEMI.",
  }),
  defineDisease({
    id: "aortic-dissection",
    name: "Acute aortic syndrome (dissection suspect)",
    icd10: "I71.00",
    specialty: "emergency",
    department: "Emergency / Cardiothoracic surgery",
    urgency: "emergency",
    setting: "Emergency department / hybrid OR pathway",
    summary:
      "Tear in the aortic intima. Sudden tearing chest or back pain, pulse deficit, and possible stroke, AR, or tamponade. Hypertension and connective-tissue disease raise risk.",
    hallmarks: ["chest-pain", "radiating-arm", "sweating", "syncope"],
    supportive: ["back-pain", "shortness-of-breath", "dizziness"],
    occasional: ["weakness-one-side", "speech-difficulty", "abdominal-pain"],
    age: [30, 100],
    vitals: { hypertensive: true, hypotensive: true },
    comorbidBoost: ["hypertension"],
    redFlags: ["Tearing pain to the back", "Pulse or BP differential", "Neurologic deficit plus chest pain", "Marfanoid habitus"],
    workup: ["Do not delay CTA if high suspicion", "ECG (may mimic ACS)", "Bedside echo", "D-dimer in selected low-moderate suspicion"],
    prevention: ["Lifelong BP control", "Screen first-degree relatives of genetic aortopathy", "Avoid fluoroquinolones in known aortopathy when possible"],
    medications: [
      {
        class: "Anti-impulse therapy then repair",
        examples: ["IV beta-blocker (esmolol/labetalol) then vasodilator", "Emergency surgery for type A"],
        notes: "Hospital-only. Do not treat empirically as ACS with thrombolysis.",
      },
    ],
    selfCare: ["Call emergency services"],
    seekCare: "Call emergency services now.",
  }),
  defineDisease({
    id: "hypertension-urgent",
    name: "Hypertension, symptomatic / urgency spectrum",
    icd10: "I10",
    specialty: "cardiology",
    department: "Primary care / Emergency if end-organ signs",
    urgency: "soon",
    setting: "Clinic for asymptomatic severe BP; ED if headache, chest pain, dyspnea, or neurologic change",
    summary:
      "Elevated blood pressure with headache, blurred vision, or epistaxis, or incidental severe readings. True emergency requires acute end-organ damage.",
    hallmarks: ["headache", "blurred-vision"],
    supportive: ["dizziness", "fatigue", "chest-tightness", "palpitations"],
    occasional: ["chest-pain", "shortness-of-breath", "confusion", "epistaxis"],
    age: [20, 100],
    vitals: { hypertensive: true },
    comorbidBoost: ["hypertension", "kidney-disease", "diabetes"],
    redFlags: ["Focal neurology", "Chest pain", "Acute dyspnea", "Papilledema", "Pregnancy"],
    workup: ["Repeat BP both arms", "ECG, troponin, CXR, BMP, UA if severe", "Fundoscopy if headache/vision change"],
    prevention: ["DASH-style diet, sodium reduction", "Daily medication adherence", "Home BP log", "Limit alcohol, treat sleep apnea"],
    medications: [
      {
        class: "Oral antihypertensives for urgency; IV agents for emergency",
        examples: ["Amlodipine", "ACE inhibitor / ARB", "Thiazide", "Nicardipine or labetalol IV if emergency"],
        notes: "Asymptomatic severe BP is usually lowered over hours–days, not minutes. Pregnancy needs obstetric protocols (not ACE/ARB).",
      },
    ],
    selfCare: ["Do not double-dose leftover meds without advice", "Sit quietly and recheck"],
    seekCare: "ED for chest pain, breathlessness, or neurologic symptoms with high BP.",
  }),
  defineDisease({
    id: "costochondritis",
    name: "Costochondritis / musculoskeletal chest wall pain",
    icd10: "M94.0",
    specialty: "general-medicine",
    department: "Primary care — after ACS is excluded when indicated",
    urgency: "routine",
    setting: "Primary care once life-threatening causes are reasonably excluded",
    summary:
      "Inflammation of costochondral junctions. Reproducible focal chest-wall tenderness without ischemic features, hypoxia, or ECG changes. A diagnosis of exclusion in at-risk adults.",
    hallmarks: ["chest-pain", "sore-chest-cough"],
    supportive: ["chest-tightness"],
    occasional: ["cough"],
    redFlags: ["Exertional pressure", "Diaphoresis", "Dyspnea", "Syncope"],
    workup: ["ECG and troponin when ACS remains possible", "Clinical reproduction of pain"],
    prevention: ["Ergonomics", "Gradual return to push-ups/lifting"],
    medications: [
      {
        class: "Simple analgesia",
        examples: ["Acetaminophen", "Short-course NSAID if no contraindication", "Topical NSAID"],
        notes: "Never assume musculoskeletal pain in a high-risk patient without an ECG.",
      },
    ],
    selfCare: ["Activity modification, heat", "Avoid heavy bench-press until pain-free"],
    seekCare: "ED for pressure-like, exertional, or radiating pain.",
  }),
  defineDisease({
    id: "stroke-tia",
    name: "Ischemic stroke or TIA",
    icd10: "I63.9",
    specialty: "neurology",
    department: "Emergency / Stroke team — time-critical",
    urgency: "emergency",
    setting: "Emergency department via EMS — note last known well",
    summary:
      "Focal brain ischemia. Sudden face/arm weakness, speech difficulty, visual field loss, or severe imbalance. TIA is a warning; stroke is ongoing injury. Last-known-well time drives thrombolysis and thrombectomy windows.",
    hallmarks: ["weakness-one-side", "facial-droop", "speech-difficulty", "vision-loss"],
    supportive: ["numbness", "balance-problems", "confusion", "dizziness", "headache"],
    occasional: ["seizure", "loss-of-consciousness"],
    age: [18, 100],
    vitals: { hypertensive: true },
    comorbidBoost: ["hypertension", "heart-disease", "diabetes"],
    smokerBoost: true,
    redFlags: ["Any sudden focal deficit", "Thunderclap headache", "Decreasing consciousness"],
    workup: ["NIHSS", "Noncontrast CT then CTA/CTP or MRI per protocol", "Glucose, ECG, troponin", "Swallow screen"],
    prevention: ["BP control", "Antithrombotic therapy matched to mechanism (antiplatelet vs anticoagulation for AF)", "Statin", "Carotid revascularization when indicated", "Lifestyle"],
    medications: [
      {
        class: "Hyperacute reperfusion then secondary prevention",
        examples: ["IV thrombolysis if eligible", "Endovascular thrombectomy for LVO", "Aspirin if thrombolysis not given", "High-intensity statin"],
        notes: "Do not give aspirin at home if thrombolysis might be used. EMS first.",
      },
    ],
    selfCare: ["Note the clock time", "Do not drive"],
    seekCare: "Call emergency services immediately.",
  }),
  defineDisease({
    id: "meningitis",
    name: "Meningitis (suspect)",
    icd10: "G03.9",
    specialty: "neurology",
    department: "Emergency / Infectious diseases — isolation",
    urgency: "emergency",
    setting: "Emergency department now",
    summary:
      "Infection of the meninges. Fever, neck stiffness, photophobia, and altered mentation. Bacterial disease can kill within hours; rash of meningococcemia is a late and ominous sign.",
    hallmarks: ["fever", "neck-stiffness", "headache", "photophobia", "confusion"],
    supportive: ["nausea", "vomiting", "malaise", "chills"],
    occasional: ["rash", "petechiae", "seizure"],
    vitals: { fever: true, highFever: true, tachy: true },
    comorbidBoost: ["immunocompromised"],
    redFlags: ["Petechial rash", "Rapid decline", "Seizure", "Focal neurology", "Infant inconsolability"],
    workup: ["Blood cultures", "Do not delay antibiotics for CT if bacterial disease likely", "Lumbar puncture when safe", "Viral PCR panel including HSV"],
    prevention: ["Meningococcal, pneumococcal, Hib vaccines", "Post-exposure prophylaxis for meningococcus", "Avoid sharing drinks in outbreak settings"],
    medications: [
      {
        class: "Immediate empiric IV antimicrobials ± dexamethasone",
        examples: ["Ceftriaxone (or cefotaxime) plus vancomycin", "Add ampicillin if Listeria risk", "Dexamethasone before or with first dose in suspected pneumococcal", "Acyclovir if HSV encephalitis possible"],
        notes: "Hospital protocol. Minutes matter.",
      },
    ],
    selfCare: ["Do not wait for a classic triad"],
    seekCare: "Call emergency services.",
  }),
  defineDisease({
    id: "migraine",
    name: "Migraine",
    icd10: "G43.909",
    specialty: "neurology",
    department: "Neurology / Primary care",
    urgency: "soon",
    setting: "Primary care / neurology; ED for first thunderclap, neurologic deficit, or status migrainosus",
    summary:
      "Recurrent primary headache, often unilateral and throbbing, with nausea, photophobia, and sometimes aura. New 'worst headache' is never assumed to be migraine until examined.",
    hallmarks: ["headache", "photophobia", "nausea", "aura"],
    supportive: ["vomiting", "blurred-vision", "fatigue"],
    occasional: ["dizziness", "neck-pain", "tinnitus"],
    age: [10, 55],
    sexBias: "female",
    redFlags: ["Thunderclap onset", "Fever and stiff neck", "Focal weakness", "New headache after 50", "Headache in pregnancy with visual change (pre-eclampsia)"],
    workup: ["Clinical ICHD-3 features", "Neuroimaging if red flags", "Fundoscopy if raised-ICP concern"],
    prevention: ["Regular sleep, meals, hydration", "Limit analgesic overuse", "Identify triggers", "Preventive Rx if ≥4 days/month"],
    medications: [
      {
        class: "Acute: NSAID, triptan, or gepant; antiemetic",
        examples: ["Ibuprofen / naproxen", "Sumatriptan", "Rimegepant / ubrogepant", "Metoclopramide"],
        notes: "Triptans are contraindicated in uncontrolled vascular disease. Do not use opioids as first-line.",
      },
      {
        class: "Prevention",
        examples: ["Propranolol", "Topiramate", "Amitriptyline", "CGRP monoclonal antibodies", "OnabotulinumtoxinA for chronic migraine"],
        notes: "Chosen by comorbidity and pregnancy plans.",
      },
    ],
    selfCare: ["Dark quiet room", "Treat early", "Headache diary"],
    seekCare: "ED for sudden worst headache, fever, or neurologic deficit.",
  }),
  defineDisease({
    id: "tension-headache",
    name: "Tension-type headache",
    icd10: "G44.209",
    specialty: "neurology",
    department: "Primary care",
    urgency: "self-care",
    setting: "Home / primary care",
    summary:
      "The most common primary headache: bilateral pressing 'band' pain without prominent nausea or photophobia. Often related to stress, posture, or analgesic overuse.",
    hallmarks: ["headache", "neck-pain"],
    supportive: ["fatigue", "insomnia", "irritability"],
    occasional: ["photophobia", "dizziness"],
    redFlags: ["Sudden severe onset", "Fever", "Focal signs"],
    workup: ["Clinical", "Review medication overuse", "Imaging only for red flags"],
    prevention: ["Ergonomics", "Sleep regularity", "Limit caffeine rebound", "Stress reduction", "Avoid daily simple analgesics"],
    medications: [
      {
        class: "Simple analgesia; prevention if frequent",
        examples: ["Acetaminophen", "Ibuprofen", "Amitriptyline for frequent TTH"],
        notes: "Combination analgesics with caffeine can rebound if used >10 days/month.",
      },
    ],
    selfCare: ["Heat, stretching, hydration", "Break the daily-pill cycle with a clinician if needed"],
    seekCare: "Clinic if headaches are weekly; ED for red flags.",
  }),
  defineDisease({
    id: "cluster-headache",
    name: "Cluster headache",
    icd10: "G44.009",
    specialty: "neurology",
    department: "Neurology / Emergency for first bout",
    urgency: "urgent",
    setting: "Neurology promptly; ED for first-ever severe unilateral orbital pain",
    summary:
      "Excruciating unilateral orbital pain in short bouts, with tearing, nasal congestion, and restlessness, often at night. One of the trigeminal autonomic cephalalgias.",
    hallmarks: ["headache", "eye-pain", "red-eyes", "runny-nose"],
    supportive: ["nasal-congestion", "photophobia"],
    occasional: ["nausea"],
    age: [20, 50],
    sexBias: "male",
    smokerBoost: true,
    redFlags: ["First episode (exclude secondary causes)", "Horner syndrome that persists", "Fever"],
    workup: ["Clinical", "MRI once to exclude mimics", "Oxygen trial diagnostically and therapeutically"],
    prevention: ["Avoid alcohol during a cluster bout", "Verapamil with ECG monitoring as preventive", "Smoking cessation"],
    medications: [
      {
        class: "Acute: high-flow oxygen and injectable triptan",
        examples: ["100% oxygen 12 L/min via NRB", "Sumatriptan subcutaneous"],
        notes: "Oral tablets are too slow. Bridging corticosteroids or greater-occipital nerve block sometimes used.",
      },
    ],
    selfCare: ["Do not drink alcohol during a bout", "Have a home oxygen plan if prescribed"],
    seekCare: "Urgent neurology; ED for first or worst episode.",
  }),
  defineDisease({
    id: "bppv",
    name: "Benign paroxysmal positional vertigo",
    icd10: "H81.10",
    specialty: "otolaryngology",
    department: "ENT / Neurology / Vestibular physiotherapy",
    urgency: "soon",
    setting: "Clinic for canalith repositioning; ED if stroke cannot be excluded",
    summary:
      "Otoconia in a semicircular canal. Brief spinning vertigo triggered by rolling in bed or looking up, with fatigable nystagmus on Dix-Hallpike. No persistent neurologic deficit.",
    hallmarks: ["vertigo", "dizziness", "nausea"],
    supportive: ["vomiting", "balance-problems"],
    occasional: ["tinnitus", "headache"],
    age: [40, 100],
    redFlags: ["Continuous vertigo", "Diplopia, dysarthria, weakness", "New hearing loss (labyrinthitis vs AICA stroke)"],
    workup: ["Dix-Hallpike / supine roll tests", "HINTS exam if acute vestibular syndrome", "Imaging if central signs"],
    prevention: ["Caution on ladders until treated", "Vitamin D if deficient and recurrent"],
    medications: [
      {
        class: "Canalith repositioning, not chronic vestibular suppressants",
        examples: ["Epley maneuver", "Short-term meclizine only for severe nausea"],
        notes: "Daily meclizine delays compensation. Treat the canal, not the symptom indefinitely.",
      },
    ],
    selfCare: ["Do not drive during spells", "Follow prescribed repositioning video/physiotherapy"],
    seekCare: "ED if vertigo with weakness, dysarthria, or continuous vomiting.",
  }),
  defineDisease({
    id: "bells-palsy",
    name: "Bell's palsy",
    icd10: "G51.0",
    specialty: "neurology",
    department: "Primary care / Neurology / Ophthalmology for eye care",
    urgency: "soon",
    setting: "Clinic within 72 hours of onset; ED if stroke cannot be excluded",
    summary:
      "Idiopathic facial-nerve (VII) paresis, usually HSV-related inflammation. Entire hemiface including forehead is weak. Forehead sparing suggests a central lesion (stroke until proven otherwise).",
    hallmarks: ["facial-droop"],
    supportive: ["ear-pain", "loss-of-smell", "tinnitus"],
    occasional: ["headache", "eye-pain"],
    age: [15, 70],
    redFlags: ["Forehead sparing", "Limb weakness", "Vesicles in the ear (Ramsay Hunt)", "Bilateral palsy (Lyme, GBS, sarcoid)"],
    workup: ["Clinical", "Lyme serology in endemic areas", "Stroke workup if forehead spared or additional signs"],
    prevention: ["Eye protection while the lid does not close", "Zoster vaccination reduces Ramsay Hunt risk"],
    medications: [
      {
        class: "Early corticosteroid ± antiviral",
        examples: ["Prednisone 60 mg taper (adult, typical)", "Valacyclovir if severe or zoster suspected"],
        notes: "Start within 72 hours. Artificial tears and night patch to prevent corneal injury.",
      },
    ],
    selfCare: ["Tape lid at night as instructed", "Facial exercises after the acute phase per therapy"],
    seekCare: "Same day to distinguish from stroke; ED if any arm/leg weakness or speech change.",
  }),
  defineDisease({
    id: "seizure-event",
    name: "Seizure / epilepsy presentation",
    icd10: "R56.9",
    specialty: "neurology",
    department: "Emergency / Neurology",
    urgency: "emergency",
    setting: "EMS / ED for first seizure, status, or injury; neurology follow-up for known epilepsy",
    summary:
      "Abnormal excessive neuronal activity: convulsions, staring, or focal twitching, often with post-ictal confusion. First seizures need a workup for provoked causes (glucose, sodium, infection, mass, toxic).",
    hallmarks: ["seizure", "loss-of-consciousness", "confusion"],
    supportive: ["headache", "fatigue", "muscle-aches"],
    occasional: ["incontinence", "oral-ulcers", "fever"],
    vitals: { tachy: true },
    comorbidBoost: ["kidney-disease"],
    redFlags: ["Seizure ≥5 minutes (status)", "Repeated seizures without recovery", "Pregnancy (eclampsia)", "Fever and stiff neck", "Head injury"],
    workup: ["ABCs, glucose", "Electrolytes, CBC, tox as indicated", "CT if first, focal, or trauma", "EEG and MRI in new unprovoked seizure"],
    prevention: ["Medication adherence", "Sleep, alcohol moderation", "Avoid strobe if photosensitive", "Water and driving safety counseling"],
    medications: [
      {
        class: "Abortive benzodiazepine then ASM",
        examples: ["Lorazepam / midazolam for status", "Levetiracetam, lamotrigine, valproate, carbamazepine — syndrome-specific"],
        notes: "Valproate is teratogenic — not for most people who can become pregnant. Driving laws vary; a clinician must advise.",
      },
    ],
    selfCare: ["Rescue plan for caregivers", "Do not put objects in the mouth", "Time the event"],
    seekCare: "Call emergency services for a first seizure or any seizure lasting over 5 minutes.",
  }),
  defineDisease({
    id: "concussion",
    name: "Concussion / mild traumatic brain injury",
    icd10: "S06.0X0A",
    specialty: "neurology",
    department: "Emergency / Sports medicine / Neurology",
    urgency: "urgent",
    setting: "ED if red flags; otherwise clinic and relative rest",
    summary:
      "Biomechanical brain injury with headache, fogginess, dizziness, and photophobia after a blow or whiplash. Loss of consciousness is not required. Second-impact and intracranial bleed are the feared complications.",
    hallmarks: ["headache", "dizziness", "confusion", "fatigue", "photophobia"],
    supportive: ["nausea", "insomnia", "balance-problems", "memory-loss"],
    occasional: ["vomiting", "tinnitus", "blurred-vision"],
    redFlags: ["Declining consciousness", "Repeated vomiting", "Seizure", "Focal weakness", "Anticoagulated patient", "Worsening headache"],
    workup: ["Canadian CT Head Rule / PECARN in children", "Neurologic exam", "Do not routinely image every concussion"],
    prevention: ["Sport-specific return-to-play protocols", "Helmets where indicated", "Do not return the same day"],
    medications: [
      {
        class: "Symptom-targeted, avoid routine opioids",
        examples: ["Acetaminophen", "Limited NSAID after bleed excluded", "Ondansetron for nausea"],
        notes: "Cognitive and physical relative rest 24–48 h then graded return. Sleep and mood support as needed.",
      },
    ],
    selfCare: ["Relative rest, then graded activity", "No alcohol", "A responsible adult should stay overnight after a significant injury"],
    seekCare: "ED for red flags; do not return to contact sport until cleared.",
  }),
  defineDisease({
    id: "peripheral-neuropathy",
    name: "Peripheral polyneuropathy",
    icd10: "G62.9",
    specialty: "neurology",
    department: "Neurology / Endocrinology if diabetic",
    urgency: "routine",
    setting: "Outpatient neurology / diabetes clinic",
    summary:
      "Length-dependent sensory (and sometimes motor) nerve injury. Stocking-glove numbness, tingling, and burning, most often from diabetes, B12 deficiency, alcohol, or medications.",
    hallmarks: ["numbness", "tingling", "muscle-weakness"],
    supportive: ["muscle-weakness", "balance-problems", "calf-cramps"],
    occasional: ["night-back-pain"],
    age: [25, 100],
    comorbidBoost: ["diabetes", "kidney-disease"],
    redFlags: ["Rapid ascending weakness (GBS)", "Bowel/bladder with back pain (cord/cauda)", "Asymmetric foot drop of abrupt onset"],
    workup: ["A1c, B12, SPEP in older adults, TSH", "EMG/NCS if atypical", "Medication review (chemo, INH, amiodarone)"],
    prevention: ["Glycemic and BP control", "Alcohol moderation", "Foot care and protective shoes", "B12 monitoring on metformin/acid suppression when indicated"],
    medications: [
      {
        class: "Neuropathic pain agents plus treat the cause",
        examples: ["Duloxetine", "Gabapentin / pregabalin", "Amitriptyline", "Topical capsaicin or lidocaine"],
        notes: "Opioids are not first-line. Treat B12 deficiency if present.",
      },
    ],
    selfCare: ["Daily foot inspection", "Fall-proof the home"],
    seekCare: "Urgent if rapidly progressive weakness or incontinence.",
  }),
  defineDisease({
    id: "acute-glaucoma",
    name: "Acute angle-closure glaucoma",
    icd10: "H40.20",
    specialty: "ophthalmology",
    department: "Ophthalmology emergency",
    urgency: "emergency",
    setting: "Emergency department / eye emergency the same hour",
    summary:
      "Sudden blockade of aqueous outflow. Severe unilateral eye pain, mid-dilated pupil, halos, headache, and nausea. Permanent vision loss can occur within hours.",
    hallmarks: ["eye-pain", "vision-loss", "headache", "nausea", "red-eyes"],
    supportive: ["vomiting", "photophobia", "blurred-vision"],
    occasional: ["abdominal-pain"],
    age: [40, 100],
    sexBias: "female",
    redFlags: ["Hard eye on palpation", "Halos around lights", "Vomiting with a red eye"],
    workup: ["Immediate intraocular pressure", "Slit lamp", "Gonioscopy"],
    prevention: ["Prophylactic iridotomy in the fellow eye", "Caution with anticholinergic/mydriatic drugs in anatomically narrow angles"],
    medications: [
      {
        class: "IOP-lowering bundle then laser iridotomy",
        examples: ["Timolol, apraclonidine, acetazolamide, pilocarpine as protocol", "Laser peripheral iridotomy"],
        notes: "Ophthalmology-directed. Analgesia and antiemetics support but do not replace pressure reduction.",
      },
    ],
    selfCare: ["Do not wait for a clinic appointment in the morning"],
    seekCare: "Emergency eye care immediately.",
  }),
  defineDisease({
    id: "retinal-detachment",
    name: "Retinal detachment (suspect)",
    icd10: "H33.20",
    specialty: "ophthalmology",
    department: "Vitreoretinal emergency",
    urgency: "emergency",
    setting: "Same-day ophthalmology / ED",
    summary:
      "Separation of neurosensory retina. New flashes, floaters, and a curtain over the visual field. Macula-on detachments are especially time-sensitive.",
    hallmarks: ["floaters-flash", "vision-loss", "blurred-vision"],
    supportive: ["photophobia"],
    occasional: ["eye-pain"],
    age: [40, 100],
    redFlags: ["Curtain or shadow in vision", "Sudden shower of floaters"],
    workup: ["Dilated fundus exam", "B-scan ultrasound if the view is obscured"],
    prevention: ["Prompt care for retinal tears", "Protective eyewear", "Counsel high myopes"],
    medications: [
      {
        class: "Surgical repair (not an oral medication disease)",
        examples: ["Pneumatic retinopexy", "Scleral buckle", "Vitrectomy"],
        notes: "Keep NPO if surgery is imminent. Do not fly with an intraocular gas bubble.",
      },
    ],
    selfCare: ["Limit activity as instructed", "Cover neither eye unless told"],
    seekCare: "Same-day retina / ED.",
  }),
];
