import { defineDisease } from "../define";

export const GI_ENDO_RENAL = [
  defineDisease({
    id: "gerd",
    name: "Gastroesophageal reflux disease",
    icd10: "K21.9",
    specialty: "gastroenterology",
    department: "Gastroenterology / Primary care",
    urgency: "routine",
    setting: "Primary care; GI if alarm features or incomplete response",
    summary:
      "Retrograde gastric contents causing heartburn and regurgitation, worse after meals and recumbency. Alarm features (dysphagia, weight loss, GI bleed, anemia) require endoscopy, not empiricism alone.",
    hallmarks: ["heartburn", "epigastric-pain"],
    supportive: ["cough", "hoarseness", "chest-pain", "nausea"],
    occasional: ["dysphagia", "sore-throat", "wheezing"],
    comorbidBoost: ["asthma"],
    smokerBoost: true,
    redFlags: ["Dysphagia or odynophagia", "GI bleeding", "Unintentional weight loss", "Anemia", "Vomiting"],
    workup: ["Empiric PPI trial if typical and no alarms", "EGD for alarms or failure", "pH/impedance in refractory disease", "H. pylori testing when ulcer suspected"],
    prevention: ["Weight reduction if overweight", "Head-of-bed elevation", "Avoid late meals", "Limit alcohol, tobacco, trigger foods"],
    medications: [
      {
        class: "Acid suppression",
        examples: ["Omeprazole, esomeprazole, pantoprazole (PPI)", "Famotidine (H2 blocker)", "Antacids for breakthrough"],
        notes: "Use the lowest effective PPI dose. Long-term PPI has risks (infection, malabsorption) — review annually.",
      },
    ],
    selfCare: ["Do not lie down within 3 hours of eating", "Loosen belts", "Track triggers"],
    seekCare: "Urgent GI/ED for vomiting blood, black stools, or food sticking.",
  }),
  defineDisease({
    id: "peptic-ulcer",
    name: "Peptic ulcer disease",
    icd10: "K27.9",
    specialty: "gastroenterology",
    department: "Gastroenterology / Emergency if bleeding or perforation",
    urgency: "soon",
    setting: "GI clinic; ED for bleed, perforation, or intractable pain",
    summary:
      "Mucosal break in stomach or duodenum, driven by H. pylori and NSAIDs. Epigastric pain related to meals, with risk of bleeding and perforation.",
    hallmarks: ["epigastric-pain", "nausea", "anorexia"],
    supportive: ["heartburn", "vomiting", "fatigue"],
    occasional: ["black-stool", "vomiting-blood", "weight-loss"],
    smokerBoost: true,
    redFlags: ["Melena", "Hematemesis", "Sudden severe abdomen (perforation)", "Syncope"],
    workup: ["H. pylori testing (stool antigen or breath, off PPI if possible)", "CBC", "EGD", "Upright x-ray if perforation suspected"],
    prevention: ["Test-and-treat H. pylori", "Avoid unnecessary NSAIDs; add PPI gastroprotection if NSAID is required", "Stop smoking"],
    medications: [
      {
        class: "PPI plus H. pylori eradication when positive",
        examples: ["Omeprazole-based quadruple therapy (bismuth, tetracycline, metronidazole)", "Pylera-type regimens", "High-dose PPI"],
        notes: "Clarithromycin triple therapy is often obsolete where resistance is high. Confirm eradication.",
      },
    ],
    selfCare: ["Stop NSAIDs unless a clinician says otherwise", "Avoid alcohol during healing"],
    seekCare: "ED for black stools, vomiting blood, or board-like abdomen.",
  }),
  defineDisease({
    id: "cholecystitis",
    name: "Acute cholecystitis / biliary colic",
    icd10: "K81.0",
    specialty: "gastroenterology",
    department: "Emergency / General surgery / GI",
    urgency: "urgent",
    setting: "ED; surgical admission if acute cholecystitis",
    summary:
      "Gallstone obstruction of the cystic duct. Biliary colic is episodic RUQ pain after fatty meals; acute cholecystitis adds fever, persistent pain, and Murphy sign.",
    hallmarks: ["ruq-pain", "nausea", "vomiting", "fever"],
    supportive: ["anorexia", "epigastric-pain", "sweating"],
    occasional: ["jaundice", "shoulder-tip-pain", "chills"],
    age: [20, 80],
    sexBias: "female",
    vitals: { fever: true, tachy: true },
    redFlags: ["Jaundice and fever (cholangitis — Charcot triad)", "Hypotension", "Pregnancy"],
    workup: ["CBC, CMP including bilirubin and ALP", "RUQ ultrasound", "HIDA if ultrasound equivocal", "Blood cultures if cholangitis"],
    prevention: ["Gradual weight loss if indicated (crash diets increase stones)", "Consider cholecystectomy after symptomatic stones"],
    medications: [
      {
        class: "Supportive then source control",
        examples: ["IV fluids, analgesia", "Antibiotics covering enteric gram-negatives and anaerobes (ceftriaxone+metronidazole or piperacillin-tazobactam)", "Early laparoscopic cholecystectomy when fit"],
        notes: "Cholangitis needs urgent biliary drainage (ERCP) plus antibiotics.",
      },
    ],
    selfCare: ["NPO until evaluated", "Do not take leftover pain meds and wait if febrile"],
    seekCare: "ED for persistent RUQ pain, fever, or jaundice.",
  }),
  defineDisease({
    id: "appendicitis",
    name: "Acute appendicitis",
    icd10: "K35.80",
    specialty: "emergency",
    department: "Emergency / General surgery",
    urgency: "emergency",
    setting: "Emergency department",
    summary:
      "Obstruction and infection of the appendix. Periumbilical pain migrating to the right lower quadrant, anorexia, low-grade fever, and rebound. Delay risks perforation.",
    hallmarks: ["rlq-pain", "anorexia", "nausea", "abdominal-pain", "rebound-pain"],
    supportive: ["fever", "vomiting", "malaise"],
    occasional: ["diarrhea", "dysuria"],
    age: [5, 50],
    vitals: { fever: true, tachy: true },
    pregnancyRisk: true,
    redFlags: ["Board-like abdomen", "Hypotension", "Pregnancy (atypical location)", "Young children with lethargy"],
    workup: ["CBC, CRP, pregnancy test", "RLQ ultrasound (preferred in children/pregnancy) or CT", "Surgical consult"],
    prevention: ["No reliable primary prevention; do not ignore migratory abdominal pain"],
    medications: [
      {
        class: "Source control ± antibiotics",
        examples: ["Laparoscopic appendectomy", "Perioperative cefazolin or broader coverage if perforated", "Selected antibiotic-first protocols for uncomplicated disease in trials/specialist programs"],
        notes: "Do not eat or drink if surgery is likely. Pain control should not delay imaging.",
      },
    ],
    selfCare: ["NPO", "Do not use a heating pad and wait overnight"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "diverticulitis",
    name: "Acute diverticulitis",
    icd10: "K57.92",
    specialty: "gastroenterology",
    department: "Emergency / Colorectal surgery / GI",
    urgency: "urgent",
    setting: "ED; outpatient only if mild, reliable, and no peritonitis",
    summary:
      "Inflammation of colonic diverticula, usually sigmoid. Left-lower-quadrant pain, fever, and change in bowel habit in middle-aged and older adults.",
    hallmarks: ["llq-pain", "fever", "anorexia"],
    supportive: ["nausea", "constipation", "diarrhea", "bloating"],
    occasional: ["blood-stool", "dysuria", "rebound-pain"],
    age: [40, 100],
    vitals: { fever: true },
    redFlags: ["Peritonitis", "Inability to tolerate oral intake", "Immunosuppression", "High fever"],
    workup: ["CBC, CRP, CMP", "CT abdomen/pelvis with contrast", "Do not colonoscopy in the acute attack"],
    prevention: ["High-fiber dietary pattern after resolution", "Smoking cessation", "Avoid unnecessary NSAIDs", "Colonoscopy after the first episode to exclude neoplasm (timing per GI)"],
    medications: [
      {
        class: "Selective antibiotics and source control",
        examples: ["Observation without antibiotics in selected immunocompetent mild cases", "Amoxicillin-clavulanate or ciprofloxacin+metronidazole when treating", "Drainage/surgery for abscess or perforation"],
        notes: "Antibiotics are not automatic for every mild episode — follow local surgical pathways.",
      },
    ],
    selfCare: ["Clear liquids advancing as pain allows if a clinician agrees outpatient care is safe"],
    seekCare: "ED for fever with severe left-sided pain.",
  }),
  defineDisease({
    id: "pancreatitis",
    name: "Acute pancreatitis",
    icd10: "K85.9",
    specialty: "gastroenterology",
    department: "Emergency / GI / Surgery if biliary",
    urgency: "emergency",
    setting: "Emergency department; admit",
    summary:
      "Autodigestive inflammation of the pancreas, most often gallstones or alcohol. Severe epigastric pain radiating to the back with vomiting. Risk of SIRS, necrosis, and hypocalcemia.",
    hallmarks: ["epigastric-pain", "vomiting", "nausea", "anorexia"],
    supportive: ["fever", "sweating", "abdominal-pain"],
    occasional: ["jaundice", "shortness-of-breath", "constipation"],
    vitals: { tachy: true, fever: true, hypotensive: true },
    redFlags: ["Hypotension", "Hypoxia", "Confusion", "Rigid abdomen"],
    workup: ["Lipase (≥3× ULN)", "Ultrasound for stones", "CBC, CMP, triglycerides, calcium", "CT if diagnostic uncertainty or failure to improve"],
    prevention: ["Gallstone management", "Alcohol cessation", "Triglyceride control", "Drug review (e.g., azathioprine, GLP-1 caution as advised)"],
    medications: [
      {
        class: "Supportive; ERCP if cholangitis",
        examples: ["Goal-directed IV fluids", "Multimodal analgesia", "Early oral feeding as tolerated", "ERCP for concomitant cholangitis"],
        notes: "Routine prophylactic antibiotics are not indicated without infected necrosis.",
      },
    ],
    selfCare: ["Do not drink alcohol", "NPO until a clinician says otherwise"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "ibs",
    name: "Irritable bowel syndrome",
    icd10: "K58.9",
    specialty: "gastroenterology",
    department: "Gastroenterology / Primary care",
    urgency: "routine",
    setting: "Primary care / GI for refractory or atypical features",
    summary:
      "Disorder of gut–brain interaction. Recurrent abdominal pain related to defecation with change in frequency or form, without alarm features or inflammatory markers.",
    hallmarks: ["abdominal-pain", "bloating", "diarrhea", "constipation"],
    supportive: ["nausea", "fatigue", "anxiety", "food-intolerance"],
    occasional: ["mucus-stool", "headache"],
    age: [15, 60],
    sexBias: "female",
    redFlags: ["Blood in stool", "Nocturnal diarrhea", "Weight loss", "Fever", "Onset after 50", "Family history of IBD/CRC"],
    workup: ["Rome IV history", "CBC, CRP, fecal calprotectin, celiac serology", "Colonoscopy if alarms or age-appropriate screening due"],
    prevention: ["Regular meals, soluble fiber", "Limit ultra-processed trigger foods as identified", "Address stress and sleep", "Avoid chronic opioid use for cramps"],
    medications: [
      {
        class: "Symptom-targeted (diarrhea, constipation, pain)",
        examples: ["Psyllium", "Loperamide for diarrhea-predominant", "Polyethylene glycol for constipation", "Antispasmodics", "Low-dose TCA", "Secretagogues (linaclotide) in IBS-C"],
        notes: "Low-FODMAP is a time-limited dietitian-led trial, not a forever elimination.",
      },
    ],
    selfCare: ["Food and symptom diary", "Walking", "Gut-directed CBT or hypnotherapy where available"],
    seekCare: "Prompt GI if blood, weight loss, or iron deficiency.",
  }),
  defineDisease({
    id: "ibd-flare",
    name: "Inflammatory bowel disease flare (Crohn / UC)",
    icd10: "K52.9",
    specialty: "gastroenterology",
    department: "Gastroenterology / IBD clinic / Emergency if severe",
    urgency: "urgent",
    setting: "GI same week; ED for bleeding, fever, or obstruction",
    summary:
      "Relapse of Crohn disease or ulcerative colitis. Bloody diarrhea, urgency, abdominal pain, weight loss, and systemic inflammation. Extra-intestinal eyes, joints, and skin may accompany.",
    hallmarks: ["diarrhea", "blood-stool", "abdominal-pain", "urgency", "weight-loss"],
    supportive: ["fever", "fatigue", "anorexia", "joint-pain"],
    occasional: ["oral-ulcers", "eye-pain", "anal-pain"],
    age: [10, 60],
    vitals: { fever: true, tachy: true },
    redFlags: [">6 bloody stools/day", "Fever and tachycardia (severe colitis)", "Peritonitis", "Obstructive vomiting", "Pregnancy"],
    workup: ["CBC, CRP, albumin, fecal calprotectin", "Stool infection panel including C. difficile", "Flex sig in severe UC", "Imaging for Crohn complications"],
    prevention: ["Medication adherence (do not stop biologics without GI)", "Vaccinations while immunosuppressed per ID", "Smoking cessation (Crohn)", "Colonoscopic dysplasia surveillance"],
    medications: [
      {
        class: "Anti-inflammatory and advanced therapy",
        examples: ["Mesalamine (UC)", "Corticosteroids for induction not maintenance", "Thiopurines, methotrexate", "Anti-TNF, anti-integrin, anti-IL-23, JAK inhibitors"],
        notes: "Choice is IBD-team directed. Steroid-dependence is a reason to escalate, not to stay on prednisone.",
      },
    ],
    selfCare: ["Hydration, nutrition support", "Do not take NSAIDs for pain without GI advice"],
    seekCare: "ED for heavy bleeding, high fever, or severe distension.",
  }),
  defineDisease({
    id: "viral-hepatitis",
    name: "Acute viral hepatitis",
    icd10: "B19.9",
    specialty: "gastroenterology",
    department: "Hepatology / Infectious diseases",
    urgency: "urgent",
    setting: "GI/ID promptly; hospitalize if coagulopathy, encephalopathy, or pregnancy (HEV/HBV)",
    summary:
      "Hepatotropic viruses (A, B, C, E) or EBV/CMV. Prodrome of fatigue and anorexia then jaundice, dark urine, and right-upper discomfort. HAV/HEV are fecal–oral; HBV/HCV blood-borne.",
    hallmarks: ["jaundice", "fatigue", "anorexia", "ruq-pain", "nausea"],
    supportive: ["fever", "malaise", "vomiting", "pale-skin"],
    occasional: ["joint-pain", "rash", "itch"],
    vitals: { fever: true },
    travelBoost: true,
    redFlags: ["Confusion (encephalopathy)", "Bleeding / high INR", "Pregnancy", "Hypoglycemia"],
    workup: ["ALT/AST, bilirubin, INR, albumin", "Hep A IgM, HBsAg, HBc IgM, HCV Ab/RNA, HEV if indicated", "Acetaminophen level", "Abdominal ultrasound"],
    prevention: ["HAV and HBV vaccines", "Safe needles and sex", "Food/water precautions", "Do not share razors"],
    medications: [
      {
        class: "Supportive; antivirals for selected HBV / HEV in pregnancy per specialist",
        examples: ["N-acetylcysteine if acetaminophen co-toxicity", "Tenofovir or entecavir for severe acute HBV in selected cases", "Avoid hepatotoxic drugs including excess acetaminophen"],
        notes: "Acute HAV is supportive. HCV is usually treated in the chronic phase with DAAs.",
      },
    ],
    selfCare: ["No alcohol", "Hygiene to protect household (HAV)"],
    seekCare: "Urgent if jaundiced with confusion or bleeding; same-week labs for painless jaundice.",
  }),
  defineDisease({
    id: "celiac",
    name: "Celiac disease",
    icd10: "K90.0",
    specialty: "gastroenterology",
    department: "Gastroenterology / Nutrition",
    urgency: "routine",
    setting: "GI clinic — do not start gluten-free diet before testing",
    summary:
      "Immune enteropathy to gluten in genetically susceptible people. Iron deficiency, bloating, diarrhea, weight loss, dermatitis herpetiformis, and fatigue. Testing must occur while still eating gluten.",
    hallmarks: ["bloating", "diarrhea", "fatigue", "weight-loss", "food-intolerance"],
    supportive: ["abdominal-pain", "anorexia", "pale-skin"],
    occasional: ["rash", "joint-pain", "oral-ulcers"],
    age: [1, 80],
    redFlags: ["Severe weight loss", "Positive FHx with alarm GI bleeding"],
    workup: ["IgA tTG plus total IgA", "Endoscopic biopsies while on gluten", "Iron studies, B12, folate, vitamin D, DEXA later", "Family screening"],
    prevention: ["Lifelong gluten-free diet after confirmed diagnosis", "Dietitian-led label reading", "Pneumococcal vaccine if hyposplenic features"],
    medications: [
      {
        class: "Nutrient repletion; no routine drug therapy",
        examples: ["Iron", "Vitamin D", "Calcium", "B12 if deficient"],
        notes: "Oats must be certified gluten-free. Experimental therapies are specialist-only.",
      },
    ],
    selfCare: ["Do not self-start a gluten-free diet before serology/biopsy", "Join a reputable celiac society for safe-food lists"],
    seekCare: "GI referral for unexplained iron deficiency or chronic diarrhea.",
  }),
  defineDisease({
    id: "bowel-obstruction",
    name: "Bowel obstruction (suspect)",
    icd10: "K56.60",
    specialty: "emergency",
    department: "Emergency / General surgery",
    urgency: "emergency",
    setting: "Emergency department",
    summary:
      "Mechanical blockage of intestine, often adhesions, hernia, or tumor. Colicky pain, distension, vomiting, and obstipation. Strangulation is a surgical emergency.",
    hallmarks: ["abdominal-pain", "vomiting", "constipation", "bloating"],
    supportive: ["anorexia", "nausea"],
    occasional: ["fever", "rebound-pain"],
    age: [18, 100],
    vitals: { tachy: true },
    redFlags: ["Peritonitis", "Fever with leukocytosis (ischemia)", "Incarcerated hernia"],
    workup: ["CBC, CMP, lactate", "Abdominal series or CT", "NPO, NG decompression", "Surgical consult"],
    prevention: ["Hernia repair when indicated", "Do not ignore obstipation after prior surgery"],
    medications: [
      {
        class: "Resuscitation and source control",
        examples: ["IV fluids", "Antiemetics", "Antibiotics if ischemia/perforation", "Surgery or endoscopic stenting depending on cause"],
        notes: "Do not give stimulant laxatives in complete obstruction.",
      },
    ],
    selfCare: ["NPO"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "t2dm-symptomatic",
    name: "Symptomatic type 2 diabetes / hyperglycemia",
    icd10: "E11.65",
    specialty: "endocrinology",
    department: "Endocrinology / Primary care",
    urgency: "soon",
    setting: "Primary care promptly; ED if DKA/HHS features",
    summary:
      "Insulin resistance with progressive beta-cell failure. Polyuria, polydipsia, fatigue, blurred vision, and infections. Many people are diagnosed on screening before symptoms.",
    hallmarks: ["polyuria", "thirst", "fatigue", "blurred-vision", "polyphagia"],
    supportive: ["weight-loss", "frequency", "delayed-wound", "numbness"],
    occasional: ["nausea", "fruity-breath"],
    age: [25, 100],
    comorbidBoost: ["diabetes", "hypertension"],
    redFlags: ["Kussmaul breathing", "Fruity breath", "Confusion", "Vomiting (DKA/HHS)"],
    workup: ["A1c, fasting glucose", "BMP, urine ketones if ill", "Lipids, urine albumin, dilated eye exam", "C-peptide/antibodies if type 1/LADA possible"],
    prevention: ["Weight reduction of 5–10% delays T2D", "Mediterranean/DASH pattern", "150 minutes activity weekly", "Screen high-risk adults"],
    medications: [
      {
        class: "Glucose-lowering with cardiorenal benefit when indicated",
        examples: ["Metformin", "SGLT2 inhibitor", "GLP-1 receptor agonist", "Insulin if catabolic or severe hyperglycemia", "Statin and ACE/ARB as indicated"],
        notes: "Hypoglycemia education if on insulin or sulfonylurea. Sick-day rules matter.",
      },
    ],
    selfCare: ["Home glucose as prescribed", "Foot care", "Never skip insulin in type 1 because you are not eating — call for sick-day advice"],
    seekCare: "ED for vomiting, deep breathing, or confusion with known diabetes.",
  }),
  defineDisease({
    id: "dka",
    name: "Diabetic ketoacidosis",
    icd10: "E11.10",
    specialty: "endocrinology",
    department: "Emergency / ICU / Endocrinology",
    urgency: "emergency",
    setting: "Emergency department now",
    summary:
      "Insulin deficiency causing ketosis and anion-gap acidosis, classically in type 1 but also in type 2 under stress. Polyuria, vomiting, abdominal pain, Kussmaul respirations, and fruity breath.",
    hallmarks: ["thirst", "polyuria", "vomiting", "abdominal-pain", "fruity-breath", "fatigue"],
    supportive: ["nausea", "confusion", "weight-loss", "shortness-of-breath"],
    occasional: ["fever"],
    vitals: { tachy: true, hypotensive: true },
    comorbidBoost: ["diabetes"],
    redFlags: ["Kussmaul breathing", "Altered mentation", "Shock"],
    workup: ["Glucose, VBG/ABG, anion gap, ketones, potassium (often high but total body K low)", "Infection workup", "A1c"],
    prevention: ["Never omit basal insulin", "Sick-day ketone testing", "Pump failure education", "Prompt care for infection"],
    medications: [
      {
        class: "Protocolized IV insulin, fluids, and electrolyte repletion",
        examples: ["Isotonic saline then dextrose when glucose falls", "IV regular insulin infusion", "Potassium replacement", "Treat the precipitant"],
        notes: "Hospital ICU/ward protocol. Do not self-treat suspected DKA with extra home insulin alone.",
      },
    ],
    selfCare: ["Call emergency services"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "hypoglycemia",
    name: "Hypoglycemia",
    icd10: "E16.2",
    specialty: "endocrinology",
    department: "Emergency if severe; diabetes clinic for prevention",
    urgency: "emergency",
    setting: "Treat immediately; EMS if seizure, coma, or no glucagon/carbs",
    summary:
      "Glucose low enough to cause autonomic and neuroglycopenic symptoms — tremor, sweating, confusion, seizure — usually from insulin or sulfonylureas mismatched to food or activity.",
    hallmarks: ["sweating", "tremor", "confusion", "palpitations", "polyphagia"],
    supportive: ["dizziness", "anxiety", "blurred-vision", "headache"],
    occasional: ["seizure", "loss-of-consciousness"],
    comorbidBoost: ["diabetes", "kidney-disease"],
    redFlags: ["Seizure", "Unconsciousness", "On insulin/SU and cannot swallow"],
    workup: ["Capillary then plasma glucose", "Medication review", "If not on glucose-lowering drugs: insulin, C-peptide, sulfonylurea screen, cortisol"],
    prevention: ["Match insulin to meals", "Carry rapid carbohydrate", "Glucagon kit for contacts", "Avoid driving until recovered 45 minutes"],
    medications: [
      {
        class: "Immediate glucose then review the regimen",
        examples: ["15 g rapid carbohydrate if conscious", "IM/IN glucagon if unconscious", "IV dextrose in EMS/ED", "Octreotide for sulfonylurea-induced hypoglycemia in hospital"],
        notes: "Recheck in 15 minutes. Identify the cause before the next dose of insulin.",
      },
    ],
    selfCare: ["Rule of 15 if awake and able to swallow", "Do not drive"],
    seekCare: "EMS if unconscious or glucagon used.",
  }),
  defineDisease({
    id: "hypothyroidism",
    name: "Hypothyroidism",
    icd10: "E03.9",
    specialty: "endocrinology",
    department: "Endocrinology / Primary care",
    urgency: "soon",
    setting: "Outpatient; ED for myxedema coma (rare)",
    summary:
      "Thyroid hormone deficiency, usually autoimmune (Hashimoto). Fatigue, cold intolerance, weight gain, constipation, dry skin, and bradycardia. Myxedema coma is a winter emergency in older adults.",
    hallmarks: ["fatigue", "cold-intolerance", "weight-gain", "constipation", "hair-loss"],
    supportive: ["depressed-mood", "dry-skin", "edema-legs"],
    occasional: ["goiter", "memory-loss", "heavy-menses"],
    age: [15, 90],
    sexBias: "female",
    vitals: { brady: true },
    redFlags: ["Hypothermia with confusion (myxedema)", "Pericardial effusion / severe bradycardia"],
    workup: ["TSH, free T4", "TPO antibodies", "Lipids", "ECG if bradycardic"],
    prevention: ["Iodine sufficiency", "Monitor TSH on lithium, amiodarone, after neck radiation", "Pre-pregnancy TSH optimization"],
    medications: [
      {
        class: "Levothyroxine replacement",
        examples: ["Levothyroxine (T4)"],
        notes: "Take on an empty stomach, separate from iron/calcium. Lower starting dose in older adults and CAD. Do not use desiccated thyroid as first-line.",
      },
    ],
    selfCare: ["Do not skip tablets", "Report chest pain after dose increases"],
    seekCare: "ED for hypothermia, confusion, or bradycardia with known hypothyroidism.",
  }),
  defineDisease({
    id: "hyperthyroidism",
    name: "Hyperthyroidism / thyrotoxicosis",
    icd10: "E05.90",
    specialty: "endocrinology",
    department: "Endocrinology; ED for thyroid storm",
    urgency: "soon",
    setting: "Endocrine clinic promptly; ED if storm features",
    summary:
      "Excess thyroid hormone — Graves, toxic nodule, or thyroiditis. Heat intolerance, weight loss, tremor, palpitations, and anxiety. Thyroid storm is life-threatening.",
    hallmarks: ["heat-intolerance", "weight-loss", "palpitations", "tremor", "sweating"],
    supportive: ["anxiety", "diarrhea", "fatigue", "goiter"],
    occasional: ["red-eyes", "double-vision", "irregular-heartbeat"],
    age: [15, 70],
    sexBias: "female",
    vitals: { tachy: true },
    redFlags: ["Fever with thyrotoxicosis (storm)", "AF with heart failure", "Severe eye pain"],
    workup: ["TSH, free T4/T3", "TRAb for Graves", "Radioactive uptake if needed (not in pregnancy/breastfeeding)", "ECG"],
    prevention: ["Adherence after radioiodine or surgery", "Iodine contrast caution in at-risk patients", "Smoking cessation for Graves orbitopathy"],
    medications: [
      {
        class: "Symptom control then disease-specific therapy",
        examples: ["Propranolol or atenolol", "Methimazole (PTU in first trimester pregnancy)", "Radioiodine", "Thyroidectomy"],
        notes: "Agranulocytosis counseling with thionamides: stop and get a CBC for fever/sore throat.",
      },
    ],
    selfCare: ["Avoid extra iodine/kelp supplements", "Seek care for fever while on methimazole"],
    seekCare: "ED for fever, delirium, or heart failure with known thyrotoxicosis.",
  }),
  defineDisease({
    id: "cystitis",
    name: "Acute cystitis (lower UTI)",
    icd10: "N30.00",
    specialty: "urology",
    department: "Primary care / Urgent care / Urology if recurrent",
    urgency: "soon",
    setting: "Clinic or telehealth for uncomplicated; ED if pyelo features or pregnancy",
    summary:
      "Bladder infection, typically E. coli. Dysuria, frequency, urgency, and suprapubic discomfort without fever or flank pain in uncomplicated women.",
    hallmarks: ["dysuria", "frequency", "urgency", "pelvic-pain"],
    supportive: ["hematuria", "malaise"],
    occasional: ["fever", "back-pain"],
    sexBias: "female",
    pregnancyRisk: true,
    redFlags: ["Fever or flank pain (pyelonephritis)", "Pregnancy", "Male sex (complicated until assessed)", "Immunocompromise", "Catheter"],
    workup: ["Urinalysis ± culture", "Pregnancy test", "Culture always in pregnancy, men, recurrence, and treatment failure"],
    prevention: ["Void after intercourse", "Adequate hydration", "Avoid spermicides if recurrent", "Vaginal estrogen in postmenopausal recurrent UTI"],
    medications: [
      {
        class: "Short-course antibiotic matched to local resistance",
        examples: ["Nitrofurantoin", "Trimethoprim-sulfamethoxazole if susceptible", "Fosfomycin", "Pivmecillinam where available"],
        notes: "Avoid fluoroquinolones as first-line for simple cystitis. Phenazopyridine is short-term symptom relief only.",
      },
    ],
    selfCare: ["Fluids", "Do not hold urine"],
    seekCare: "Same day if pregnant, male, febrile, or flank pain.",
  }),
  defineDisease({
    id: "pyelonephritis",
    name: "Acute pyelonephritis",
    icd10: "N10",
    specialty: "nephrology",
    department: "Emergency / Infectious diseases / Urology",
    urgency: "urgent",
    setting: "ED; many require IV antibiotics at least initially",
    summary:
      "Ascending infection of the renal pelvis and parenchyma. Fever, flank pain, nausea, and lower-urinary symptoms. Can seed the bloodstream.",
    hallmarks: ["flank-pain", "fever", "chills", "dysuria", "nausea"],
    supportive: ["vomiting", "frequency", "malaise"],
    occasional: ["hematuria", "abdominal-pain"],
    vitals: { fever: true, highFever: true, tachy: true },
    pregnancyRisk: true,
    comorbidBoost: ["diabetes", "kidney-disease"],
    redFlags: ["Hypotension", "Pregnancy", "Obstruction / stone", "Male sex with fever"],
    workup: ["UA and culture", "CBC, CMP, blood cultures if septic", "Pregnancy test", "Imaging if obstruction, stone, or failure at 48–72 h"],
    prevention: ["Treat lower UTI promptly in pregnancy", "Relieve obstruction", "Glycemic control"],
    medications: [
      {
        class: "Systemic antibiotics then oral step-down",
        examples: ["Ceftriaxone IV", "Ciprofloxacin if local resistance allows", "TMP-SMX if susceptible", "Beta-lactam in pregnancy (no FQ/TMP-SMX first trimester)"],
        notes: "14-day courses historically; shorter IV-to-oral pathways are used when recovering. Urology if obstructed (pus under pressure).",
      },
    ],
    selfCare: ["Do not rely on cranberry juice as treatment"],
    seekCare: "Emergency department for fever plus flank pain.",
  }),
  defineDisease({
    id: "nephrolithiasis",
    name: "Nephrolithiasis (kidney stone)",
    icd10: "N20.0",
    specialty: "urology",
    department: "Emergency / Urology",
    urgency: "urgent",
    setting: "ED for first or severe colic; urology for stone >5–6 mm, infection, or AKI",
    summary:
      "Ureteric colic from a calculus. Sudden severe flank pain radiating to the groin, restlessness, hematuria, and nausea. Infected obstructing stone is a urologic emergency.",
    hallmarks: ["flank-pain", "hematuria", "nausea", "vomiting"],
    supportive: ["dysuria", "frequency", "sweating"],
    occasional: ["fever", "abdominal-pain"],
    age: [18, 70],
    sexBias: "male",
    vitals: { tachy: true },
    redFlags: ["Fever (infected stone)", "Anuria / solitary kidney", "Intractable vomiting", "Pregnancy"],
    workup: ["UA, CBC, CMP (creatinine)", "Noncontrast CT or ultrasound (pregnancy, young, recurrent)", "Strain urine"],
    prevention: ["High fluid intake (urine pale)", "Sodium reduction", "Thiazide, citrate, or allopurinol based on stone analysis and 24-h urine"],
    medications: [
      {
        class: "Analgesia, medical expulsive therapy, and source control if infected",
        examples: ["NSAID first-line if safe", "Tamsulosin for selected distal stones", "Ondansetron", "Urgent decompression plus antibiotics if infected obstruction"],
        notes: "Alpha-blockers help some distal stones; they are not a substitute for drainage of an infected kidney.",
      },
    ],
    selfCare: ["Fluids as tolerated", "Strain urine", "Keep the stone for analysis"],
    seekCare: "ED for fever, one kidney, or pain not controlled with simple measures.",
  }),
  defineDisease({
    id: "bph",
    name: "Benign prostatic hyperplasia",
    icd10: "N40.1",
    specialty: "urology",
    department: "Urology / Primary care",
    urgency: "routine",
    setting: "Primary care / urology; ED for acute retention",
    summary:
      "Non-cancerous prostate enlargement causing LUTS: weak stream, hesitancy, nocturia, and incomplete emptying in older men. Retention and recurrent UTI are complications.",
    hallmarks: ["nocturia", "frequency", "urgency", "incontinence"],
    supportive: ["weak-stream", "pelvic-pain"],
    occasional: ["hematuria", "dysuria"],
    age: [50, 100],
    sexBias: "male",
    redFlags: ["Acute inability to void", "Fever with retention", "Renal failure", "Hard nodular prostate (cancer workup)"],
    workup: ["IPSS score", "UA, PSA shared decision", "Post-void residual", "Creatinine if chronic retention"],
    prevention: ["Limit evening fluids and alcohol", "Avoid decongestants and anticholinergics that precipitate retention", "Weight and activity"],
    medications: [
      {
        class: "Alpha-blocker ± 5-alpha-reductase inhibitor",
        examples: ["Tamsulosin", "Alfuzosin", "Finasteride", "Dutasteride", "Tadalafil daily in selected"],
        notes: "Floppy-iris counseling before cataract surgery. Finasteride lowers PSA — interpret accordingly.",
      },
    ],
    selfCare: ["Double voiding", "Timed voids"],
    seekCare: "ED if you cannot pass urine.",
  }),
  defineDisease({
    id: "prostatitis",
    name: "Acute bacterial prostatitis",
    icd10: "N41.0",
    specialty: "urology",
    department: "Urology / Emergency",
    urgency: "urgent",
    setting: "ED or urgent urology; many need IV antibiotics initially",
    summary:
      "Acute prostate infection. Perineal and pelvic pain, fever, dysuria, and obstructive voiding. The gland is exquisitely tender; vigorous massage is contraindicated in the acute phase.",
    hallmarks: ["pelvic-pain", "fever", "dysuria", "frequency", "chills"],
    supportive: ["malaise", "muscle-aches", "urgency"],
    occasional: ["hematuria", "low-urine"],
    age: [20, 80],
    sexBias: "male",
    vitals: { fever: true, tachy: true },
    redFlags: ["Sepsis", "Acute retention", "Immunocompromise"],
    workup: ["UA and culture", "Blood cultures if febrile", "Gentle DRE", "Imaging if abscess suspected"],
    prevention: ["Safe catheter care", "Treat UTI promptly in men"],
    medications: [
      {
        class: "Prolonged, prostate-penetrating antibiotics",
        examples: ["Ciprofloxacin or levofloxacin if susceptible", "TMP-SMX", "IV ceftriaxone then oral step-down"],
        notes: "Courses are typically 2–4 weeks. STI coverage (ceftriaxone + doxycycline) in younger sexually active men.",
      },
    ],
    selfCare: ["Hydration, analgesia, stool softener", "Sitz baths"],
    seekCare: "ED for fever with pelvic pain in men.",
  }),
  defineDisease({
    id: "ckd-symptomatic",
    name: "Chronic kidney disease (symptomatic)",
    icd10: "N18.9",
    specialty: "nephrology",
    department: "Nephrology",
    urgency: "soon",
    setting: "Nephrology clinic; ED for hyperkalemia, volume overload, or uremia",
    summary:
      "Sustained reduction in GFR or albuminuria. Fatigue, edema, nocturia, pruritus, and anorexia appear late. Hypertension and diabetes are the leading causes.",
    hallmarks: ["fatigue", "edema-legs", "nocturia", "anorexia"],
    supportive: ["itch", "nausea", "pale-skin", "shortness-of-breath"],
    occasional: ["confusion", "low-urine", "bone-pain"],
    age: [30, 100],
    comorbidBoost: ["diabetes", "hypertension", "kidney-disease"],
    redFlags: ["Kussmaul / uremic encephalopathy", "Hyperkalemia symptoms", "Anuria", "Pulmonary edema"],
    workup: ["eGFR, UACR, electrolytes, CBC, phosphate, PTH, vitamin D", "Renal ultrasound", "Medication review (NSAIDs, ACE/ARB, diuretics)"],
    prevention: ["BP and diabetes targets", "SGLT2 inhibitors in indicated CKD", "ACE/ARB for albuminuria", "Avoid NSAIDs and contrast when possible", "Vaccination"],
    medications: [
      {
        class: "Kidney and CV protection plus complication treatment",
        examples: ["ACE inhibitor / ARB", "SGLT2 inhibitor", "Statin", "Loop diuretic for volume", "ESA and iron for anemia — specialist", "Phosphate binders"],
        notes: "Doses of many drugs need renal adjustment. Hyperkalemia is an emergency.",
      },
    ],
    selfCare: ["Daily weights if volume-prone", "Sick-day rules for ACE/ARB/SGLT2/diuretics", "Low-sodium eating pattern"],
    seekCare: "ED for severe swelling with breathlessness, or very little urine.",
  }),
];
