import { defineDisease } from "../define";

export const HOSPITAL_PLUS = [
  defineDisease({
    id: "c-diff",
    name: "Clostridioides difficile colitis",
    icd10: "A04.72",
    specialty: "infectious-disease",
    department: "Infectious diseases / Gastroenterology",
    urgency: "urgent",
    setting: "Outpatient if stable; hospitalize for shock, megacolon, or ileus",
    summary:
      "Toxin-mediated colitis after antibiotics or healthcare exposure. Watery diarrhea, cramping, fever, and leukocytosis; fulminant disease can cause toxic megacolon.",
    hallmarks: ["diarrhea", "abdominal-pain", "fever", "malaise"],
    supportive: ["abdominal-pain", "anorexia", "tenesmus", "dehydration"],
    occasional: ["blood-stool", "vomiting", "confusion"],
    age: [16, 100],
    vitals: { fever: true, tachy: true },
    comorbidBoost: ["immunocompromised", "cancer", "kidney-disease"],
    redFlags: ["Ileus or toxic megacolon", "Shock", "Severe abdominal distension", "WBC >20 or rising lactate"],
    workup: ["Stool C. difficile toxin/NAAT", "CBC, creatinine, albumin", "Abdominal imaging if peritonitis or ileus"],
    prevention: [
      "Stewardship: avoid unnecessary antibiotics, especially clindamycin and fluoroquinolones",
      "Soap-and-water hand hygiene (alcohol gel does not kill spores)",
      "Contact precautions in healthcare",
      "Avoid gastric acid suppression when not needed",
    ],
    medications: [
      {
        class: "Oral targeted antibiotics",
        examples: ["Fidaxomicin", "Vancomycin PO"],
        notes: "Metronidazole is no longer first-line for most adults. Never use antimotility agents in fulminant disease.",
      },
      {
        class: "Recurrent-disease options",
        examples: ["Bezlotoxumab", "Fecal microbiota restoration (selected)"],
        notes: "Specialist pathways after multiple recurrences.",
      },
    ],
    selfCare: ["Hydration, contact isolation at home", "Do not take leftover antibiotics"],
    seekCare: "Same-day care for high-volume diarrhea after antibiotics; emergency if dizzy, confused, or the abdomen is rigid.",
  }),
  defineDisease({
    id: "infective-endocarditis",
    name: "Infective endocarditis (suspect)",
    icd10: "I33.0",
    specialty: "cardiology",
    department: "Cardiology / Infectious diseases / Emergency",
    urgency: "emergency",
    setting: "Hospital — blood cultures before antibiotics whenever possible",
    summary:
      "Infection of heart valves or endocardium. Fever, new murmur, embolic phenomena, and risk in injection-drug use, prosthetic valves, or congenital heart disease.",
    hallmarks: ["fever", "fatigue", "malaise", "night-sweats"],
    supportive: ["chills", "anorexia", "weight-loss", "joint-pain", "petechiae"],
    occasional: ["shortness-of-breath", "chest-pain", "confusion", "hematuria", "back-pain"],
    vitals: { fever: true, tachy: true },
    comorbidBoost: ["heart-disease", "immunocompromised", "cancer"],
    redFlags: ["Acute heart failure", "Stroke during bacteremia", "Heart block", "Severe valvular regurgitation"],
    workup: ["Three sets of blood cultures before antibiotics", "Transthoracic then transesophageal echo", "Duke criteria", "Dental source exam"],
    prevention: [
      "Dental hygiene; antibiotic prophylaxis only for the highest-risk cardiac lesions",
      "Harm reduction and sterile injection equipment",
      "Prompt treatment of bacteremia and skin infection",
    ],
    medications: [
      {
        class: "Prolonged IV bactericidal combination therapy",
        examples: ["Directed by organism: anti-staph beta-lactam ± gentamicin/rifampin in selected prosthetic cases"],
        notes: "Empiric regimens are protocol-based after cultures. Never delay cultures for a stable patient; do not delay antibiotics in shock.",
      },
    ],
    selfCare: ["This is not a home illness"],
    seekCare: "Emergency department for unexplained fever with a valve, pacemaker, or injection-drug use.",
  }),
  defineDisease({
    id: "hiv-acute",
    name: "Acute HIV infection",
    icd10: "B20",
    specialty: "infectious-disease",
    department: "Infectious diseases / Sexual health",
    urgency: "soon",
    setting: "Outpatient sexual-health / ID clinic; hospital if opportunistic disease",
    summary:
      "Mononucleosis-like seroconversion illness 2–4 weeks after exposure: fever, rash, pharyngitis, lymphadenopathy, and mucosal ulcers. Window-period testing can miss it.",
    hallmarks: ["fever", "malaise", "sore-throat", "rash", "swollen-lymph"],
    supportive: ["fatigue", "headache", "muscle-aches", "night-sweats", "oral-ulcers"],
    occasional: ["diarrhea", "nausea", "genital-ulcers"],
    age: [15, 65],
    vitals: { fever: true },
    comorbidBoost: ["immunocompromised"],
    redFlags: ["Meningism", "Shortness of breath (PCP)", "Focal neurology"],
    workup: ["HIV Ag/Ab plus RNA viral load", "STI panel", "Baseline CD4 once confirmed", "Hepatitis B/C and TB screen"],
    prevention: [
      "Condoms, PrEP for people at ongoing risk",
      "PEP within 72 hours after a high-risk exposure",
      "Never share injecting equipment",
      "Treatment as prevention once virally suppressed",
    ],
    medications: [
      {
        class: "Combination antiretroviral therapy",
        examples: ["Integrase-inhibitor based first-line regimens (clinic-prescribed)"],
        notes: "Start promptly after confirmed infection. Resistance testing and specialist follow-up are required.",
      },
    ],
    selfCare: ["Safer sex while awaiting results", "Partner notification via clinic"],
    seekCare: "Sexual-health or ID clinic this week for fever-rash-pharyngitis after a risk exposure.",
  }),
  defineDisease({
    id: "sti-urethritis",
    name: "Urethritis (gonorrhea / chlamydia)",
    icd10: "N34.1",
    specialty: "urology",
    department: "Sexual health / Urology / Gynecology",
    urgency: "soon",
    setting: "Sexual-health clinic; emergency if suspected PID or epididymo-orchitis with systemic signs",
    summary:
      "Infectious urethritis, usually N. gonorrhoeae or C. trachomatis. Dysuria and discharge; many partners are asymptomatic. Complications include PID, epididymitis, and disseminated gonococcal infection.",
    hallmarks: ["dysuria", "urethral-discharge"],
    supportive: ["frequency", "urgency", "testicular-pain", "pelvic-pain"],
    occasional: ["fever", "joint-pain", "rash", "eye-discharge"],
    age: [14, 55],
    redFlags: ["Pelvic peritonitis", "Testicular torsion mimic", "Septic arthritis", "Eye involvement in a neonate"],
    workup: ["NAAT on urine or swab", "GC culture if resistance a concern", "Syphilis and HIV tests", "Partner treatment"],
    prevention: ["Condoms", "Screening of sexually active people under 25 and those with new partners", "Expedited partner therapy where legal", "Vaccinate against HPV and hepatitis B"],
    medications: [
      {
        class: "Guideline dual or single-agent antimicrobials",
        examples: ["Ceftriaxone IM for gonorrhea", "Doxycycline for chlamydia (azithromycin if pregnant/adherence issue)"],
        notes: "Resistance patterns change — follow current national STI guidance. Treat partners.",
      },
    ],
    selfCare: ["Abstain until both partners treated and symptoms resolve", "Test of cure only when indicated"],
    seekCare: "Sexual-health clinic promptly; emergency if severe pelvic or testicular pain.",
  }),
  defineDisease({
    id: "encephalitis",
    name: "Encephalitis (suspect)",
    icd10: "G04.90",
    specialty: "neurology",
    department: "Emergency / Neurology / Infectious diseases",
    urgency: "emergency",
    setting: "ICU-capable hospital; start acyclovir empirically for HSV while investigating",
    summary:
      "Brain parenchymal inflammation — HSV, autoimmune, or arboviral. Fever, personality change, seizures, and focal signs. Time to acyclovir changes HSV outcome.",
    hallmarks: ["fever", "confusion", "headache", "seizure"],
    supportive: ["photophobia", "neck-stiffness", "speech-difficulty", "weakness-one-side"],
    occasional: ["hallucinations", "double-vision", "rash"],
    vitals: { fever: true, tachy: true },
    comorbidBoost: ["immunocompromised", "cancer"],
    redFlags: ["Status epilepticus", "Coma", "Raised ICP"],
    workup: ["CT then LP if safe", "CSF HSV PCR", "MRI brain", "Autoimmune encephalitis panel in selected cases", "EEG"],
    prevention: ["Mosquito protection in endemic areas", "Vaccines (Japanese encephalitis, rabies) for travelers as indicated", "Prompt treatment of HSV"],
    medications: [
      {
        class: "Empiric antiviral",
        examples: ["IV acyclovir"],
        notes: "Do not wait for PCR if HSV is plausible. Autoimmune encephalitis uses immunotherapy under neurology.",
      },
      {
        class: "Seizure control and supportive ICU care",
        examples: ["Levetiracetam or protocol AED", "Airway protection"],
        notes: "Steroids only in selected autoimmune or vasogenic-edema pathways.",
      },
    ],
    selfCare: ["Not a home illness"],
    seekCare: "Emergency services for fever plus new confusion or seizure.",
  }),
  defineDisease({
    id: "pneumothorax",
    name: "Pneumothorax",
    icd10: "J93.9",
    specialty: "pulmonology",
    department: "Emergency / Thoracic surgery / Pulmonology",
    urgency: "emergency",
    setting: "Emergency department; needle decompression if tension physiology",
    summary:
      "Air in the pleural space collapsing the lung. Sudden pleuritic pain and dyspnea in tall thin young adults (primary) or COPD (secondary). Tension physiology is immediately life-threatening.",
    hallmarks: ["pleuritic-pain", "shortness-of-breath"],
    supportive: ["chest-tightness", "dry-cough"],
    occasional: ["cyanosis", "syncope", "chest-pain"],
    age: [12, 90],
    smokerBoost: true,
    vitals: { tachy: true, hypoxic: true },
    comorbidBoost: ["copd", "asthma"],
    redFlags: ["Tracheal deviation", "Hypotension", "Falling SpO2", "Silent hemithorax"],
    workup: ["Upright chest radiograph", "Point-of-care ultrasound", "CT if occult or complex"],
    prevention: ["Smoking cessation", "Avoid unpressurized high-altitude and scuba after a recent pneumothorax until cleared", "Treat underlying bullous disease"],
    medications: [
      {
        class: "Supportive oxygen and procedural care",
        examples: ["High-flow oxygen (selected primary)", "Aspiration or chest tube", "VATS bleb resection for recurrence"],
        notes: "No specific drug treats the air leak. Analgesia as needed. Tension physiology is a procedure, not a prescription.",
      },
    ],
    selfCare: ["Sit upright, do not fly", "Return immediately if more breathless"],
    seekCare: "Emergency department now for sudden one-sided chest pain and breathlessness.",
  }),
  defineDisease({
    id: "pleural-effusion",
    name: "Pleural effusion",
    icd10: "J90",
    specialty: "pulmonology",
    department: "Pulmonology / Internal medicine",
    urgency: "soon",
    setting: "Outpatient workup if small and stable; hospital if hypoxic or malignant suspicion with distress",
    summary:
      "Fluid in the pleural space from heart failure, infection, PE, or malignancy. Progressive dyspnea, dullness, and sometimes pleuritic pain. Light's criteria separate transudate from exudate.",
    hallmarks: ["shortness-of-breath", "pleuritic-pain", "dry-cough"],
    supportive: ["orthopnea", "fatigue", "edema-legs"],
    occasional: ["fever", "weight-loss", "hemoptysis", "chest-tightness"],
    vitals: { hypoxic: true },
    comorbidBoost: ["heart-disease", "cancer", "kidney-disease"],
    redFlags: ["Rapidly accumulating effusion", "Fever with effusion (empyema)", "Massive effusion with mediastinal shift"],
    workup: ["Chest radiograph/US", "Diagnostic thoracentesis", "Protein, LDH, pH, cytology, culture", "Echo if transudate suspected"],
    prevention: ["Treat heart failure and pneumonia early", "Occupational dust precautions", "Smoking cessation"],
    medications: [
      {
        class: "Treat the cause",
        examples: ["Diuretics for cardiogenic transudate", "Antibiotics for parapneumonic effusion", "Pleurodesis agents in selected malignant effusion"],
        notes: "Empyema needs drainage, not antibiotics alone.",
      },
    ],
    selfCare: ["Sleep propped up", "Report fever or worsening breathlessness"],
    seekCare: "Same-day if new breathlessness with known cancer or fever after pneumonia.",
  }),
  defineDisease({
    id: "pad",
    name: "Peripheral artery disease",
    icd10: "I73.9",
    specialty: "cardiology",
    department: "Vascular surgery / Cardiology",
    urgency: "soon",
    setting: "Vascular clinic; emergency if rest pain, ulcers, or a cold pulseless limb",
    summary:
      "Atherosclerotic stenosis of limb arteries. Intermittent claudication, diminished pulses, and in critical ischemia rest pain or tissue loss. A marker of coronary and carotid disease.",
    hallmarks: ["claudication", "calf-cramps"],
    supportive: ["pale-skin", "numbness", "limited-motion"],
    occasional: ["nonhealing-sore", "pale-skin"],
    age: [45, 100],
    smokerBoost: true,
    comorbidBoost: ["diabetes", "hypertension", "heart-disease"],
    redFlags: ["Sudden cold pulseless limb (embolus)", "Rest pain", "Gangrene"],
    workup: ["ABI", "Arterial duplex", "Lipid/HbA1c/BP", "ECG", "CTA/MRA before revascularization"],
    prevention: ["Smoking cessation is the highest-yield step", "High-intensity statin and antiplatelet as indicated", "Supervised walking program", "Foot care in diabetes"],
    medications: [
      {
        class: "Risk reduction",
        examples: ["High-intensity statin", "Aspirin or clopidogrel", "ACE inhibitor for BP", "Cilostazol for claudication in selected patients"],
        notes: "Cilostazol is contraindicated in heart failure. Acute limb ischemia is surgical/endovascular, not a pill.",
      },
    ],
    selfCare: ["Walk to near-maximal pain then rest, repeat", "Inspect feet daily"],
    seekCare: "Emergency if a limb suddenly becomes painful, pale, and cold.",
  }),
  defineDisease({
    id: "ugib",
    name: "Upper gastrointestinal bleeding",
    icd10: "K92.2",
    specialty: "gastroenterology",
    department: "Emergency / Gastroenterology",
    urgency: "emergency",
    setting: "Resuscitation bay then urgent endoscopy",
    summary:
      "Bleeding proximal to the ligament of Treitz — peptic ulcer, varices, Mallory–Weiss. Hematemesis, coffee-ground emesis, or melena, with risk of hemorrhagic shock.",
    hallmarks: ["vomiting-blood", "coffee-ground", "black-stool"],
    supportive: ["epigastric-pain", "dizziness", "sweating", "fatigue"],
    occasional: ["syncope", "abdominal-pain", "heartburn"],
    vitals: { tachy: true, hypotensive: true },
    comorbidBoost: ["heart-disease", "kidney-disease", "cancer"],
    redFlags: ["Shock", "Ongoing hematemesis", "Known cirrhosis with bleed", "Anticoagulant use"],
    workup: ["CBC, coagulation, type and screen", "Urea often disproportionately high", "Resuscitate then endoscopy", "Glasgow-Blatchford / Rockall"],
    prevention: ["H. pylori test-and-treat", "PPI gastroprotection with dual antiplatelet or high-dose NSAID risk", "Alcohol cessation", "Variceal banding and nonselective beta-blockers in known varices"],
    medications: [
      {
        class: "Acid suppression and hemostasis adjuncts",
        examples: ["High-dose PPI infusion after ulcer hemostasis", "Octreotide and antibiotics in variceal bleed", "Reversal of anticoagulation when appropriate"],
        notes: "Tranexamic acid is not routine. Endoscopy is the disease-modifying step.",
      },
    ],
    selfCare: ["NPO, do not take NSAIDs"],
    seekCare: "Emergency services for vomiting blood or black stools with faintness.",
  }),
  defineDisease({
    id: "cirrhosis-decomp",
    name: "Decompensated cirrhosis",
    icd10: "K74.60",
    specialty: "gastroenterology",
    department: "Hepatology / Emergency",
    urgency: "urgent",
    setting: "Hospital for new ascites, bleed, or encephalopathy",
    summary:
      "Loss of hepatic reserve with ascites, jaundice, variceal bleeding, or hepatic encephalopathy. Triggers include infection, alcohol, and GI bleed.",
    hallmarks: ["jaundice", "bloating", "edema-legs", "fatigue", "confusion"],
    supportive: ["anorexia", "weight-loss", "easy-bleeding", "itch"],
    occasional: ["vomiting-blood", "black-stool", "fever"],
    age: [25, 85],
    comorbidBoost: ["cancer", "kidney-disease"],
    redFlags: ["GI bleed", "Fever in ascites (SBP)", "Grade 3–4 encephalopathy", "AKI"],
    workup: ["LFTs, INR, bilirubin, creatinine (MELD)", "Ultrasound ± Doppler", "Diagnostic paracentesis if new ascites", "Endoscopy for varices"],
    prevention: ["Alcohol cessation", "Hepatitis B vaccination and treatment of viral hepatitis", "Salt restriction and diuretics as directed", "SBP prophylaxis in selected high-risk ascites"],
    medications: [
      {
        class: "Complication-directed therapy",
        examples: ["Spironolactone ± furosemide for ascites", "Lactulose ± rifaximin for encephalopathy", "Nonselective beta-blocker for variceal prophylaxis", "Albumin in SBP/LVP protocols"],
        notes: "NSAIDs and many sedatives are dangerous. Transplant evaluation when MELD or decompensation warrants.",
      },
    ],
    selfCare: ["No alcohol", "Daily weights", "Lactulose to 2–3 soft stools if prescribed"],
    seekCare: "Emergency for vomit-blood, fever with a swollen abdomen, or new confusion.",
  }),
  defineDisease({
    id: "cholangitis",
    name: "Acute cholangitis",
    icd10: "K83.0",
    specialty: "gastroenterology",
    department: "Emergency / GI / Interventional endoscopy",
    urgency: "emergency",
    setting: "Hospital: fluids, antibiotics, and biliary drainage (ERCP)",
    summary:
      "Infection of an obstructed biliary tree (Choledocholithiasis, stricture, stent). Charcot triad: RUQ pain, fever, jaundice. Reynolds pentad adds shock and confusion.",
    hallmarks: ["ruq-pain", "fever", "jaundice", "chills"],
    supportive: ["nausea", "vomiting", "dark-urine", "pale-stool", "malaise"],
    occasional: ["confusion", "dizziness", "itch"],
    vitals: { fever: true, highFever: true, tachy: true, hypotensive: true },
    comorbidBoost: ["cancer", "diabetes"],
    redFlags: ["Shock", "Confusion", "INR rising", "Pus under pressure at ERCP"],
    workup: ["LFTs (obstructive pattern)", "Blood cultures", "CBC, CRP", "US then MRCP/ERCP"],
    prevention: ["Cholecystectomy after gallstone cholangitis when fit", "Stent surveillance", "Hydration during prolonged fasting in stone-formers"],
    medications: [
      {
        class: "Broad-spectrum IV antibiotics plus source control",
        examples: ["Piperacillin-tazobactam or carbapenem per local protocol", "ERCP sphincterotomy and stone extraction"],
        notes: "Antibiotics without drainage fail in complete obstruction.",
      },
    ],
    selfCare: ["NPO"],
    seekCare: "Emergency for fever, yellow eyes, and right-upper pain.",
  }),
  defineDisease({
    id: "mesenteric-ischemia",
    name: "Acute mesenteric ischemia",
    icd10: "K55.0",
    specialty: "emergency",
    department: "Emergency / Vascular / GI surgery",
    urgency: "emergency",
    setting: "Immediate CT angiography and surgical/endovascular reperfusion",
    summary:
      "Gut arterial occlusion or low-flow. Pain out of proportion to exam, often in AF or hypercoagulable patients. Lactate rises late — do not wait for it.",
    hallmarks: ["abdominal-pain", "cannot-get-comfortable", "vomiting"],
    supportive: ["diarrhea", "blood-stool", "nausea", "anorexia"],
    occasional: ["confusion", "syncope"],
    age: [50, 95],
    vitals: { tachy: true, hypotensive: true },
    comorbidBoost: ["heart-disease", "diabetes"],
    redFlags: ["Pain out of proportion", "AF plus sudden abdominal pain", "Peritonitis (infarction)"],
    workup: ["CTA mesenteric", "Lactate, CBC, ABG", "ECG for AF", "Surgical consult before the scan if peritonitic"],
    prevention: ["Anticoagulation in AF as indicated", "Smoking cessation", "Manage atherosclerosis"],
    medications: [
      {
        class: "Resuscitation and anticoagulation / reperfusion",
        examples: ["IV fluids", "Unfractionated heparin unless bleeding", "Endovascular or open embolectomy"],
        notes: "Vasopressors worsen splanchnic flow. Time to reperfusion is the outcome.",
      },
    ],
    selfCare: ["None — this is a time-critical emergency"],
    seekCare: "Emergency services for sudden severe abdominal pain you cannot find a position for.",
  }),
  defineDisease({
    id: "sah",
    name: "Subarachnoid hemorrhage",
    icd10: "I60.9",
    specialty: "neurology",
    department: "Emergency / Neurosurgery",
    urgency: "emergency",
    setting: "Comprehensive stroke / neurosurgical center",
    summary:
      "Arterial bleeding into the subarachnoid space, usually aneurysmal. Thunderclap headache, vomiting, and meningism. A normal CT early still needs LP if suspicion is high.",
    hallmarks: ["worst-headache", "neck-stiffness", "vomiting", "photophobia"],
    supportive: ["loss-of-consciousness", "nausea", "confusion"],
    occasional: ["seizure", "double-vision", "weakness-one-side"],
    vitals: { hypertensive: true },
    redFlags: ["Thunderclap headache", "Sentinel headache days prior", "Coma", "Third-nerve palsy"],
    workup: ["Noncontrast CT immediately", "LP if CT negative and early", "CTA/DSA for aneurysm", "Labs, coagulation"],
    prevention: ["BP control", "Smoking and cocaine cessation", "Family screening in selected heritable aneurysm syndromes"],
    medications: [
      {
        class: "Neurocritical care",
        examples: ["Nimodipine to reduce delayed ischemia", "BP protocol", "Antiepileptics if seizure", "Secure aneurysm (coil/clip)"],
        notes: "Avoid hypotension after securing. Steroids are not standard.",
      },
    ],
    selfCare: ["Do not wait for 'the worst headache of my life' to fade"],
    seekCare: "Emergency services immediately.",
  }),
  defineDisease({
    id: "gbs",
    name: "Guillain–Barré syndrome",
    icd10: "G61.0",
    specialty: "neurology",
    department: "Neurology / ICU",
    urgency: "emergency",
    setting: "Hospital with ICU: monitor FVC and swallow",
    summary:
      "Post-infectious immune attack on peripheral nerves. Ascending areflexic weakness, often after Campylobacter or a viral illness. Respiratory failure can be rapid.",
    hallmarks: ["ascending-weakness", "tingling", "muscle-weakness"],
    supportive: ["back-pain", "bilateral-leg-weakness", "balance-problems"],
    occasional: ["double-vision", "ptosis", "dysphagia", "palpitations"],
    age: [5, 90],
    redFlags: ["Vital-capacity falling", "Bulbar weakness", "Autonomic instability"],
    workup: ["CSF (albuminocytologic dissociation)", "Nerve conduction", "Campylobacter/serology as indicated", "FVC/NIF serial"],
    prevention: ["Food-safety against Campylobacter", "Rare association with certain infections; vaccines' benefit far outweighs GBS risk in most programs"],
    medications: [
      {
        class: "Immunotherapy",
        examples: ["IVIG", "Plasma exchange"],
        notes: "Steroids alone are not effective. Supportive airway care saves lives.",
      },
    ],
    selfCare: ["Do not stay home if legs are getting weaker day by day"],
    seekCare: "Emergency department for ascending weakness, especially if breathless or choking on saliva.",
  }),
  defineDisease({
    id: "myasthenia-crisis",
    name: "Myasthenia gravis (flare / crisis)",
    icd10: "G70.00",
    specialty: "neurology",
    department: "Neurology / ICU",
    urgency: "urgent",
    setting: "Clinic for new fatigable weakness; ICU for crisis",
    summary:
      "Antibody-mediated neuromuscular-junction disease. Fatigable ptosis, diplopia, and proximal weakness. Crisis is respiratory or bulbar failure, often triggered by infection or drugs (aminoglycosides, fluoroquinolones).",
    hallmarks: ["fatigable-weakness", "ptosis", "double-vision"],
    supportive: ["dysphagia", "proximal-weakness", "speech-difficulty"],
    occasional: ["shortness-of-breath", "hoarseness"],
    age: [15, 85],
    sexBias: "female",
    comorbidBoost: ["immunocompromised"],
    redFlags: ["Dyspnea", "Can't swallow saliva", "Vital capacity drop"],
    workup: ["AChR/MuSK antibodies", "Ice-pack / tensilon in selected settings", "CT chest for thymoma", "FVC"],
    prevention: ["Vaccinate, treat infection early", "Medication review (avoid NMJ-blocking drugs)", "Thymectomy when indicated"],
    medications: [
      {
        class: "Acetylcholinesterase inhibitors and immunotherapy",
        examples: ["Pyridostigmine", "Corticosteroids / steroid-sparing agents", "IVIG or PLEX in crisis"],
        notes: "Cholinergic crisis from excess pyridostigmine is a specialist distinction. Never start high-dose steroids unmonitored in bulbar disease.",
      },
    ],
    selfCare: ["Rest before meals, small bites", "Sick-day plan"],
    seekCare: "Emergency if speech, swallow, or breathing worsen.",
  }),
  defineDisease({
    id: "parkinson",
    name: "Parkinson disease",
    icd10: "G20",
    specialty: "neurology",
    department: "Neurology / Movement disorders",
    urgency: "routine",
    setting: "Outpatient neurology",
    summary:
      "Lewy-body synucleinopathy of the substantia nigra. Rest tremor, rigidity, bradykinesia, and postural instability. Non-motor features (constipation, anosmia, REM-sleep behavior) often precede motor signs.",
    hallmarks: ["rest-tremor", "shuffling-gait", "tremor"],
    supportive: ["constipation", "loss-of-smell", "balance-problems", "depressed-mood", "insomnia"],
    occasional: ["memory-loss", "daytime-sleepiness", "depressed-mood"],
    age: [50, 90],
    redFlags: ["Falls from the start (red flag for atypical parkinsonism)", "Rapid dementia", "Early severe dysautonomia"],
    workup: ["Clinical diagnosis", "DaTscan if essential tremor vs PD unclear", "MRI if red flags", "Medication review (drug-induced parkinsonism)"],
    prevention: ["No proven primary prevention; exercise is disease-modifying in function", "Avoid chronic dopamine-blocking antiemetics/antipsychotics when possible"],
    medications: [
      {
        class: "Dopaminergic therapy",
        examples: ["Levodopa-carbidopa", "Dopamine agonists in selected younger patients", "MAO-B inhibitors"],
        notes: "Start low, titrate. Impulse-control disorders with agonists. Specialist titration prevents dyskinesia mismanagement.",
      },
    ],
    selfCare: ["Daily aerobic and resistance exercise", "Fall-proof the home"],
    seekCare: "Neurology referral for new rest tremor or shuffling; emergency for psychosis or inability to swallow tablets.",
  }),
  defineDisease({
    id: "ms-relapse",
    name: "Multiple sclerosis (relapse)",
    icd10: "G35",
    specialty: "neurology",
    department: "Neurology",
    urgency: "soon",
    setting: "Neurology clinic; hospital if disabling or brainstem/spinal",
    summary:
      "Immune-mediated CNS demyelination. A relapse is a new neurologic deficit lasting >24 hours — optic neuritis, internuclear ophthalmoplegia, or partial myelitis.",
    hallmarks: ["numbness", "tingling", "blurred-vision", "electric-spine"],
    supportive: ["fatigue", "balance-problems", "weakness-one-side", "double-vision", "urgency"],
    occasional: ["vertigo", "speech-difficulty", "incontinence"],
    age: [15, 55],
    sexBias: "female",
    redFlags: ["Bilateral severe optic neuritis", "Complete transverse myelitis (NMO spectrum)", "Area postrema intractable vomiting"],
    workup: ["MRI brain/spine with contrast", "CSF oligoclonal bands", "AQP4/MOG if atypical", "Ophthalmology for optic neuritis"],
    prevention: ["Disease-modifying therapy adherence", "Vitamin D repletion as advised", "Smoking cessation", "Treat infection that can mimic relapse (Uhthoff)"],
    medications: [
      {
        class: "Relapse and disease-modifying therapy",
        examples: ["High-dose methylprednisolone for disabling relapses", "Platform or high-efficacy DMTs (interferon, fumarates, S1P, anti-CD20)"],
        notes: "Steroids speed recovery of a relapse; they do not change long-term course. DMT choice is specialist.",
      },
    ],
    selfCare: ["Cooling strategies", "Rest during Uhthoff phenomena"],
    seekCare: "Neurology promptly for a new deficit lasting a day; emergency if both legs weaken or you cannot void.",
  }),
  defineDisease({
    id: "delirium",
    name: "Delirium",
    icd10: "F05",
    specialty: "general-medicine",
    department: "Internal medicine / Geriatrics / Emergency",
    urgency: "urgent",
    setting: "Hospital if new, fluctuating confusion in an older or medically ill adult",
    summary:
      "Acute fluctuating inattention from a medical precipitant (infection, drugs, withdrawal, metabolic). Not dementia — though dementia is the major risk factor. Find and treat the cause.",
    hallmarks: ["fluctuating-confusion", "confusion", "agitation"],
    supportive: ["insomnia", "hallucinations", "restlessness"],
    occasional: ["fever", "low-urine", "dysuria"],
    age: [60, 100],
    comorbidBoost: ["kidney-disease", "heart-disease", "diabetes", "cancer"],
    redFlags: ["Focal neurology (stroke)", "Fever and meningism", "Hypoxia", "Head injury on anticoagulants"],
    workup: ["Confusion Assessment Method", "Glucose, CBC, BMP, UA, CXR", "Medication review", "CT head if trauma/focal/anticoagulant", "ECG"],
    prevention: ["Orientation, glasses/hearing aids, sleep, mobilization (HELP bundle)", "Avoid benzodiazepines in older adults", "Treat constipation, pain, and urinary retention"],
    medications: [
      {
        class: "Treat the cause; antipsychotics only for dangerous agitation",
        examples: ["Low-dose haloperidol or quetiapine in selected cases", "Thiamine if alcohol risk", "Stop deliriogenic drugs"],
        notes: "Benzodiazepines worsen most delirium except alcohol/benzo withdrawal.",
      },
    ],
    selfCare: ["Family at the bedside, daylight, familiar objects"],
    seekCare: "Emergency for sudden confusion in an older adult.",
  }),
  defineDisease({
    id: "alcohol-withdrawal",
    name: "Alcohol withdrawal (including DTs risk)",
    icd10: "F10.239",
    specialty: "psychiatry",
    department: "Emergency / Addiction medicine / ICU if DTs",
    urgency: "urgent",
    setting: "Monitored unit for CIWA-moderate or history of seizures/DTs",
    summary:
      "Autonomic hyperactivity 6–48 h after stopping heavy drinking; seizures and delirium tremens are the feared complications. Tremor, sweating, tachycardia, insomnia, then confusion and hallucinations.",
    hallmarks: ["tremor", "sweating", "anxiety", "insomnia", "agitation"],
    supportive: ["nausea", "vomiting", "palpitations", "headache", "hallucinations"],
    occasional: ["seizure", "confusion", "fever"],
    age: [18, 80],
    vitals: { tachy: true, hypertensive: true },
    redFlags: ["Seizure", "Delirium tremens", "Fever", "GI bleed", "Wernicke triad"],
    workup: ["CIWA-Ar", "Glucose, electrolytes (Mg, Phos)", "LFTs, CBC", "BAL if recently drinking", "ECG"],
    prevention: ["Medically supervised detox if prior seizures/DTs", "Thiamine before glucose", "Treat alcohol-use disorder after the acute phase"],
    medications: [
      {
        class: "Benzodiazepines by symptom-triggered protocol",
        examples: ["Diazepam or lorazepam CIWA-guided", "Phenobarbital in selected protocols", "Thiamine, folate, multivitamin"],
        notes: "Do not undertreat DTs. Outpatient detox is unsafe after withdrawal seizures.",
      },
    ],
    selfCare: ["Do not suddenly stop a heavy daily intake without a plan"],
    seekCare: "Emergency if shaking, sweating, and seeing things after stopping alcohol — or after a withdrawal seizure.",
  }),
  defineDisease({
    id: "cauda-equina",
    name: "Cauda equina syndrome",
    icd10: "G83.4",
    specialty: "orthopedics",
    department: "Emergency / Spine surgery",
    urgency: "emergency",
    setting: "Immediate MRI and surgical decompression",
    summary:
      "Compression of the cauda equina — usually a central disc. Saddle anesthesia, bowel/bladder dysfunction, and often bilateral sciatica. Hours matter for sphincter recovery.",
    hallmarks: ["saddle-numbness", "urinary-retention", "back-pain", "bilateral-leg-weakness"],
    supportive: ["sciatica", "incontinence", "constipation", "numbness"],
    occasional: ["incontinence", "constipation"],
    age: [20, 70],
    redFlags: ["Saddle anesthesia", "Painless urinary retention", "Bilateral sciatica with sphincter change"],
    workup: ["Emergency MRI lumbosacral spine", "Post-void residual", "Surgical consult before delayed imaging if classic"],
    prevention: ["Safe lifting", "Seek care early for progressive neurologic back pain"],
    medications: [
      {
        class: "Surgical decompression is the treatment",
        examples: ["Analgesia while imaging", "Dexamethasone sometimes used perioperatively for cord-level compression (metastasis)"],
        notes: "This is not a 'painkiller and physio' diagnosis.",
      },
    ],
    selfCare: ["None"],
    seekCare: "Emergency department now for back pain with saddle numbness or inability to pass urine.",
  }),
  defineDisease({
    id: "gca",
    name: "Giant cell arteritis",
    icd10: "M31.6",
    specialty: "rheumatology",
    department: "Rheumatology / Ophthalmology / Emergency",
    urgency: "emergency",
    setting: "Start steroids the same day if visual symptoms; temporal-artery biopsy / ultrasound after",
    summary:
      "Large-vessel vasculitis of older adults, often overlapping PMR. New headache, scalp tenderness, jaw claudication, and the feared complication — anterior ischemic optic neuropathy.",
    hallmarks: ["headache", "scalp-tenderness", "jaw-claudication", "fatigue"],
    supportive: ["shoulder-hip-stiffness", "morning-stiffness", "weight-loss", "fever"],
    occasional: ["vision-loss", "double-vision", "toothache"],
    age: [50, 100],
    sexBias: "female",
    vitals: { fever: true },
    redFlags: ["Amaurosis", "Diplopia", "Jaw claudication with visual change"],
    workup: ["ESR/CRP immediately", "CBC", "Temporal-artery ultrasound or biopsy within days of steroids", "Ophthalmology if visual symptoms"],
    prevention: ["No primary prevention; do not delay steroids for a biopsy slot if vision is threatened"],
    medications: [
      {
        class: "High-dose corticosteroids ± steroid-sparing",
        examples: ["Prednisone 40–60 mg daily, or IV methylprednisolone if visual loss", "Tocilizumab in selected relapsing disease", "Bone and PCP prophylaxis as indicated"],
        notes: "Vision loss can be irreversible within hours. Start treatment on clinical suspicion.",
      },
    ],
    selfCare: ["Do not wait for a clinic slot if a temple is tender and vision flickers"],
    seekCare: "Same-day emergency / eye emergency for new headache plus jaw pain on chewing or visual symptoms over age 50.",
  }),
  defineDisease({
    id: "septic-arthritis",
    name: "Septic arthritis",
    icd10: "M00.9",
    specialty: "rheumatology",
    department: "Emergency / Orthopedics / Rheumatology",
    urgency: "emergency",
    setting: "Urgent joint aspiration before antibiotics if the patient is stable",
    summary:
      "Bacterial infection of a native or prosthetic joint. A single hot, swollen, exquisitely painful joint is septic until proven otherwise. Delay destroys cartilage.",
    hallmarks: ["hot-swollen-joint", "joint-pain", "fever", "inability-bear-weight"],
    supportive: ["chills", "malaise", "limited-motion"],
    occasional: ["skin-redness", "wound"],
    vitals: { fever: true, tachy: true },
    comorbidBoost: ["diabetes", "immunocompromised", "cancer"],
    redFlags: ["Prosthetic joint", "Inability to move the joint", "Sepsis"],
    workup: ["Synovial fluid before antibiotics: cell count, Gram stain, culture, crystals", "Blood cultures", "CRP/ESR", "Do not rely on serum WBC"],
    prevention: ["Skin-infection treatment", "Dental and wound care with prostheses", "Glycemic control"],
    medications: [
      {
        class: "IV antibiotics plus surgical washout",
        examples: ["Empiric anti-staph cover per local protocol (vancomycin ± ceftriaxone)", "Directed therapy 2–6 weeks"],
        notes: "Intra-articular steroids are contraindicated until infection is excluded.",
      },
    ],
    selfCare: ["Do not take leftover painkillers and wait"],
    seekCare: "Emergency department for one joint that is red-hot and you cannot walk on.",
  }),
  defineDisease({
    id: "ank-spond",
    name: "Ankylosing spondylitis / axial SpA",
    icd10: "M45.9",
    specialty: "rheumatology",
    department: "Rheumatology",
    urgency: "routine",
    setting: "Rheumatology outpatient",
    summary:
      "Inflammatory axial arthritis of young adults, often HLA-B27. Inflammatory back pain (night pain, morning stiffness, better with activity), uveitis, and in some, dactylitis or psoriasis.",
    hallmarks: ["night-back-pain", "morning-stiffness", "back-pain"],
    supportive: ["fatigue", "dactylitis", "eye-pain", "limited-motion"],
    occasional: ["nail-pitting", "diarrhea", "rash"],
    age: [15, 45],
    sexBias: "male",
    redFlags: ["Acute uveitis", "Cauda-equina-like late disease", "Aortitis rare"],
    workup: ["HLA-B27", "CRP", "MRI SI joints", "X-ray pelvis later", "Ophthalmology if red painful eye"],
    prevention: ["Smoking cessation (radiographic progression)", "Daily stretching and swimming", "NSAIDs used as disease-modifying in axSpA"],
    medications: [
      {
        class: "NSAIDs then biologics",
        examples: ["Naproxen or other NSAID trial", "TNF or IL-17 inhibitors if high disease activity"],
        notes: "Systemic steroids are not the long-term plan. Screen for IBD and uveitis.",
      },
    ],
    selfCare: ["Extension exercises, swimming", "Do not stay in bed"],
    seekCare: "Rheumatology for inflammatory back pain; same-day eye care for a painful red eye.",
  }),
  defineDisease({
    id: "aki",
    name: "Acute kidney injury",
    icd10: "N17.9",
    specialty: "nephrology",
    department: "Nephrology / Emergency / Internal medicine",
    urgency: "urgent",
    setting: "Hospital if oliguric, hyperkalemic, or uremic",
    summary:
      "Abrupt fall in GFR from hypovolemia, ATN, obstruction, or acute GN. Oliguria, rising creatinine, and risk of hyperkalemia and fluid overload.",
    hallmarks: ["low-urine", "fatigue", "nausea", "edema-legs"],
    supportive: ["thirst", "dehydration", "metallic-taste", "confusion"],
    occasional: ["flank-pain", "hematuria", "foamy-urine", "shortness-of-breath"],
    vitals: { tachy: true, hypertensive: true },
    comorbidBoost: ["kidney-disease", "diabetes", "heart-disease"],
    redFlags: ["Anuria", "K+ critically high", "Pulmonary edema", "Uremic pericarditis or seizure"],
    workup: ["BMP, K, bicarbonate", "Urinalysis and FeNa/FeUrea", "Bladder scan / US for obstruction", "CK if rhabdo", "ABG if acidotic"],
    prevention: ["Sick-day rules: pause ACE/ARB/diuretic/NSAID/metformin if volume deplete", "Avoid iodinated contrast when possible", "Hydrate around nephrotoxins"],
    medications: [
      {
        class: "Treat cause; renal replacement if indicated",
        examples: ["Isotonic fluids for prerenal", "Calcium/insulin-glucose/binder for severe hyperkalemia", "Stop nephrotoxins"],
        notes: "AEIOU indications for dialysis. Do not give more potassium-containing ORS blindly.",
      },
    ],
    selfCare: ["Hold NSAIDs", "Maintain oral fluids if drinking"],
    seekCare: "Emergency if you stop passing urine, feel breathless, or have known CKD and vomiting.",
  }),
  defineDisease({
    id: "nephrotic",
    name: "Nephrotic syndrome",
    icd10: "N04.9",
    specialty: "nephrology",
    department: "Nephrology",
    urgency: "soon",
    setting: "Nephrology clinic; hospital if anasarca, thrombosis, or infection",
    summary:
      "Heavy proteinuria, hypoalbuminemia, edema, and often hyperlipidemia. Causes include membranous, MCD, FSGS, and diabetic nephropathy. Thrombotic and infectious risk is high.",
    hallmarks: ["periorbital-edema", "edema-legs", "foamy-urine", "weight-gain"],
    supportive: ["fatigue", "anorexia"],
    occasional: ["calf-swelling", "fever"],
    age: [2, 80],
    comorbidBoost: ["diabetes", "cancer"],
    redFlags: ["Respiratory distress from effusion", "Unilateral leg swelling (clot)", "Spontaneous bacterial peritonitis in children"],
    workup: ["Spot urine protein/creatinine", "Serum albumin, lipids, creatinine", "ANA, complements, PLA2R, hepatitis, HIV, A1c", "Kidney biopsy in most adults"],
    prevention: ["ACE/ARB for proteinuria when appropriate", "Vaccination (encapsulated organisms)", "Salt restriction"],
    medications: [
      {
        class: "Edema, RAAS blockade, immunosuppression for primary causes",
        examples: ["Loop diuretics", "ACE inhibitor or ARB", "Anticoagulation if albumin very low in membranous", "Steroids for MCD"],
        notes: "Cause-specific therapy is nephrologist-directed. NSAIDs can cause minimal-change disease.",
      },
    ],
    selfCare: ["Low-salt diet, daily weights", "Report fever"],
    seekCare: "Prompt nephrology for puffy eyes, foamy urine, and swelling; emergency if breathless.",
  }),
  defineDisease({
    id: "rhabdo",
    name: "Rhabdomyolysis",
    icd10: "M62.82",
    specialty: "nephrology",
    department: "Emergency / Nephrology",
    urgency: "urgent",
    setting: "Hospital fluids until CK falls and urine clears",
    summary:
      "Skeletal-muscle necrosis releasing myoglobin — crush, immobilization, extreme exertion, statins, or drugs. Myalgias, dark urine, and AKI.",
    hallmarks: ["muscle-aches", "dark-urine", "muscle-weakness", "fatigue"],
    supportive: ["dehydration", "nausea", "low-urine"],
    occasional: ["confusion", "fever", "calf-cramps"],
    vitals: { tachy: true },
    comorbidBoost: ["kidney-disease"],
    redFlags: ["Anuria", "Hyperkalemia", "Compartment syndrome"],
    workup: ["CK (often >5× ULN)", "BMP, K, Phos, uric acid, Ca", "Urine dip positive for blood with few RBCs", "ECG"],
    prevention: ["Hydration around extreme exertion and heat", "Medication review (statin + CYP3A4 inhibitor)", "Avoid lying immobilized after intoxication"],
    medications: [
      {
        class: "Volume expansion",
        examples: ["Isotonic saline", "Electrolyte repletion", "RRT if established anuric AKI"],
        notes: "Bicarbonate and mannitol are not routinely superior to saline. Stop the offending drug.",
      },
    ],
    selfCare: ["Oral fluids if mild and still passing urine — still get a CK"],
    seekCare: "Emergency after a fall/lie-down or extreme workout if urine turns cola-colored.",
  }),
  defineDisease({
    id: "addison",
    name: "Adrenal insufficiency (Addison / crisis risk)",
    icd10: "E27.40",
    specialty: "endocrinology",
    department: "Endocrinology / Emergency",
    urgency: "urgent",
    setting: "Emergency if hypotensive; endocrine clinic if chronic",
    summary:
      "Cortisol (± aldosterone) deficiency. Fatigue, weight loss, salt craving, hyperpigmentation in primary disease. Crisis is shock precipitated by infection or missed steroids.",
    hallmarks: ["fatigue", "weight-loss", "salt-craving", "hyperpigmentation", "dizziness"],
    supportive: ["nausea", "anorexia", "abdominal-pain", "low-urine"],
    occasional: ["confusion", "syncope", "fever"],
    vitals: { hypotensive: true, tachy: true },
    comorbidBoost: ["immunocompromised"],
    redFlags: ["Shock", "Fever in a known Addison patient who missed steroids", "Hyponatremia with hyperkalemia"],
    workup: ["8 a.m. cortisol + ACTH", "Cosyntropin stim test", "Electrolytes", "21-hydroxylase antibodies if primary"],
    prevention: ["Sick-day double-dose teaching", "Emergency injectable hydrocortisone kit", "MedicAlert", "Never abruptly stop chronic steroids"],
    medications: [
      {
        class: "Glucocorticoid ± mineralocorticoid replacement",
        examples: ["Hydrocortisone (or prednisolone)", "Fludrocortisone in primary disease", "IV hydrocortisone in crisis"],
        notes: "Do not delay steroids in suspected crisis for a stim test. Thyroid replacement before cortisol can precipitate crisis.",
      },
    ],
    selfCare: ["Never skip steroids", "Extra dose if fever/vomiting — if vomiting, inject and call EMS"],
    seekCare: "Emergency for vomiting plus known adrenal failure, or unexplained shock with pigmentation.",
  }),
  defineDisease({
    id: "preeclampsia",
    name: "Preeclampsia",
    icd10: "O14.90",
    specialty: "gynecology",
    department: "Obstetric emergency / Labor ward",
    urgency: "emergency",
    setting: "Maternity hospital; magnesium and delivery planning",
    summary:
      "New hypertension after 20 weeks with proteinuria or end-organ signs. Headache, visual change, RUQ pain, and edema. Eclampsia is seizure — preventable with magnesium.",
    hallmarks: ["headache", "edema-legs", "blurred-vision", "ruq-pain"],
    supportive: ["nausea", "vomiting", "photophobia", "weight-gain"],
    occasional: ["seizure", "chest-pain", "shortness-of-breath", "confusion"],
    age: [15, 50],
    sexBias: "female",
    pregnancyRisk: true,
    vitals: { hypertensive: true },
    redFlags: ["Seizure", "Severe headache", "RUQ pain", "Pulmonary edema", "HELLP labs"],
    workup: ["BP, urine protein", "CBC, AST/ALT, creatinine, LDH, uric acid", "NST/CTG", "Ultrasound"],
    prevention: ["Low-dose aspirin from 12 weeks in high-risk pregnancy", "Calcium supplementation in low-intake populations", "Treat chronic hypertension before conception"],
    medications: [
      {
        class: "BP control, seizure prophylaxis, timely delivery",
        examples: ["Labetalol, nifedipine, or hydralazine", "Magnesium sulfate", "Antenatal corticosteroids if preterm"],
        notes: "ACE inhibitors are contraindicated in pregnancy. Delivery is the definitive therapy.",
      },
    ],
    selfCare: ["Home BP if prescribed", "Report headache/visual change immediately"],
    seekCare: "Labor ward / emergency now for headache, spots in vision, or RUQ pain in the second half of pregnancy.",
  }),
  defineDisease({
    id: "ovarian-torsion",
    name: "Ovarian torsion",
    icd10: "N83.51",
    specialty: "gynecology",
    department: "Emergency gynecology / Surgery",
    urgency: "emergency",
    setting: "Urgent laparoscopy to salvage the ovary",
    summary:
      "Twisting of the ovary on its pedicle, usually with a cyst or in young patients. Sudden unilateral pelvic pain, nausea, and vomiting. Doppler can be falsely reassuring.",
    hallmarks: ["pelvic-pain", "nausea", "vomiting"],
    supportive: ["abdominal-pain", "sweating"],
    occasional: ["fever", "shoulder-tip-pain"],
    age: [8, 50],
    sexBias: "female",
    redFlags: ["Sudden severe unilateral pelvic pain with vomiting"],
    workup: ["Pregnancy test", "Pelvic US with Doppler", "CBC", "Surgical exploration if high suspicion despite imaging"],
    prevention: ["Follow large cysts as advised", "Prompt evaluation of sudden pelvic pain"],
    medications: [
      {
        class: "Analgesia and operative detorsion",
        examples: ["IV analgesia", "Laparoscopic detorsion ± cystectomy"],
        notes: "Do not delay surgery for 'a period of observation' if classic.",
      },
    ],
    selfCare: ["NPO"],
    seekCare: "Emergency gynecology now.",
  }),
  defineDisease({
    id: "miscarriage",
    name: "Threatened or incomplete miscarriage",
    icd10: "O03.9",
    specialty: "gynecology",
    department: "Early pregnancy unit / Emergency gynae",
    urgency: "urgent",
    setting: "EPAU; emergency if heavy bleeding or shock",
    summary:
      "Pregnancy loss before 20 weeks. Bleeding and cramping with a positive pregnancy test. Ectopic must be excluded. Rh-negative patients need anti-D when indicated.",
    hallmarks: ["vaginal-bleeding", "pelvic-pain", "missed-period"],
    supportive: ["abdominal-pain", "nausea", "fatigue"],
    occasional: ["shoulder-tip-pain", "dizziness", "syncope"],
    age: [14, 50],
    sexBias: "female",
    pregnancyRisk: true,
    redFlags: ["Soaking pads hourly", "Shoulder-tip pain (ectopic)", "Syncope"],
    workup: ["Urine/serum hCG", "Transvaginal US", "CBC, group and hold", "Rhesus status"],
    prevention: ["Folic acid preconception", "Avoid smoking, alcohol, and teratogens", "Treat antiphospholipid syndrome if recurrent"],
    medications: [
      {
        class: "Expectant, medical, or surgical management",
        examples: ["Misoprostol ± mifepristone protocols", "Anti-D immunoglobulin if Rh-negative", "Analgesia"],
        notes: "Ectopic is a different disease — methotrexate only after a confirmed ectopic pathway.",
      },
    ],
    selfCare: ["Pad counts", "Return if soaking or feeling faint"],
    seekCare: "Early pregnancy unit the same day; emergency if soaking or dizzy.",
  }),
  defineDisease({
    id: "endometriosis",
    name: "Endometriosis",
    icd10: "N80.9",
    specialty: "gynecology",
    department: "Gynecology",
    urgency: "routine",
    setting: "Gynecology clinic; emergency only for acute abdomen (ruptured endometrioma rare)",
    summary:
      "Ectopic endometrial-like tissue causing inflammatory pelvic pain. Dysmenorrhea, dyspareunia, and infertility. Laparoscopy is diagnostic and therapeutic but clinical diagnosis is encouraged.",
    hallmarks: ["painful-menses", "pelvic-pain", "painful-intercourse"],
    supportive: ["heavy-menses", "fatigue", "constipation", "dysuria"],
    occasional: ["bloating", "back-pain"],
    age: [15, 50],
    sexBias: "female",
    redFlags: ["Acute abdomen", "Heavy bleeding with anemia"],
    workup: ["Clinical history", "Pelvic exam", "TVUS / MRI for deep disease", "Laparoscopy if treatment-resistant"],
    prevention: ["No proven primary prevention; earlier recognition reduces delay (average years)"],
    medications: [
      {
        class: "Analgesia and hormonal suppression",
        examples: ["NSAIDs", "Combined hormonal contraception or progestins", "GnRH analogues with add-back in refractory disease"],
        notes: "Surgery for failed medical therapy or endometrioma/fertility indications.",
      },
    ],
    selfCare: ["Heat, tracking pain with cycles", "Fertility counseling if desired"],
    seekCare: "Gynecology for cyclical pelvic pain that limits life; emergency for sudden severe pain.",
  }),
  defineDisease({
    id: "pcos",
    name: "Polycystic ovary syndrome",
    icd10: "E28.2",
    specialty: "endocrinology",
    department: "Endocrinology / Gynecology",
    urgency: "routine",
    setting: "Outpatient",
    summary:
      "Androgen excess, ovulatory dysfunction, and/or polycystic ovarian morphology. Hirsutism, irregular menses, acne, and insulin resistance. Rotterdam criteria.",
    hallmarks: ["missed-period", "hirsutism", "weight-gain"],
    supportive: ["hair-loss", "fatigue", "central-weight"],
    occasional: ["pelvic-pain", "depressed-mood", "thirst"],
    age: [14, 45],
    sexBias: "female",
    comorbidBoost: ["diabetes"],
    redFlags: ["Rapid virilization (androgen-secreting tumor)", "Amenorrhea with pregnancy not excluded"],
    workup: ["Pregnancy test", "Total/free testosterone, 17-OHP, TSH, prolactin", "A1c / OGTT", "TVUS if needed for Rotterdam"],
    prevention: ["Weight reduction of 5–10% improves ovulation", "Screen diabetes and lipids", "Endometrial protection if oligomenorrhea"],
    medications: [
      {
        class: "Metabolic and cycle regulation",
        examples: ["Combined oral contraceptive", "Spironolactone for hirsutism (with contraception)", "Metformin in selected insulin-resistant patients", "Letrozole for ovulation induction"],
        notes: "Anti-androgens are teratogenic. Fertility treatment is specialist.",
      },
    ],
    selfCare: ["Resistance and aerobic exercise", "Sleep and weight"],
    seekCare: "Clinic for irregular periods plus hirsutism; urgent if hair and voice change rapidly.",
  }),
  defineDisease({
    id: "colorectal-ca",
    name: "Colorectal cancer (suspect)",
    icd10: "C18.9",
    specialty: "oncology",
    department: "Gastroenterology / Colorectal surgery / Oncology",
    urgency: "soon",
    setting: "Two-week-wait endoscopy pathway",
    summary:
      "Malignancy of the colon or rectum. Change in bowel habit, blood mixed with stool, iron-deficiency anemia, and weight loss. Right-sided tumors may present only with anemia.",
    hallmarks: ["change-bowel", "blood-stool", "weight-loss", "fatigue"],
    supportive: ["anorexia", "abdominal-pain", "tenesmus", "pale-skin"],
    occasional: ["black-stool", "early-satiety", "bloating"],
    age: [40, 90],
    smokerBoost: true,
    comorbidBoost: ["cancer"],
    redFlags: ["Iron-deficiency anemia in a man or postmenopausal woman", "Palpable rectal mass", "Obstruction"],
    workup: ["CBC, ferritin", "FIT in screening contexts", "Colonoscopy", "CT staging / CEA after diagnosis"],
    prevention: [
      "Organized screening (FIT / colonoscopy) from the guideline start age",
      "Do not ignore rectal bleeding",
      "Limit processed meat, don't smoke, stay active",
      "Genetic counseling if Lynch / FAP family history",
    ],
    medications: [
      {
        class: "Stage-directed oncology",
        examples: ["Surgical resection", "FOLFOX/FOLFIRI and biologics per molecular profile", "Immunotherapy for MSI-high"],
        notes: "This workstation flags a referral, it does not stage or prescribe chemo.",
      },
    ],
    selfCare: ["Keep a symptom diary, complete FIT if offered"],
    seekCare: "Urgent cancer pathway for bleeding plus change in bowel habit or unexplained anemia.",
  }),
  defineDisease({
    id: "lung-ca",
    name: "Lung cancer (suspect)",
    icd10: "C34.90",
    specialty: "oncology",
    department: "Pulmonology / Thoracic oncology",
    urgency: "soon",
    setting: "Rapid-access lung clinic",
    summary:
      "Primary lung malignancy, mostly smoking-related. Persistent cough, hemoptysis, weight loss, and chest pain. Small-cell may present with SIADH or paraneoplastic neurology.",
    hallmarks: ["cough", "hemoptysis", "weight-loss", "fatigue"],
    supportive: ["shortness-of-breath", "chest-pain", "anorexia", "hoarseness"],
    occasional: ["bone-pain", "headache", "night-sweats"],
    age: [40, 90],
    smokerBoost: true,
    comorbidBoost: ["copd", "cancer"],
    redFlags: ["Hemoptysis in a smoker", "SVC obstruction", "New Horner syndrome", "Spinal cord compression"],
    workup: ["Chest radiograph then CT", "Biopsy (bronch, EBUS, CT-guided)", "PET-CT staging", "Molecular markers"],
    prevention: ["Smoking cessation", "LDCT screening for eligible heavy smokers", "Radon and occupational dust control"],
    medications: [
      {
        class: "Stage and histology directed",
        examples: ["Surgery or SABR in early NSCLC", "TKIs for EGFR/ALK/ROS1", "Checkpoint inhibitors", "Platinum doublets"],
        notes: "Hemoptysis plus a smoking history is a same-week CXR, not watchful waiting.",
      },
    ],
    selfCare: ["Stop smoking even after diagnosis — it improves outcomes"],
    seekCare: "Urgent CXR pathway for cough >3 weeks in a smoker, or any hemoptysis.",
  }),
  defineDisease({
    id: "melanoma-suspect",
    name: "Melanoma (suspect lesion)",
    icd10: "C43.9",
    specialty: "dermatology",
    department: "Dermatology / Skin cancer clinic",
    urgency: "soon",
    setting: "Two-week-wait dermatology; emergency only if bleeding mass with systemic disease",
    summary:
      "Malignant melanocyte tumor. ABCDE: asymmetry, border, color, diameter, evolution. Nodular melanoma may grow quickly without the classic radial pattern.",
    hallmarks: ["mole-change"],
    supportive: ["itch", "nonhealing-sore"],
    occasional: ["weight-loss", "swollen-lymph"],
    age: [15, 90],
    smokerBoost: false,
    redFlags: ["Ugly duckling mole", "Bleeding or ulcerated pigmented lesion", "Regional nodes"],
    workup: ["Dermoscopy", "Complete excision biopsy with margins per guideline (not a shave if melanoma likely)", "SLNB / staging if confirmed"],
    prevention: ["Sun protection, no tanning beds", "Skin self-exam monthly", "Especially important after blistering childhood burns"],
    medications: [
      {
        class: "Surgical then adjuvant/systemic as staged",
        examples: ["Wide local excision", "PD-1 inhibitors", "BRAF/MEK inhibitors if BRAF-mutant"],
        notes: "Do not apply 'wart remover' to a changing mole.",
      },
    ],
    selfCare: ["Photograph moles for change", "SPF, hats, shade"],
    seekCare: "Urgent skin-cancer clinic for a changing or ugly-duckling mole.",
  }),
  defineDisease({
    id: "breast-ca",
    name: "Breast cancer (suspect)",
    icd10: "C50.919",
    specialty: "oncology",
    department: "Breast clinic",
    urgency: "soon",
    setting: "Two-week-wait triple assessment",
    summary:
      "Most common cancer in women. A painless hard irregular lump, nipple inversion, peau d'orange, or bloody nipple discharge. Men can be affected. Screening does not replace a new lump workup.",
    hallmarks: ["breast-lump"],
    supportive: ["weight-loss", "fatigue", "swollen-lymph"],
    occasional: ["bone-pain", "skin-redness"],
    age: [20, 95],
    sexBias: "female",
    redFlags: ["Hard fixed lump", "Inflammatory breast (red, swollen, peau d'orange)", "Axillary nodes"],
    workup: ["Triple assessment: exam, mammogram/US, core biopsy", "Receptor and HER2 testing", "Staging as indicated"],
    prevention: ["Organized mammographic screening", "Alcohol moderation, healthy weight, exercise", "Genetic counseling if strong family history", "Do not ignore a lump because a mammogram last year was normal"],
    medications: [
      {
        class: "Multimodality oncology",
        examples: ["Surgery ± radiation", "Endocrine therapy for ER+", "HER2-targeted therapy", "Chemotherapy as indicated"],
        notes: "A lump needs triple assessment, not antibiotics for 'mastitis' unless classic lactational infection.",
      },
    ],
    selfCare: ["Breast awareness, not ritual self-exam anxiety"],
    seekCare: "Breast clinic urgently for a new lump, skin change, or bloody nipple discharge.",
  }),
  defineDisease({
    id: "peritonsillar-abscess",
    name: "Peritonsillar abscess (quinsy)",
    icd10: "J36",
    specialty: "otolaryngology",
    department: "ENT emergency",
    urgency: "urgent",
    setting: "ENT: drainage plus antibiotics; airway watch",
    summary:
      "Collection beside the tonsil after pharyngitis. Hot-potato voice, trismus, uvula deviation, and unilateral swelling. Airway compromise is the emergency.",
    hallmarks: ["sore-throat", "muffled-voice", "fever", "odynophagia"],
    supportive: ["ear-pain", "swollen-lymph", "drooling"],
    occasional: ["stridor", "dehydration"],
    age: [8, 45],
    vitals: { fever: true, tachy: true },
    redFlags: ["Stridor", "Drooling", "Trismus with dehydration"],
    workup: ["Clinical ENT exam", "Needle aspiration / incision", "CT if deep-neck suspicion"],
    prevention: ["Complete streptococcal treatment", "Tonsillectomy after recurrent quinsy as advised"],
    medications: [
      {
        class: "Drainage plus antibiotics and steroids",
        examples: ["Aspiration/I&D", "IV penicillin plus metronidazole or amoxicillin-clavulanate", "Dexamethasone for swelling"],
        notes: "Antibiotics without drainage fail. Airway first.",
      },
    ],
    selfCare: ["Fluids if you can swallow"],
    seekCare: "Emergency / ENT for muffled voice and inability to open the mouth with a severe sore throat.",
  }),
  defineDisease({
    id: "epiglottitis",
    name: "Epiglottitis",
    icd10: "J05.10",
    specialty: "otolaryngology",
    department: "Emergency / ENT / Anesthesiology",
    urgency: "emergency",
    setting: "Keep the patient calm; airway team; do not inspect the throat aggressively",
    summary:
      "Infection of the epiglottis with rapid airway obstruction. Drooling, tripoding, stridor, and muffled voice. Hib vaccine made it rarer in children but adult cases persist.",
    hallmarks: ["drooling", "stridor", "muffled-voice", "sore-throat"],
    supportive: ["fever", "odynophagia", "anxiety"],
    occasional: ["shortness-of-breath", "cyanosis"],
    age: [2, 80],
    vitals: { fever: true, tachy: true, hypoxic: true },
    redFlags: ["Stridor at rest", "Tripod position", "Cyanosis"],
    workup: ["Do not send for a remote x-ray unaccompanied", "Lateral neck film only if stable", "Secure airway in theatre", "Blood cultures"],
    prevention: ["Hib vaccination", "Pneumococcal vaccination"],
    medications: [
      {
        class: "Airway, then IV antibiotics",
        examples: ["Third-generation cephalosporin ± vancomycin per protocol", "Corticosteroids often used as adjunct"],
        notes: "The airway is the medicine. Tongue depressors in unstable children can precipitate obstruction.",
      },
    ],
    selfCare: ["Sit forward, do not lie flat, do not inspect the throat at home"],
    seekCare: "Emergency services now for drooling and noisy breathing with a sore throat.",
  }),
  defineDisease({
    id: "conjunctivitis",
    name: "Acute conjunctivitis",
    icd10: "H10.9",
    specialty: "ophthalmology",
    department: "Primary care / Ophthalmology if red flags",
    urgency: "self-care",
    setting: "Home if viral/allergic without pain or vision loss; same-day eye if uncertain",
    summary:
      "Inflammation of the conjunctiva — viral, bacterial, or allergic. Red eye with discharge and normal visual acuity. Pain, photophobia, or vision change is not 'pink eye'.",
    hallmarks: ["red-eyes", "eye-discharge", "itch"],
    supportive: ["runny-nose", "sore-throat", "sneezing"],
    occasional: ["photophobia", "swollen-lymph"],
    redFlags: ["True eye pain", "Photophobia with vision drop (keratitis/uveitis)", "Contact-lens wearer with red eye", "Newborn"],
    workup: ["Visual acuity", "Fluorescein if pain/photophobia", "GC/chlamydia swabs in sexually active with hyperacute discharge"],
    prevention: ["Hand hygiene, don't share towels", "Replace eye makeup after infection", "Contact-lens hygiene"],
    medications: [
      {
        class: "Supportive; topical antibiotic only if bacterial likely",
        examples: ["Preservative-free lubricants", "Topical antihistamine for allergic", "Chloramphenicol or other topical Abx if bacterial"],
        notes: "Steroid drops only under ophthalmology. Contact-lens red eye needs specialist review for keratitis.",
      },
    ],
    selfCare: ["Cool compresses, hygiene, discard contacts"],
    seekCare: "Same-day eye clinic if pain, light hurts, vision drops, or you wear contact lenses.",
  }),
  defineDisease({
    id: "meniere",
    name: "Ménière disease",
    icd10: "H81.0",
    specialty: "otolaryngology",
    department: "ENT / Audiology",
    urgency: "soon",
    setting: "ENT outpatient; emergency if first thunderclap vertigo with neuro signs (stroke)",
    summary:
      "Endolymphatic hydrops. Episodic vertigo (20 min–hours) with fluctuating hearing loss, tinnitus, and aural fullness, usually unilateral.",
    hallmarks: ["vertigo", "tinnitus", "hearing-loss", "ear-fullness"],
    supportive: ["nausea", "vomiting", "balance-problems"],
    occasional: ["headache"],
    age: [20, 70],
    redFlags: ["Continuous vertigo with neurologic signs (stroke/vestibular neuritis overlap)", "Sudden complete deafness"],
    workup: ["Audiogram", "Exclude vestibular migraine and TIA", "MRI if asymmetric SNHL to rule out vestibular schwannoma"],
    prevention: ["Low-salt diet", "Limit caffeine and alcohol", "Stress and sleep hygiene", "Avoid ototoxic drugs"],
    medications: [
      {
        class: "Acute vestibular suppressants then preventive",
        examples: ["Short-course prochlorperazine or antihistamine for attacks", "Betahistine in some regions", "Intratympanic steroid or gentamicin for refractory disease"],
        notes: "Chronic vestibular suppressants delay compensation. Diuretics are sometimes used.",
      },
    ],
    selfCare: ["Sit/lie during attacks, low salt"],
    seekCare: "ENT for recurrent spinning with hearing change; emergency if sudden weakness or dysarthria with vertigo.",
  }),
  defineDisease({
    id: "scabies",
    name: "Scabies",
    icd10: "B86",
    specialty: "dermatology",
    department: "Dermatology / Primary care",
    urgency: "soon",
    setting: "Home treatment of the whole household",
    summary:
      "Sarcoptes scabiei infestation. Intense itch worse at night, burrows in web spaces and wrists, genital nodules. Crusted scabies in immunocompromised is highly infectious.",
    hallmarks: ["itch", "night-itch", "rash"],
    supportive: ["blisters"],
    occasional: ["skin-redness"],
    redFlags: ["Crusted (Norwegian) scabies", "Secondary bacterial infection / post-strep GN"],
    workup: ["Clinical; mineral-oil scraping", "Dermoscopy (delta wing)"],
    prevention: ["Treat all close contacts the same day", "Wash linen on hot / bag for 3 days", "Avoid sharing bedding"],
    medications: [
      {
        class: "Scabicides",
        examples: ["Permethrin 5% cream neck-down overnight, repeat day 8", "Oral ivermectin in crusted or institutional outbreaks"],
        notes: "Itch can last 2–4 weeks after mites die — that is not always treatment failure. Treat the environment and contacts.",
      },
    ],
    selfCare: ["Trim nails, hot wash, treat contacts even if asymptomatic"],
    seekCare: "Clinic if itch persists after two correctly timed treatments or if crusted.",
  }),
  defineDisease({
    id: "bipolar",
    name: "Bipolar disorder (manic / hypomanic episode)",
    icd10: "F31.9",
    specialty: "psychiatry",
    department: "Psychiatry / Crisis team",
    urgency: "urgent",
    setting: "Crisis team or hospital if risk, psychosis, or no sleep",
    summary:
      "Episodes of mania or hypomania often alternating with depression. Decreased need for sleep, grandiosity, racing thoughts, and risky behavior. Suicide risk is high in mixed and depressed poles.",
    hallmarks: ["mania", "insomnia", "irritability"],
    supportive: ["agitation", "restlessness", "speech-difficulty"],
    occasional: ["hallucinations", "depressed-mood", "suicidal-thoughts"],
    age: [15, 60],
    redFlags: ["Suicidal intent", "Psychosis", "No sleep for days", "Reckless spending/driving"],
    workup: ["Clinical diagnostic interview", "Urine tox", "TSH", "Pregnancy test", "Rule out steroids, stimulants"],
    prevention: ["Sleep regularity", "Medication adherence", "Substance avoidance", "Early warning-sign plan with family"],
    medications: [
      {
        class: "Mood stabilizers and antipsychotics",
        examples: ["Lithium", "Valproate (not in pregnancy)", "Quetiapine, olanzapine, aripiprazole", "Lamotrigine more for bipolar depression"],
        notes: "Antidepressant monotherapy can switch to mania. Lithium needs levels, renal and thyroid monitoring.",
      },
    ],
    selfCare: ["Protect sleep, delay big decisions", "Involve a trusted person"],
    seekCare: "Crisis services if not sleeping and racing; emergency / 988 if suicidal.",
  }),
  defineDisease({
    id: "ptsd",
    name: "Post-traumatic stress disorder",
    icd10: "F43.10",
    specialty: "psychiatry",
    department: "Psychiatry / Trauma-focused therapy services",
    urgency: "soon",
    setting: "Outpatient trauma therapy; emergency if acute risk",
    summary:
      "Intrusion, avoidance, negative mood/cognition, and hyperarousal after a qualifying trauma, lasting >1 month. Nightmares, flashbacks, and startle.",
    hallmarks: ["flashbacks", "insomnia", "anxiety", "irritability"],
    supportive: ["anhedonia", "depressed-mood", "panic"],
    occasional: ["suicidal-thoughts", "palpitations"],
    age: [12, 90],
    redFlags: ["Active suicidal plan", "Dissociative fugue", "Substance crisis"],
    workup: ["PCL-5 / clinical interview", "Screen depression, substance use, TBI if blast/assault"],
    prevention: ["Early practical support after trauma (not forced debriefing)", "Treat acute stress and sleep", "Reduce secondary trauma exposure"],
    medications: [
      {
        class: "Trauma-focused psychotherapy first-line; SSRI/SNRI as indicated",
        examples: ["Prolonged exposure, CPT, EMDR", "Sertraline or venlafaxine", "Prazosin sometimes for nightmares"],
        notes: "Benzodiazepines are not a PTSD treatment. Therapy is the core.",
      },
    ],
    selfCare: ["Grounding, regular sleep, limit alcohol", "Peer support if wanted"],
    seekCare: "Mental-health services; crisis line if unsafe.",
  }),
  defineDisease({
    id: "postpartum-depression",
    name: "Postpartum depression",
    icd10: "F53.0",
    specialty: "psychiatry",
    department: "Perinatal psychiatry / Primary care",
    urgency: "soon",
    setting: "Outpatient perinatal MH; emergency if psychosis or infanticidal thoughts",
    summary:
      "Major depression with onset in pregnancy or the first year postpartum. Beyond 'baby blues'. Bonding trouble, insomnia not explained by the infant, and anhedonia. Postpartum psychosis is a different emergency.",
    hallmarks: ["postpartum-mood", "depressed-mood", "anhedonia", "insomnia"],
    supportive: ["anxiety", "fatigue", "anorexia", "irritability"],
    occasional: ["suicidal-thoughts", "hallucinations", "panic"],
    age: [15, 50],
    sexBias: "female",
    pregnancyRisk: true,
    redFlags: ["Thoughts of harming the baby", "Psychosis", "Suicidal plan"],
    workup: ["EPDS screen", "TSH, CBC, B12", "Risk assessment", "Differentiate blues vs psychosis"],
    prevention: ["Screen in pregnancy and postpartum", "Sleep support, partner/family help", "Treat antenatal depression"],
    medications: [
      {
        class: "SSRI and psychotherapy; lactation-informed choices",
        examples: ["Sertraline commonly used in lactation", "CBT / IPT", "Brexanolone / zuranolone in selected severe PPD"],
        notes: "Untreated depression harms parent and infant more than most compatible antidepressants. Psychosis needs emergency psychiatry.",
      },
    ],
    selfCare: ["Ask for overnight help", "Do not stay alone if thoughts of harm"],
    seekCare: "Same-day perinatal mental health if not coping; emergency / 988 if thoughts of death or harming the infant.",
  }),
];
