import { defineDisease } from "../define";

export const INFECTIOUS = [
  defineDisease({
    id: "viral-uri",
    name: "Viral upper respiratory infection (common cold)",
    icd10: "J06.9",
    specialty: "infectious-disease",
    department: "Primary care / Family medicine",
    urgency: "self-care",
    setting: "Home with return precautions; clinic if >10 days or worsening",
    summary:
      "Self-limited rhinovirus or similar infection of the nasopharynx. Congestion, sore throat, and cough without hypoxia, high fever, or focal chest findings.",
    hallmarks: ["runny-nose", "nasal-congestion", "sneezing", "sore-throat"],
    supportive: ["cough", "fatigue", "headache", "malaise"],
    occasional: ["fever", "ear-pain", "hoarseness", "loss-of-smell"],
    vitals: {},
    redFlags: ["Shortness of breath", "Oxygen saturation below 94%", "Neck stiffness with fever", "Stridor"],
    workup: ["Clinical diagnosis", "Testing only if influenza/COVID would change management", "Consider sinus or chest imaging if prolonged or focal"],
    prevention: [
      "Hand hygiene and not touching the face",
      "Stay home while febrile and highly symptomatic",
      "Seasonal influenza and COVID-19 vaccination",
      "Avoid close contact with immunocompromised household members while ill",
    ],
    medications: [
      {
        class: "Supportive analgesics / antipyretics",
        examples: ["Acetaminophen", "Ibuprofen"],
        notes: "Symptom control. Avoid aspirin in children and adolescents (Reye syndrome).",
      },
      {
        class: "Intranasal saline or ipratropium",
        examples: ["Isotonic saline rinses", "Ipratropium nasal spray"],
        notes: "May reduce rhinorrhea. Oral decongestants are cautioned in hypertension.",
      },
    ],
    selfCare: ["Rest, fluids, humidifier", "Honey for cough in adults and children over 1 year", "Return if symptoms persist beyond 10 days or a second fever spike occurs"],
    seekCare: "Clinic if symptoms last more than 10 days, high fever, ear pain, wheeze, or in infants, pregnancy, or immunocompromise.",
  }),
  defineDisease({
    id: "influenza",
    name: "Influenza",
    icd10: "J11.1",
    specialty: "infectious-disease",
    department: "Primary care / Infectious diseases",
    urgency: "soon",
    setting: "Outpatient if stable; emergency department if hypoxic, hypotensive, or pregnant with severe disease",
    summary:
      "Acute influenza virus infection with abrupt fever, myalgias, dry cough, and profound fatigue. Highest risk of pneumonia and decompensation in older adults, pregnancy, and chronic cardiopulmonary disease.",
    hallmarks: ["fever", "chills", "muscle-aches", "fatigue", "dry-cough", "headache"],
    supportive: ["sore-throat", "runny-nose", "malaise", "sweating"],
    occasional: ["shortness-of-breath", "vomiting", "diarrhea", "chest-pain"],
    vitals: { fever: true, highFever: true, tachy: true },
    comorbidBoost: ["asthma", "copd", "heart-disease", "diabetes", "immunocompromised", "pregnancy"],
    redFlags: ["Dyspnea or hypoxia", "Chest pain", "Confusion", "Pregnancy with high fever", "Inability to keep fluids down"],
    workup: ["Influenza NAAT or antigen", "Pulse oximetry", "Chest radiograph if pneumonia suspected", "CBC/CMP in high-risk patients"],
    prevention: [
      "Annual influenza vaccination for everyone 6 months and older",
      "Early antiviral therapy in high-risk groups",
      "Mask and isolation while febrile",
      "Hand hygiene during influenza season",
    ],
    medications: [
      {
        class: "Neuraminidase inhibitors",
        examples: ["Oseltamivir", "Zanamivir", "Peramivir"],
        notes: "Most useful within 48 hours of onset, and later in hospitalized or high-risk patients. Clinician-prescribed.",
      },
      {
        class: "Cap-dependent endonuclease inhibitor",
        examples: ["Baloxavir marboxil"],
        notes: "Single-dose option in selected outpatients; avoid in pregnancy unless advised by a specialist.",
      },
      {
        class: "Supportive care",
        examples: ["Acetaminophen", "Oral hydration"],
        notes: "Do not use aspirin in children.",
      },
    ],
    selfCare: ["Isolation until 24 hours after fever resolves", "Fluids and rest", "Monitor oxygen if chronic lung disease"],
    seekCare: "Same-day care if high-risk, pregnant, breathless, or not improving after 3 days.",
  }),
  defineDisease({
    id: "covid-19",
    name: "COVID-19",
    icd10: "U07.1",
    specialty: "infectious-disease",
    department: "Primary care / Infectious diseases / Pulmonology",
    urgency: "soon",
    setting: "Home isolation if stable; ED for hypoxia, chest pain, or confusion",
    summary:
      "SARS-CoV-2 infection ranging from mild URI to viral pneumonia. Anosmia, dry cough, fever, and exertional dyspnea are typical. Risk of severe disease rises with age, obesity, and comorbidity.",
    hallmarks: ["fever", "dry-cough", "fatigue", "loss-of-smell", "malaise"],
    supportive: ["sore-throat", "headache", "muscle-aches", "shortness-of-breath", "runny-nose", "chills"],
    occasional: ["diarrhea", "nausea", "chest-tightness", "night-sweats"],
    vitals: { fever: true, tachy: true, hypoxic: true },
    comorbidBoost: ["diabetes", "hypertension", "heart-disease", "asthma", "copd", "immunocompromised", "cancer"],
    redFlags: ["SpO2 ≤94% or falling", "Severe dyspnea", "Chest pain", "Confusion", "Blue lips"],
    workup: ["SARS-CoV-2 NAAT or antigen", "Pulse oximetry including ambulation", "Chest imaging if pneumonia suspected", "D-dimer/inflammatory markers in hospital settings"],
    prevention: [
      "Stay current with recommended COVID-19 vaccination",
      "Ventilation, masking in high-risk settings",
      "Early therapeutics for eligible high-risk outpatients",
      "Isolate per public-health guidance while infectious",
    ],
    medications: [
      {
        class: "Oral antiviral (high-risk outpatients)",
        examples: ["Nirmatrelvir-ritonavir", "Molnupiravir (selected cases)"],
        notes: "Start promptly after a positive test in eligible patients. Ritonavir has major drug–drug interactions — pharmacist review required.",
      },
      {
        class: "Supportive and hospital therapies",
        examples: ["Dexamethasone if oxygen-requiring", "Remdesivir", "Oxygen"],
        notes: "Steroids are not used in non-hypoxic outpatients.",
      },
    ],
    selfCare: ["Rest, fluids, pulse-ox monitoring if available", "Acetaminophen for fever", "Return precautions for dyspnea"],
    seekCare: "Urgent evaluation for falling oxygen, chest pain, confusion, or inability to drink.",
  }),
  defineDisease({
    id: "community-acquired-pneumonia",
    name: "Community-acquired pneumonia",
    icd10: "J18.9",
    specialty: "pulmonology",
    department: "Internal medicine / Pulmonology / Emergency",
    urgency: "urgent",
    setting: "ED or hospital if CURB-65/PSI high, hypoxic, or elderly; otherwise close outpatient follow-up",
    summary:
      "Acute infection of the pulmonary parenchyma. Fever, productive cough, pleuritic pain, and dyspnea with focal crackles or infiltrate. Can decompensate rapidly in older adults.",
    hallmarks: ["fever", "productive-cough", "shortness-of-breath", "pleuritic-pain", "chills"],
    supportive: ["fatigue", "malaise", "chest-pain", "sweating", "anorexia"],
    occasional: ["hemoptysis", "confusion", "nausea", "muscle-aches"],
    vitals: { fever: true, tachy: true, hypoxic: true },
    comorbidBoost: ["copd", "asthma", "heart-disease", "diabetes", "immunocompromised"],
    smokerBoost: true,
    redFlags: ["Hypoxia", "Hypotension", "Confusion", "Respiratory rate ≥30", "Hemoptysis"],
    workup: [
      "Chest radiograph (or CT if discordant)",
      "Pulse oximetry and arterial blood gas if severe",
      "CBC, CMP, CRP or procalcitonin",
      "Blood cultures and sputum if hospitalized",
      "Legionella/pneumococcal urine antigen when indicated",
    ],
    prevention: [
      "Pneumococcal vaccination per ACIP schedule",
      "Annual influenza vaccine",
      "Smoking cessation",
      "Oral care in older adults and aspiration-risk patients",
    ],
    medications: [
      {
        class: "Empiric antibiotics (severity- and resistance-guided)",
        examples: ["Amoxicillin", "Amoxicillin-clavulanate", "Doxycycline", "Azithromycin", "Ceftriaxone plus macrolide"],
        notes: "Choice depends on comorbidities, local resistance, and whether the patient is inpatient. Never self-start leftover antibiotics.",
      },
      {
        class: "Supportive",
        examples: ["Oxygen", "Antipyretics", "IV fluids if dehydrated"],
        notes: "Early mobility and VTE prophylaxis when hospitalized.",
      },
    ],
    selfCare: ["Do not delay care if breathless", "Complete the prescribed antibiotic course", "Follow-up radiograph in selected patients"],
    seekCare: "Emergency department for hypoxia, confusion, chest pain, or inability to take oral fluids.",
  }),
  defineDisease({
    id: "acute-bronchitis",
    name: "Acute bronchitis",
    icd10: "J20.9",
    specialty: "pulmonology",
    department: "Primary care",
    urgency: "routine",
    setting: "Primary care; antibiotics are usually not indicated",
    summary:
      "Self-limited inflammation of the bronchi, nearly always viral. Cough lasts 1–3 weeks, often productive, without infiltrate or hypoxia.",
    hallmarks: ["cough", "productive-cough", "sore-chest-cough"],
    supportive: ["fatigue", "malaise", "runny-nose", "wheezing"],
    occasional: ["fever", "shortness-of-breath", "chest-tightness"],
    redFlags: ["Focal crackles with fever (consider pneumonia)", "Hemoptysis", "Hypoxia"],
    workup: ["Clinical", "Chest radiograph if pneumonia cannot be excluded", "Peak flow if asthma history"],
    prevention: ["Influenza vaccination", "Avoid smoke and irritants", "Hand hygiene"],
    medications: [
      {
        class: "Supportive antitussives / inhaled bronchodilator if wheeze",
        examples: ["Honey", "Dextromethorphan (selected adults)", "Albuterol if airflow obstruction"],
        notes: "Antibiotics do not shorten viral bronchitis and drive resistance.",
      },
    ],
    selfCare: ["Humidified air, fluids", "Expect cough for up to 3 weeks", "Stop smoking"],
    seekCare: "If fever persists, dyspnea, or cough beyond 3 weeks.",
  }),
  defineDisease({
    id: "acute-sinusitis",
    name: "Acute rhinosinusitis",
    icd10: "J01.90",
    specialty: "otolaryngology",
    department: "Primary care / Otolaryngology",
    urgency: "soon",
    setting: "Primary care; ENT if recurrent, complicated, or immunocompromised",
    summary:
      "Inflammation of the paranasal sinuses. Most episodes are viral. Bacterial disease is considered when symptoms last ≥10 days, or a double-worsening pattern occurs.",
    hallmarks: ["sinus-pressure", "nasal-congestion", "runny-nose", "headache"],
    supportive: ["fever", "cough", "fatigue", "toothache", "loss-of-smell"],
    occasional: ["ear-pain", "sore-throat", "chills"],
    vitals: { fever: true },
    redFlags: ["Periorbital swelling", "Diplopia", "Severe headache with photophobia", "Altered mentation", "Immunocompromise with high fever"],
    workup: ["Clinical diagnosis", "Imaging only for complications or protracted disease", "Nasal endoscopy in ENT clinic if recurrent"],
    prevention: ["Treat allergic rhinitis", "Nasal saline", "Avoid unnecessary antibiotics", "Intranasal corticosteroids for recurrent disease"],
    medications: [
      {
        class: "Intranasal corticosteroid",
        examples: ["Fluticasone", "Mometasone", "Budesonide"],
        notes: "First-line symptom therapy for many patients.",
      },
      {
        class: "First-line antibiotic when bacterial criteria met",
        examples: ["Amoxicillin-clavulanate", "Doxycycline if penicillin-allergic"],
        notes: "Watchful waiting is appropriate in many uncomplicated adults.",
      },
    ],
    selfCare: ["Saline irrigations", "Steam, rest, analgesia", "Intranasal steroid"],
    seekCare: "Urgent care for orbital signs, severe headache, or high fever after 3 days of therapy.",
  }),
  defineDisease({
    id: "strep-pharyngitis",
    name: "Streptococcal pharyngitis",
    icd10: "J02.0",
    specialty: "infectious-disease",
    department: "Primary care / Pediatrics / ENT",
    urgency: "soon",
    setting: "Clinic or urgent care for testing and directed therapy",
    summary:
      "Group A Streptococcus infection of the pharynx. Sudden sore throat, fever, tender cervical nodes, and tonsillar exudate without prominent cough. Treat to reduce suppurative complications and rheumatic fever in at-risk groups.",
    hallmarks: ["sore-throat", "fever", "swollen-lymph", "chills"],
    supportive: ["headache", "malaise", "anorexia"],
    occasional: ["abdominal-pain", "rash", "nausea"],
    age: [3, 45],
    vitals: { fever: true },
    redFlags: ["Drooling or stridor (epiglottitis/abscess)", "Trismus", "Unilateral tonsillar bulge", "Rash of scarlet fever with toxicity"],
    workup: ["Centor/McIsaac score", "RADT and/or throat culture", "Consider EBV testing if atypical"],
    prevention: ["Avoid sharing utensils during illness", "Treat confirmed GAS", "Household evaluation if recurrent"],
    medications: [
      {
        class: "Beta-lactam antibiotic",
        examples: ["Penicillin V", "Amoxicillin", "Benzathine penicillin G"],
        notes: "First-line when GAS is confirmed or highly likely. Cephalexin or macrolide if true penicillin allergy.",
      },
      {
        class: "Analgesia",
        examples: ["Acetaminophen", "Ibuprofen"],
        notes: "Systemic steroids are reserved for severe odynophagia under clinician direction.",
      },
    ],
    selfCare: ["Soft diet, fluids, salt-water gargles", "Stay home until 12–24 hours on antibiotics and afebrile"],
    seekCare: "Same day if cannot swallow, drooling, or neck swelling.",
  }),
  defineDisease({
    id: "infectious-mono",
    name: "Infectious mononucleosis",
    icd10: "B27.90",
    specialty: "infectious-disease",
    department: "Primary care / Pediatrics",
    urgency: "soon",
    setting: "Outpatient; hospitalize for airway compromise or hemolysis",
    summary:
      "EBV (occasionally CMV) syndrome of fever, pharyngitis, and cervical lymphadenopathy, often with fatigue and splenomegaly in adolescents and young adults.",
    hallmarks: ["sore-throat", "fatigue", "swollen-lymph", "fever", "malaise"],
    supportive: ["headache", "anorexia", "muscle-aches"],
    occasional: ["rash", "abdominal-pain", "jaundice"],
    age: [12, 35],
    vitals: { fever: true },
    redFlags: ["Airway obstruction", "Severe abdominal pain (splenic rupture)", "Jaundice with anemia"],
    workup: ["Heterophile antibody", "EBV-specific serology if needed", "CBC with atypical lymphocytes", "LFTs", "Avoid empiric amoxicillin (rash)"],
    prevention: ["Do not share drinks/utensils while ill", "No contact sports until spleen risk has passed"],
    medications: [
      {
        class: "Supportive",
        examples: ["Acetaminophen", "NSAIDs", "Fluids"],
        notes: "Antivirals are not routinely indicated. Steroids only for complications (airway, hemolysis) under specialist care.",
      },
    ],
    selfCare: ["Prolonged rest as needed", "Avoid alcohol while LFTs abnormal", "Activity restriction 3–4 weeks"],
    seekCare: "Emergency care for left-shoulder or severe abdominal pain, or breathing difficulty.",
  }),
  defineDisease({
    id: "otitis-media",
    name: "Acute otitis media",
    icd10: "H66.90",
    specialty: "otolaryngology",
    department: "Pediatrics / Primary care / ENT",
    urgency: "soon",
    setting: "Clinic; ENT if recurrent, complications, or treatment failure",
    summary:
      "Middle-ear infection, most common in young children. Ear pain, fever, and a bulging tympanic membrane after a viral URI.",
    hallmarks: ["ear-pain", "fever", "malaise"],
    supportive: ["hearing-loss", "runny-nose", "irritability", "anorexia"],
    occasional: ["vomiting", "diarrhea", "tinnitus"],
    age: [0, 12],
    vitals: { fever: true },
    redFlags: ["Mastoid swelling", "Facial palsy", "Severe headache or neck stiffness", "Persistent high fever"],
    workup: ["Otoscopy", "Pneumatic otoscopy when available", "Hearing assessment if recurrent"],
    prevention: ["Pneumococcal and influenza vaccines", "Avoid smoke exposure", "Breastfeeding in infancy", "Tympanostomy tubes for recurrent AOM per ENT"],
    medications: [
      {
        class: "First-line antibiotic when indicated",
        examples: ["Amoxicillin (high-dose)", "Amoxicillin-clavulanate if recent antibiotics"],
        notes: "Watchful waiting is appropriate in selected children ≥2 years with mild disease.",
      },
      {
        class: "Analgesia",
        examples: ["Acetaminophen", "Ibuprofen"],
        notes: "Pain control is essential whether or not antibiotics are used.",
      },
    ],
    selfCare: ["Upright comfort, analgesia", "Do not insert objects in the canal"],
    seekCare: "Urgent if swelling behind the ear, neck stiffness, or persistent fever on therapy.",
  }),
  defineDisease({
    id: "otitis-externa",
    name: "Otitis externa (swimmer's ear)",
    icd10: "H60.9",
    specialty: "otolaryngology",
    department: "Primary care / ENT",
    urgency: "soon",
    setting: "Clinic; urgent if diabetic/immunocompromised (malignant OE)",
    summary:
      "Infection of the external auditory canal, typically Pseudomonas or S. aureus after water exposure or trauma from cotton swabs. Pain on tragus traction is classic.",
    hallmarks: ["ear-pain"],
    supportive: ["hearing-loss", "itch"],
    occasional: ["fever", "swollen-lymph", "tinnitus"],
    redFlags: ["Diabetes with severe canal pain (malignant otitis externa)", "Facial palsy", "Auricular cellulitis"],
    workup: ["Otoscopic exam", "Culture if severe, recurrent, or immunocompromised"],
    prevention: ["Keep canals dry after swimming", "Avoid cotton swabs", "Acetic acid drops as prophylaxis in swimmers"],
    medications: [
      {
        class: "Otic antibiotic ± steroid drops",
        examples: ["Ciprofloxacin-dexamethasone", "Ofloxacin", "Neomycin/polymyxin/hydrocortisone if TM intact"],
        notes: "Wick placement if the canal is occluded. Oral cipro plus ENT for malignant OE.",
      },
    ],
    selfCare: ["Keep ear dry", "Analgesia", "Do not irrigate a closed canal"],
    seekCare: "Same day if diabetic, immunocompromised, or spreading redness.",
  }),
  defineDisease({
    id: "pertussis",
    name: "Pertussis (whooping cough)",
    icd10: "A37.90",
    specialty: "infectious-disease",
    department: "Pediatrics / Infectious diseases / Public health",
    urgency: "urgent",
    setting: "Clinic with isolation; hospitalize infants",
    summary:
      "Bordetella pertussis infection. Catarrhal phase then paroxysmal cough with inspiratory whoop and post-tussive emesis. Infants may present with apnea rather than whoop.",
    hallmarks: ["cough", "dry-cough"],
    supportive: ["runny-nose", "vomiting", "fatigue"],
    occasional: ["fever", "syncope", "shortness-of-breath"],
    age: [0, 80],
    redFlags: ["Apnea in infants", "Cyanosis with coughing spells", "Seizure", "Unvaccinated infant contact"],
    workup: ["PCR from nasopharyngeal swab", "Culture in outbreaks", "CBC may show lymphocytosis"],
    prevention: ["DTaP childhood series and Tdap boosters", "Tdap in every pregnancy", "Post-exposure antibiotics for close contacts"],
    medications: [
      {
        class: "Macrolide antibiotic",
        examples: ["Azithromycin", "Clarithromycin", "Erythromycin"],
        notes: "Treat early to reduce spread; cough may persist (100-day cough). TMP-SMX if macrolide-intolerant.",
      },
    ],
    selfCare: ["Isolation for 5 days of antibiotics", "Small frequent meals", "Humidified air"],
    seekCare: "Emergency care for infants, cyanotic spells, or apnea.",
  }),
  defineDisease({
    id: "tuberculosis-suspect",
    name: "Pulmonary tuberculosis (suspect)",
    icd10: "A15.0",
    specialty: "infectious-disease",
    department: "Pulmonology / Infectious diseases — airborne isolation",
    urgency: "urgent",
    setting: "Public-health / hospital isolation until contagious TB excluded",
    summary:
      "Mycobacterium tuberculosis of the lung. Subacute cough, night sweats, weight loss, and hemoptysis, especially with exposure, incarceration, homelessness, or immunosuppression.",
    hallmarks: ["cough", "night-sweats", "weight-loss", "fever", "fatigue"],
    supportive: ["hemoptysis", "anorexia", "malaise", "night-itch"],
    occasional: ["chest-pain", "shortness-of-breath", "swollen-lymph"],
    vitals: { fever: true },
    comorbidBoost: ["immunocompromised", "cancer", "diabetes", "kidney-disease"],
    smokerBoost: true,
    travelBoost: true,
    redFlags: ["Hemoptysis", "HIV with cough", "Household infant exposure", "Respiratory failure"],
    workup: [
      "Airborne isolation",
      "Chest radiograph",
      "Sputum AFB smear, culture, and NAAT (GeneXpert)",
      "HIV test",
      "IGRA or TST for latent disease after active disease is addressed",
    ],
    prevention: [
      "Identify and treat latent TB in high-risk people",
      "Airborne precautions and contact investigation",
      "BCG in selected high-burden settings",
      "HIV care and nutrition",
    ],
    medications: [
      {
        class: "RIPE antimycobacterial therapy (active TB)",
        examples: ["Rifampin", "Isoniazid", "Pyrazinamide", "Ethambutol"],
        notes: "Never start without public-health/ID coordination. Adherence, hepatotoxicity monitoring, and susceptibility testing are mandatory.",
      },
    ],
    selfCare: ["Do not delay evaluation", "Mask and isolate until cleared", "Report to public health as required"],
    seekCare: "Same-day evaluation at a facility able to isolate; call ahead.",
  }),
  defineDisease({
    id: "cellulitis",
    name: "Cellulitis",
    icd10: "L03.90",
    specialty: "infectious-disease",
    department: "Emergency / Internal medicine / Dermatology",
    urgency: "urgent",
    setting: "Urgent care or ED; admit if systemic, orbital, or rapidly spreading",
    summary:
      "Spreading bacterial infection of dermis and subcutis, usually beta-hemolytic streptococci or S. aureus. Warmth, erythema, tenderness, and fever after a skin break.",
    hallmarks: ["skin-redness", "skin-warmth", "fever"],
    supportive: ["chills", "malaise", "wound"],
    occasional: ["swollen-lymph", "blisters", "fatigue"],
    vitals: { fever: true, tachy: true },
    comorbidBoost: ["diabetes", "immunocompromised"],
    redFlags: ["Rapid spread", "Creptius or bullae (necrotizing infection)", "Hypotension", "Orbital involvement", "Animal bite over a joint"],
    workup: ["Clinical", "Blood cultures if febrile/systemic", "Ultrasound to exclude abscess", "X-ray/CT if gas or osteomyelitis suspected", "Wound culture if drained"],
    prevention: ["Skin care and treat tinea pedis", "Compression for chronic edema", "Glycemic control", "Prompt care of wounds"],
    medications: [
      {
        class: "Anti-streptococcal ± MRSA coverage",
        examples: ["Cephalexin", "Dicloxacillin", "Clindamycin", "TMP-SMX or doxycycline if MRSA likely", "Cefazolin IV"],
        notes: "Mark the border, reassess in 48 hours. Elevate the limb.",
      },
    ],
    selfCare: ["Elevation, rest", "Do not delay if spreading"],
    seekCare: "ED for fever with spreading redness, face/orbit, or severe pain out of proportion.",
  }),
  defineDisease({
    id: "sepsis-suspect",
    name: "Sepsis (suspected)",
    icd10: "A41.9",
    specialty: "emergency",
    department: "Emergency department / Critical care — activate immediately",
    urgency: "emergency",
    setting: "Emergency department now",
    summary:
      "Life-threatening organ dysfunction due to a dysregulated response to infection. Fever or hypothermia, tachycardia, confusion, and a suspected source. Minutes matter.",
    hallmarks: ["fever", "chills", "confusion", "fatigue", "malaise"],
    supportive: ["shortness-of-breath", "low-urine", "nausea", "sweating"],
    occasional: ["rash", "abdominal-pain", "cough", "dysuria", "petechiae"],
    vitals: { fever: true, tachy: true, hypotensive: true, hypoxic: true },
    comorbidBoost: ["diabetes", "immunocompromised", "cancer", "kidney-disease", "heart-disease"],
    redFlags: ["Hypotension", "Lactate elevation", "Mottled skin", "Altered mentation", "Oliguria"],
    workup: [
      "Immediate ABCs and IV access",
      "Lactate, CBC, CMP, coagulation, blood cultures before antibiotics if it does not delay them",
      "Source studies (CXR, UA, imaging)",
      "qSOFA/SOFA and sepsis bundle",
    ],
    prevention: ["Vaccination", "Early treatment of infections in high-risk patients", "Device care", "Hand hygiene in hospitals"],
    medications: [
      {
        class: "Immediate empiric antimicrobials plus resuscitation",
        examples: ["Guideline-based broad-spectrum IV antibiotics", "IV crystalloid 30 mL/kg if hypotensive/lactate ≥4", "Norepinephrine if shock"],
        notes: "This is a time-critical hospital protocol, not an outpatient prescription.",
      },
    ],
    selfCare: ["Do not stay home"],
    seekCare: "Call emergency services immediately.",
  }),
  defineDisease({
    id: "malaria-suspect",
    name: "Malaria (suspect)",
    icd10: "B54",
    specialty: "infectious-disease",
    department: "Infectious diseases / Emergency — travel medicine",
    urgency: "emergency",
    setting: "Emergency department; notify ID",
    summary:
      "Plasmodium infection after travel to or residence in an endemic region. Cyclic fever, chills, headache, myalgias; falciparum can cause cerebral malaria and shock.",
    hallmarks: ["fever", "chills", "headache", "sweating", "muscle-aches"],
    supportive: ["fatigue", "nausea", "vomiting", "malaise"],
    occasional: ["confusion", "jaundice", "diarrhea", "abdominal-pain"],
    vitals: { fever: true, highFever: true, tachy: true },
    travelBoost: true,
    redFlags: ["Any neurologic change", "Jaundice", "Oliguria", "Severe anemia", "Pregnancy"],
    workup: ["Thick and thin smears STAT, repeat if negative", "Rapid diagnostic test", "CBC, CMP, bilirubin, G6PD if primaquine considered", "Travel history with dates and prophylaxis"],
    prevention: ["Chemoprophylaxis matched to destination", "Insecticide-treated nets", "Repellents", "Seek care for fever after endemic travel — even months later for vivax/ovale"],
    medications: [
      {
        class: "Artemisinin combination or other species-specific regimen",
        examples: ["Artemether-lumefantrine", "IV artesunate for severe malaria", "Atovaquone-proguanil", "Chloroquine if sensitive"],
        notes: "Regimen depends on species, severity, pregnancy, and resistance map. ID/CDC consultation.",
      },
    ],
    selfCare: ["Do not wait for a 'typical' fever pattern"],
    seekCare: "Emergency department the same day for fever after malaria-endemic travel.",
  }),
  defineDisease({
    id: "dengue-suspect",
    name: "Dengue fever (suspect)",
    icd10: "A90",
    specialty: "infectious-disease",
    department: "Infectious diseases / Emergency — travel",
    urgency: "urgent",
    setting: "ED or hospital if warning signs; outpatient only if close follow-up is possible",
    summary:
      "Aedes-transmitted flavivirus. High fever, severe myalgias, retro-orbital pain, and rash. Warning signs include abdominal pain, persistent vomiting, mucosal bleed, and rising hematocrit with falling platelets.",
    hallmarks: ["fever", "muscle-aches", "headache", "fatigue", "rash"],
    supportive: ["nausea", "vomiting", "red-eyes", "malaise", "joint-pain"],
    occasional: ["petechiae", "abdominal-pain", "easy-bleeding"],
    vitals: { fever: true, highFever: true },
    travelBoost: true,
    redFlags: ["Abdominal pain", "Persistent vomiting", "Bleeding", "Lethargy", "Narrow pulse pressure"],
    workup: ["NS1 antigen / IgM", "CBC with hematocrit and platelets serially", "LFTs", "Tourniquet test"],
    prevention: ["Mosquito bite avoidance", "Community vector control", "Dengue vaccine only in selected seropositive populations per local guidance"],
    medications: [
      {
        class: "Supportive (no NSAIDs)",
        examples: ["Acetaminophen", "Careful IV fluids in critical phase"],
        notes: "Avoid aspirin and NSAIDs because of bleeding risk. No specific antiviral in routine care.",
      },
    ],
    selfCare: ["Daily labs as directed during defervescence", "Hydration"],
    seekCare: "Emergency care for any warning sign, especially around the time fever breaks.",
  }),
  defineDisease({
    id: "typhoid-suspect",
    name: "Typhoid / enteric fever (suspect)",
    icd10: "A01.00",
    specialty: "infectious-disease",
    department: "Infectious diseases / Travel clinic",
    urgency: "urgent",
    setting: "Hospital if toxic; otherwise ID-directed outpatient therapy where safe",
    summary:
      "Salmonella Typhi or Paratyphi after exposure in endemic regions or from a carrier. Stepwise fever, abdominal pain, headache, relative bradycardia, and sometimes rose spots. Diarrhea or constipation may occur.",
    hallmarks: ["fever", "abdominal-pain", "headache", "fatigue", "anorexia"],
    supportive: ["constipation", "diarrhea", "malaise", "chills"],
    occasional: ["rash", "confusion", "cough", "nausea"],
    vitals: { fever: true, highFever: true, brady: true },
    travelBoost: true,
    redFlags: ["GI bleeding", "Peritonitis (ileal perforation)", "Encephalopathy", "Shock"],
    workup: ["Blood cultures before antibiotics", "Stool culture", "CBC (leukopenia), LFTs", "Bone marrow culture if elusive"],
    prevention: ["Typhoid vaccination for travelers", "Food and water precautions", "Do not work in food service until cleared"],
    medications: [
      {
        class: "Systemic antibiotic guided by susceptibility",
        examples: ["Ceftriaxone", "Azithromycin", "Carbapenem for XDR strains", "Fluoroquinolone only if proven susceptible"],
        notes: "Resistance is region-specific. Empiric choice follows travel geography.",
      },
    ],
    selfCare: ["Hydration", "Infection-control hygiene"],
    seekCare: "Urgent evaluation for fever after South Asia or similar exposure.",
  }),
  defineDisease({
    id: "lyme",
    name: "Lyme disease (early)",
    icd10: "A69.20",
    specialty: "infectious-disease",
    department: "Primary care / Infectious diseases / Rheumatology",
    urgency: "soon",
    setting: "Primary care; ID if neurologic, cardiac, or arthritis",
    summary:
      "Borrelia burgdorferi after Ixodes tick exposure. Early: erythema migrans (expanding target plaque), fatigue, fever, arthralgia. Later: arthritis, neuropathy, AV block.",
    hallmarks: ["target-lesion", "fatigue", "joint-pain", "malaise"],
    supportive: ["fever", "headache", "muscle-aches", "swollen-lymph"],
    occasional: ["numbness", "facial-droop", "palpitations"],
    redFlags: ["Facial palsy", "Heart block / syncope", "Meningitis symptoms"],
    workup: ["Clinical diagnosis of EM — treat without waiting for serology", "Two-tier serology for later disease", "ECG if cardiac symptoms"],
    prevention: ["Permethrin-treated clothing, DEET", "Tick checks after wooded exposure", "Prompt tick removal", "Prophylactic single-dose doxycycline in selected high-risk bites"],
    medications: [
      {
        class: "Oral tetracycline or beta-lactam",
        examples: ["Doxycycline", "Amoxicillin", "Cefuroxime"],
        notes: "Duration and agent depend on syndrome (EM vs arthritis vs neuroborreliosis). IV ceftriaxone for some neurologic disease.",
      },
    ],
    selfCare: ["Photograph the rash", "Complete the antibiotic course"],
    seekCare: "Prompt clinic visit for expanding rash or flu-like illness after tick country travel.",
  }),
  defineDisease({
    id: "herpes-zoster",
    name: "Herpes zoster (shingles)",
    icd10: "B02.9",
    specialty: "infectious-disease",
    department: "Primary care / Dermatology / Ophthalmology if facial",
    urgency: "soon",
    setting: "Clinic within 72 hours of rash; ED for eye involvement or disseminated disease",
    summary:
      "Reactivation of varicella-zoster virus in a dorsal root ganglion. Painful unilateral dermatomal vesicles. Risk of post-herpetic neuralgia and, if V1, sight-threatening keratitis.",
    hallmarks: ["dermatomal-rash", "blisters", "skin-redness"],
    supportive: ["fatigue", "malaise", "fever", "itch"],
    occasional: ["eye-pain", "photophobia", "headache"],
    age: [18, 100],
    comorbidBoost: ["immunocompromised", "cancer"],
    redFlags: ["Rash on the nose or eye pain (Hutchinson sign)", "Hearing loss or facial palsy (Ramsay Hunt)", "Disseminated vesicles", "Immunocompromise"],
    workup: ["Clinical", "PCR of lesion if uncertain", "Urgent ophthalmology for V1"],
    prevention: ["Recombinant zoster vaccine (Shingrix) in adults ≥50 and selected immunocompromised younger adults"],
    medications: [
      {
        class: "Systemic antiviral",
        examples: ["Valacyclovir", "Famciclovir", "Acyclovir"],
        notes: "Start within 72 hours of rash (later if new lesions or immunocompromised). IV acyclovir for disseminated or CNS disease.",
      },
      {
        class: "Analgesia for acute pain / PHN prevention strategies",
        examples: ["Acetaminophen", "Gabapentin (selected)", "Short course glucocorticoid in selected immunocompetent adults"],
        notes: "Pain regimens are individualized; opioids are last-line.",
      },
    ],
    selfCare: ["Keep lesions covered until crusted", "Avoid contact with pregnant non-immune and neonates"],
    seekCare: "Same day for facial zoster, eye symptoms, or immunosuppression.",
  }),
  defineDisease({
    id: "varicella",
    name: "Varicella (chickenpox)",
    icd10: "B01.9",
    specialty: "infectious-disease",
    department: "Pediatrics / Primary care",
    urgency: "soon",
    setting: "Home isolation if well; hospitalize if adult, pregnant, or immunocompromised",
    summary:
      "Primary VZV: pruritic vesicles in crops ('dewdrop on a rose petal') with fever, more severe in adults. Complications include pneumonia, encephalitis, and bacterial superinfection.",
    hallmarks: ["rash", "blisters", "itch", "fever"],
    supportive: ["fatigue", "malaise", "headache", "anorexia"],
    occasional: ["cough", "sore-throat"],
    age: [0, 40],
    vitals: { fever: true },
    redFlags: ["Dyspnea (varicella pneumonia)", "Confusion", "Pregnancy", "Immunocompromise"],
    workup: ["Clinical", "PCR if atypical", "CXR if respiratory symptoms"],
    prevention: ["Two-dose varicella vaccine", "Post-exposure vaccine or VariZIG in selected patients"],
    medications: [
      {
        class: "Antiviral in adolescents, adults, and high-risk children",
        examples: ["Acyclovir", "Valacyclovir"],
        notes: "Not routinely required in healthy young children. Aspirin is contraindicated.",
      },
    ],
    selfCare: ["Isolation until lesions crusted", "Calamine, cool baths", "Keep nails short"],
    seekCare: "Urgent if breathing difficulty, pregnancy, or immunocompromise.",
  }),
  defineDisease({
    id: "measles",
    name: "Measles",
    icd10: "B05.9",
    specialty: "infectious-disease",
    department: "Public health / Infectious diseases — airborne isolation",
    urgency: "emergency",
    setting: "Call ahead to a facility with airborne isolation; do not sit in a crowded waiting room",
    summary:
      "Highly contagious paramyxovirus. Fever, cough, coryza, conjunctivitis, Koplik spots, then a descending maculopapular rash. Outbreaks occur in unvaccinated clusters.",
    hallmarks: ["fever", "cough", "runny-nose", "red-eyes", "rash"],
    supportive: ["photophobia", "malaise", "anorexia", "sore-throat"],
    occasional: ["diarrhea", "ear-pain"],
    vitals: { fever: true, highFever: true },
    travelBoost: true,
    redFlags: ["Dyspnea", "Encephalitis", "Pregnancy", "Infant contact"],
    workup: ["Notify public health immediately", "IgM / PCR", "Airborne isolation"],
    prevention: ["MMR vaccination", "Post-exposure MMR or IG in selected contacts"],
    medications: [
      {
        class: "Supportive plus vitamin A in children",
        examples: ["Vitamin A (age-dosed)", "Antipyretics"],
        notes: "No routine antiviral. Vitamin A reduces measles mortality in deficient children — clinician-dosed.",
      },
    ],
    selfCare: ["Isolation 4 days after rash onset", "Do not attend school or work"],
    seekCare: "Call public health / ED before arriving.",
  }),
  defineDisease({
    id: "rsv-bronchiolitis",
    name: "RSV bronchiolitis",
    icd10: "J21.0",
    specialty: "pediatrics",
    department: "Pediatrics / Pediatric emergency",
    urgency: "urgent",
    setting: "Pediatric ED if hypoxic, dehydrating, or young infant; otherwise close outpatient follow-up",
    summary:
      "Viral lower-airway disease of infants: cough, wheeze, tachypnea, and feeding difficulty after a URI prodrome. RSV is the leading cause; support is the mainstay.",
    hallmarks: ["cough", "wheezing", "shortness-of-breath", "runny-nose"],
    supportive: ["fever", "dehydration", "anorexia"],
    occasional: ["ear-pain", "vomiting"],
    age: [0, 3],
    vitals: { tachy: true, hypoxic: true, fever: true },
    redFlags: ["Apnea", "Cyanosis", "Poor feeding", "Age <12 weeks", "Prematurity"],
    workup: ["Pulse oximetry", "RSV testing if it changes cohorting", "CXR not routine", "Hydration assessment"],
    prevention: [
      "Nirsevimab (or palivizumab in selected high-risk infants) per current guidance",
      "Maternal RSV vaccine in pregnancy where recommended",
      "Avoid smoke; hand hygiene",
    ],
    medications: [
      {
        class: "Supportive",
        examples: ["Oxygen", "Nasal saline and suction", "IV/NG fluids if needed"],
        notes: "Bronchodilators, steroids, and antibiotics are not routine for typical RSV bronchiolitis.",
      },
    ],
    selfCare: ["Small frequent feeds", "Watch work of breathing", "Keep away from other infants"],
    seekCare: "Emergency care for pauses in breathing, poor feeding, or blue color.",
  }),
  defineDisease({
    id: "croup",
    name: "Croup (laryngotracheobronchitis)",
    icd10: "J05.0",
    specialty: "pediatrics",
    department: "Pediatric emergency / Pediatrics",
    urgency: "urgent",
    setting: "Pediatric ED if stridor at rest; clinic if mild barky cough only",
    summary:
      "Viral inflammation of the subglottic airway in toddlers. Barking cough, hoarseness, and inspiratory stridor, worse at night.",
    hallmarks: ["cough", "hoarseness", "stridor"],
    supportive: ["fever", "runny-nose", "sore-throat"],
    occasional: ["shortness-of-breath"],
    age: [0, 6],
    vitals: { fever: true },
    redFlags: ["Stridor at rest", "Drooling (think epiglottitis/abscess)", "Cyanosis", "Tripod position"],
    workup: ["Clinical", "Do not agitate", "Steeple sign on x-ray is not required"],
    prevention: ["Usual childhood viral precautions", "Keep the child calm during attacks"],
    medications: [
      {
        class: "Corticosteroid ± nebulized epinephrine",
        examples: ["Dexamethasone", "Nebulized racemic epinephrine for moderate–severe"],
        notes: "Single-dose dexamethasone is standard. Observe after epinephrine for rebound.",
      },
    ],
    selfCare: ["Cool night air or steam as comfort measures", "Upright holding"],
    seekCare: "Emergency care for stridor at rest or labored breathing.",
  }),
  defineDisease({
    id: "food-poisoning",
    name: "Acute foodborne gastroenteritis",
    icd10: "A05.9",
    specialty: "infectious-disease",
    department: "Emergency / Gastroenterology / Public health if outbreak",
    urgency: "soon",
    setting: "Home if mild; ED if bloody diarrhea, high fever, severe dehydration, or pregnancy with listeria risk",
    summary:
      "Toxin-mediated or infectious diarrhea and vomiting clustered after a shared meal. Timing hints at the organism (hours: S. aureus/B. cereus toxin; days: Salmonella, Campylobacter, STEC).",
    hallmarks: ["diarrhea", "vomiting", "nausea", "abdominal-pain"],
    supportive: ["fever", "chills", "malaise", "dehydration"],
    occasional: ["blood-stool", "muscle-aches", "headache"],
    vitals: { fever: true, tachy: true },
    redFlags: ["Bloody diarrhea", "Anuria", "Confusion", "Pregnancy with fever and deli meats (listeria)", "Recent antibiotics (C. difficile)"],
    workup: ["Hydration status", "Stool NAAT/culture if severe, bloody, or outbreak", "CBC/CMP if dehydrated", "Shiga toxin testing before empiric antimotility"],
    prevention: ["Safe food temperatures", "Hand hygiene", "Avoid unpasteurized products in pregnancy", "Restaurant/public-health reporting of clusters"],
    medications: [
      {
        class: "Oral rehydration; targeted antimicrobials only when indicated",
        examples: ["ORS", "Azithromycin or ciprofloxacin for selected traveler/severe invasive disease", "Avoid antimotility in STEC"],
        notes: "Most viral and toxin food poisoning is supportive. Antibiotics can worsen STEC outcomes.",
      },
    ],
    selfCare: ["ORS, bland diet as tolerated", "Do not prepare food for others until 48 hours after symptoms"],
    seekCare: "ED for bloody stools, high fever, pregnancy, infant/elderly, or inability to keep fluids down.",
  }),
  defineDisease({
    id: "acute-gastroenteritis",
    name: "Viral gastroenteritis",
    icd10: "A08.4",
    specialty: "gastroenterology",
    department: "Primary care / Pediatrics / Emergency if dehydrated",
    urgency: "soon",
    setting: "Home rehydration; ED if severe volume loss",
    summary:
      "Norovirus, rotavirus, or similar. Abrupt vomiting and watery diarrhea with cramping, usually 1–3 days. The danger is dehydration, especially in infants and older adults.",
    hallmarks: ["vomiting", "diarrhea", "nausea", "abdominal-pain"],
    supportive: ["fever", "malaise", "muscle-aches", "anorexia"],
    occasional: ["headache", "chills"],
    vitals: { tachy: true, fever: true },
    redFlags: ["Bloody stool", "Severe abdominal pain", "No urine for 12 hours", "Lethargy", "Persistent vomiting"],
    workup: ["Clinical", "Electrolytes if dehydrated", "Stool studies if prolonged, bloody, or immunocompromised"],
    prevention: ["Handwashing (alcohol gel is less effective against norovirus)", "Rotavirus vaccine in infants", "Stay home from food service"],
    medications: [
      {
        class: "Rehydration and selected antiemetic",
        examples: ["Oral rehydration solution", "Ondansetron in selected vomiting", "Avoid routine antidiarrheals in children"],
        notes: "Antibiotics are not indicated for typical viral illness.",
      },
    ],
    selfCare: ["Small sips of ORS", "Advance diet as tolerated"],
    seekCare: "ED for lethargy, dry mucous membranes, or no urine output.",
  }),
];
