import { defineDisease } from "../define";

export const MSK_DERM_OTHER = [
  defineDisease({
    id: "osteoarthritis",
    name: "Osteoarthritis",
    icd10: "M19.90",
    specialty: "rheumatology",
    department: "Rheumatology / Orthopedics / Primary care",
    urgency: "routine",
    setting: "Primary care / MSK clinic",
    summary:
      "Degenerative joint disease. Activity-related pain, brief stiffness, and bony enlargement, especially knees, hips, hands, and spine. Inflammatory markers are typically normal.",
    hallmarks: ["joint-pain", "limited-motion"],
    supportive: ["morning-stiffness", "back-pain"],
    occasional: ["joint-swelling"],
    age: [40, 100],
    redFlags: ["Hot swollen joint with fever (septic arthritis)", "Sudden locking (mechanical derangement)", "Night bone pain with weight loss"],
    workup: ["Clinical ± plain radiographs", "ESR/CRP if inflammatory arthritis suspected", "Arthrocentesis if effusion is hot or unclear"],
    prevention: ["Weight reduction for knee OA", "Quadriceps strengthening", "Avoid repetitive injury", "Treat occupational overuse"],
    medications: [
      {
        class: "Analgesia and intra-articular options",
        examples: ["Topical NSAID", "Oral NSAID if GI/CV/renal risk allows", "Acetaminophen", "Intra-articular corticosteroid", "Duloxetine in selected chronic pain"],
        notes: "Opioids are not first-line. Glucosamine evidence is weak. Joint replacement when function is lost despite conservative care.",
      },
    ],
    selfCare: ["Land-based exercise, tai chi, or pool therapy", "Cane in the contralateral hand for hip/knee"],
    seekCare: "Urgent if a single joint is hot, red, and you have fever.",
  }),
  defineDisease({
    id: "rheumatoid-arthritis",
    name: "Rheumatoid arthritis",
    icd10: "M06.9",
    specialty: "rheumatology",
    department: "Rheumatology — early-arthritis clinic",
    urgency: "soon",
    setting: "Rheumatology within weeks; earlier if many swollen joints",
    summary:
      "Autoimmune symmetric polyarthritis of small joints with prolonged morning stiffness, fatigue, and extra-articular lung/eye/vessel disease. Early DMARD therapy preserves joints.",
    hallmarks: ["joint-pain", "joint-swelling", "morning-stiffness", "fatigue"],
    supportive: ["malaise", "anorexia", "weight-loss"],
    occasional: ["fever", "numbness", "dry-eyes"],
    age: [20, 80],
    sexBias: "female",
    redFlags: ["Cervical myelopathy", "Scleritis", "Rheumatoid lung with hypoxia", "Septic joint on immunosuppression"],
    workup: ["RF, anti-CCP, ESR/CRP, CBC, CMP, hepatitis B/C and TB before biologics", "Hand/foot radiographs or ultrasound", "CXR"],
    prevention: ["Smoking cessation (major modifiable risk)", "Vaccinations before immunosuppression", "Bone protection on steroids"],
    medications: [
      {
        class: "csDMARD then bDMARD/tsDMARD",
        examples: ["Methotrexate with folic acid", "Sulfasalazine", "Hydroxychloroquine", "TNF, IL-6, JAK inhibitors as indicated", "Short bridging prednisone"],
        notes: "Methotrexate is teratogenic — contraception counseling. JAK inhibitors have boxed CV/clot/cancer warnings in some groups.",
      },
    ],
    selfCare: ["Daily range-of-motion", "Pace activities", "Do not stop methotrexate because you feel better without talking to rheumatology"],
    seekCare: "Urgent rheumatology for persistent synovitis; ED for a hot joint and fever.",
  }),
  defineDisease({
    id: "gout",
    name: "Gout flare",
    icd10: "M10.9",
    specialty: "rheumatology",
    department: "Rheumatology / Primary care / Emergency if septic overlap",
    urgency: "soon",
    setting: "Clinic or ED for first podagra; always exclude septic arthritis if uncertain",
    summary:
      "Monosodium urate crystal arthritis. Exquisitely painful, red first MTP joint (podagra) or other joints, often overnight, after alcohol, diuretics, or a heavy meal.",
    hallmarks: ["joint-pain", "joint-swelling", "skin-redness", "skin-warmth"],
    supportive: ["fever", "malaise", "limited-motion"],
    occasional: ["back-pain"],
    age: [30, 90],
    sexBias: "male",
    comorbidBoost: ["kidney-disease", "hypertension", "diabetes"],
    redFlags: ["Fever with joint (septic until proven otherwise)", "Polyarticular storm", "Tophi with CKD"],
    workup: ["Arthrocentesis with crystal analysis and culture if first or atypical", "Serum urate (may be normal during a flare)", "CBC, CMP"],
    prevention: ["Urate-lowering to target <6 mg/dL", "Limit beer, spirits, sugar-sweetened drinks", "Weight reduction", "Review thiazides when possible"],
    medications: [
      {
        class: "Anti-inflammatory flare therapy then urate lowering",
        examples: ["NSAID", "Colchicine (early, renal-dosed)", "Corticosteroid", "Allopurinol or febuxostat for prevention with colchicine prophylaxis at initiation"],
        notes: "Do not start or stop allopurinol during a flare unless already on it. HLA-B*5801 screening in at-risk ancestry before allopurinol.",
      },
    ],
    selfCare: ["Ice, rest, elevation", "Hydration"],
    seekCare: "Same day if the joint is the first episode, you have fever, or you cannot walk.",
  }),
  defineDisease({
    id: "mechanical-lbp",
    name: "Mechanical low-back pain",
    icd10: "M54.50",
    specialty: "orthopedics",
    department: "Primary care / Spine / Physiotherapy",
    urgency: "routine",
    setting: "Primary care; ED for red flags",
    summary:
      "Nonspecific lumbar pain from muscles, discs, or facets. Worse with movement, better lying still. Most episodes improve in weeks. Imaging is not first-line without red flags.",
    hallmarks: ["back-pain"],
    supportive: ["muscle-aches", "limited-motion"],
    occasional: ["sciatica", "back-pain"],
    age: [16, 80],
    redFlags: ["Saddle anesthesia or bowel/bladder change (cauda equina)", "Fever and IV drug use (epidural abscess)", "Cancer history with night pain", "Progressive weakness", "Trauma in osteoporosis"],
    workup: ["History and neurologic exam", "Imaging only for red flags or pain >6 weeks not improving", "ESR if infection/cancer concern"],
    prevention: ["Regular activity, core endurance", "Lifting technique", "Avoid prolonged bed rest", "Ergonomics"],
    medications: [
      {
        class: "Time-limited analgesia; prefer non-drug first",
        examples: ["NSAIDs if safe", "Acetaminophen", "Non-benzodiazepine muscle relaxant short-term in selected adults"],
        notes: "Opioids and routine imaging worsen outcomes for nonspecific LBP. Physiotherapy and remaining active are first-line.",
      },
    ],
    selfCare: ["Stay as active as pain allows", "Heat", "Return to work plan"],
    seekCare: "Emergency care for saddle numbness, incontinence, or progressive leg weakness.",
  }),
  defineDisease({
    id: "sciatica",
    name: "Lumbosacral radiculopathy (sciatica)",
    icd10: "M54.30",
    specialty: "orthopedics",
    department: "Spine / Neurology / Neurosurgery if deficit",
    urgency: "soon",
    setting: "Primary care / spine; ED for cauda equina",
    summary:
      "Nerve-root compression, usually L5/S1 disc. Shooting pain below the knee, dermatomal numbness, and sometimes weakness. Most improve without surgery; cauda equina does not wait.",
    hallmarks: ["sciatica", "back-pain", "numbness"],
    supportive: ["tingling", "muscle-weakness", "limited-motion"],
    occasional: ["constipation"],
    age: [20, 70],
    redFlags: ["Bilateral sciatica with saddle numbness", "Urinary retention", "Foot drop that is worsening"],
    workup: ["Straight-leg raise, motor/sensory/reflex exam", "MRI if deficit, intractable pain, or surgery/injection planned", "Glucose if neuropathy mimic"],
    prevention: ["Activity, core work", "Smoking cessation (disc health)", "Weight management"],
    medications: [
      {
        class: "Neuropathic and anti-inflammatory options; procedure if refractory",
        examples: ["NSAID", "Gabapentin in selected", "Oral steroid burst sometimes used", "Epidural steroid injection", "Discectomy if persistent disabling deficit"],
        notes: "Evidence for systemic steroids is mixed. Surgery is for persistent pain or progressive deficit, not an MRI finding alone.",
      },
    ],
    selfCare: ["Stay mobile", "Avoid prolonged sitting on a wallet"],
    seekCare: "Emergency department for bowel/bladder change or saddle numbness.",
  }),
  defineDisease({
    id: "fibromyalgia",
    name: "Fibromyalgia",
    icd10: "M79.7",
    specialty: "rheumatology",
    department: "Rheumatology / Pain / Primary care",
    urgency: "routine",
    setting: "Outpatient — diagnosis of widespread pain with fatigue and sleep disturbance after inflammatory disease is excluded",
    summary:
      "Nociplastic pain disorder. Widespread musculoskeletal pain, unrefreshing sleep, fatigue, and cognitive fog without synovitis or elevated CRP. Central sensitization, not joint destruction.",
    hallmarks: ["muscle-aches", "fatigue", "insomnia", "joint-pain"],
    supportive: ["headache", "anxiety", "depressed-mood", "bloating"],
    occasional: ["numbness", "dizziness"],
    age: [20, 70],
    sexBias: "female",
    redFlags: ["Objective synovitis", "Fever", "Night sweats and weight loss", "True muscle weakness"],
    workup: ["CBC, CRP/ESR, TSH, CK, 25-OH D as a 'don't miss' panel", "Avoid endless autoantibody panels if exam is non-inflammatory"],
    prevention: ["Sleep regularity", "Graded exercise", "Treat mood and PTSD when present"],
    medications: [
      {
        class: "Pain modulators — not high-dose opioids",
        examples: ["Amitriptyline at night", "Duloxetine", "Pregabalin", "Cyclobenzaprine short-term"],
        notes: "Opioids and systemic steroids are not indicated. Education and exercise outperform most drugs.",
      },
    ],
    selfCare: ["Start walking programs very gradually", "CBT-insomnia", "Pacing rather than boom-bust"],
    seekCare: "Rheumatology if joints swell or inflammatory labs rise.",
  }),
  defineDisease({
    id: "pmr",
    name: "Polymyalgia rheumatica",
    icd10: "M35.3",
    specialty: "rheumatology",
    department: "Rheumatology / Geriatrics — screen for GCA",
    urgency: "soon",
    setting: "Rheumatology promptly; ED the same day for new headache/jaw claudication/vision change (GCA)",
    summary:
      "Inflammatory girdle stiffness in people over 50. Profound morning stiffness of shoulders and hips, constitutional symptoms, and high ESR/CRP. Giant-cell arteritis can coexist and threaten sight.",
    hallmarks: ["shoulder-hip-stiffness", "morning-stiffness", "fatigue", "muscle-aches"],
    supportive: ["weight-loss", "anorexia", "fever", "headache"],
    occasional: ["joint-pain"],
    age: [50, 100],
    sexBias: "female",
    redFlags: ["New headache, jaw claudication, or visual change (treat as GCA immediately)", "Fever of unknown origin"],
    workup: ["ESR, CRP, CBC", "CK (should be near normal — distinguishes myositis)", "Glucose, SPEP as indicated", "Temporal artery pathway if GCA signs"],
    prevention: ["Bone protection when steroids start", "Vaccination", "Patient education on GCA visual symptoms"],
    medications: [
      {
        class: "Corticosteroid with steroid-sparing as needed",
        examples: ["Prednisone 12.5–25 mg typical PMR start", "Tocilizumab or methotrexate in selected steroid-dependent", "High-dose steroid immediately if GCA"],
        notes: "Response to steroids is usually dramatic in days. Failure should question the diagnosis.",
      },
    ],
    selfCare: ["Do not ignore a new headache once PMR is diagnosed"],
    seekCare: "Same-day emergency eye/ED care for visual symptoms.",
  }),
  defineDisease({
    id: "sle-suspect",
    name: "Systemic lupus erythematosus (suspect)",
    icd10: "M32.9",
    specialty: "rheumatology",
    department: "Rheumatology; ED for nephritis, chest pain, or CNS disease",
    urgency: "soon",
    setting: "Rheumatology; hospitalize organ-threatening disease",
    summary:
      "Systemic autoimmune disease. Malar or photosensitive rash, oral ulcers, arthritis, fatigue, serositis, cytopenias, and nephritis — especially in women of childbearing age.",
    hallmarks: ["fatigue", "joint-pain", "rash", "oral-ulcers", "fever"],
    supportive: ["hair-loss", "chest-pain", "photosensitivity", "swollen-lymph"],
    occasional: ["hematuria", "confusion", "pleuritic-pain"],
    age: [12, 50],
    sexBias: "female",
    redFlags: ["Chest pain (pericarditis/PE/CAD — lupus is a CAD risk)", "Edema with rising creatinine", "Seizure or psychosis", "Pregnancy"],
    workup: ["ANA with reflex ENA, anti-dsDNA, complement", "CBC, CMP, UA with protein/creatinine", "APL antibodies if clotting or pregnancy morbidity", "CXR/echo as indicated"],
    prevention: ["Sun protection", "Hydroxychloroquine as background therapy once diagnosed", "Vaccination", "Contraception planning; avoid trimethoprim-sulfa in some patients"],
    medications: [
      {
        class: "Antimalarial, steroids, immunosuppressants",
        examples: ["Hydroxychloroquine", "Prednisone", "Mycophenolate, azathioprine, cyclophosphamide, belimumab, anifrolumab — organ-specific"],
        notes: "Hydroxychloroquine needs baseline and ongoing retinal screening. Many agents are teratogenic.",
      },
    ],
    selfCare: ["SPF, hats", "Do not smoke"],
    seekCare: "Urgent rheumatology for suspected lupus; ED for chest pain, severe headache, or little urine.",
  }),
  defineDisease({
    id: "contact-dermatitis",
    name: "Contact dermatitis",
    icd10: "L25.9",
    specialty: "dermatology",
    department: "Dermatology / Primary care / Occupational medicine",
    urgency: "routine",
    setting: "Clinic; ED only if facial/airway swelling",
    summary:
      "Irritant or allergic skin inflammation at the site of exposure (nickel, fragrances, plants, gloves, cement). Itchy plaques, vesicles, and lichenification with chronicity.",
    hallmarks: ["rash", "itch", "skin-redness"],
    supportive: ["blisters"],
    occasional: ["hives"],
    redFlags: ["Facial or airway swelling", "Superinfection", "Occupational impairment"],
    workup: ["Exposure history", "Patch testing for chronic/occupational disease"],
    prevention: ["Allergen avoidance", "Gloves appropriate to the irritant", "Emollients as a barrier"],
    medications: [
      {
        class: "Topical corticosteroid and emollient; systemic only if severe",
        examples: ["Hydrocortisone to betamethasone depending on site", "Tacrolimus for face/folds", "Short oral prednisone for severe widespread ACD (poison ivy)"],
        notes: "Avoid long-term potent steroids on the face and genitals. Treat secondary infection if present.",
      },
    ],
    selfCare: ["Bland emollient, oatmeal soaks", "Wash the allergen off promptly"],
    seekCare: "Same day for eye/face involvement or suspected infection.",
  }),
  defineDisease({
    id: "psoriasis",
    name: "Psoriasis",
    icd10: "L40.9",
    specialty: "dermatology",
    department: "Dermatology / Rheumatology if joints",
    urgency: "routine",
    setting: "Dermatology; ED for generalized pustular or erythrodermic psoriasis",
    summary:
      "Immune-mediated plaques: well-demarcated silvery scale on elbows, knees, scalp, and sacrum. Nails and joints (psoriatic arthritis) may be involved. Associated with metabolic syndrome.",
    hallmarks: ["rash", "itch", "skin-redness"],
    supportive: ["joint-pain", "nail-pitting"],
    occasional: ["fatigue"],
    age: [10, 80],
    redFlags: ["Unstable widespread redness (erythroderma)", "Pustular feverish psoriasis", "New joint swelling"],
    workup: ["Clinical", "Screen for psoriatic arthritis", "Metabolic labs", "Biopsy if uncertain"],
    prevention: ["Smoking and alcohol reduction", "Weight management", "Avoid high-dose systemic steroids that can rebound", "Trigger awareness (strep, lithium, beta-blockers)"],
    medications: [
      {
        class: "Topicals then phototherapy / systemic / biologic",
        examples: ["Vitamin D analogues, topical steroid", "Methotrexate", "Apremilast", "TNF/IL-17/IL-23 biologics"],
        notes: "Systemics require infection screening. Do not abruptly stop biologics without a plan.",
      },
    ],
    selfCare: ["Emollients, scale softening", "Do not pick plaques"],
    seekCare: "Urgent if most of the skin is red or you have fever with pustules.",
  }),
  defineDisease({
    id: "atopic-dermatitis",
    name: "Atopic dermatitis (eczema)",
    icd10: "L20.9",
    specialty: "dermatology",
    department: "Dermatology / Allergy / Pediatrics",
    urgency: "routine",
    setting: "Clinic; ED for eczema herpeticum or severe superinfection",
    summary:
      "Chronic itchy inflammation of flexures in people with atopy. Barrier failure plus type-2 inflammation. Sleep loss and secondary infection are common.",
    hallmarks: ["itch", "rash", "skin-redness"],
    supportive: ["insomnia", "dry-skin"],
    occasional: ["hives", "wheezing"],
    age: [0, 40],
    comorbidBoost: ["asthma"],
    redFlags: ["Punched-out vesicles (eczema herpeticum)", "Fever with weeping skin", "Eye involvement"],
    workup: ["Clinical", "IgE not required", "Culture if infected", "Food testing only when history is suggestive — not blanket panels"],
    prevention: ["Daily emollient", "Short lukewarm baths", "Trigger and sweat management", "Vaccination including varicella"],
    medications: [
      {
        class: "Anti-inflammatory topicals then advanced therapy",
        examples: ["Topical corticosteroids", "Topical calcineurin inhibitors", "Crisaborole", "Dupilumab, tralokinumab, JAK inhibitors in moderate–severe"],
        notes: "Wet-wraps for flares. Oral steroids are a last resort because of rebound.",
      },
    ],
    selfCare: ["Moisturize within 3 minutes of bathing", "Keep nails short"],
    seekCare: "Urgent for fever, spreading pus, or painful punched-out sores.",
  }),
  defineDisease({
    id: "urticaria",
    name: "Acute urticaria",
    icd10: "L50.9",
    specialty: "allergy-immunology",
    department: "Allergy / Emergency if anaphylaxis features",
    urgency: "soon",
    setting: "Home/clinic if hives alone; EMS if airway, breathing, or hypotension",
    summary:
      "Transient pruritic wheals from mast-cell activation. Each lesion lasts <24 hours. Anaphylaxis is the emergency overlap — look for stridor, wheeze, vomiting, or collapse.",
    hallmarks: ["hives", "itch"],
    supportive: ["rash", "facial-swelling"],
    occasional: ["wheezing", "nausea", "abdominal-pain"],
    redFlags: ["Throat tightness", "Wheeze", "Hypotension", "Persistent facial swelling"],
    workup: ["Clinical", "Do not routine RAST panels for acute spontaneous urticaria", "Evaluate anaphylaxis if systemic"],
    prevention: ["Avoid known triggers (NSAIDs, specific foods if truly related)", "MedicAlert if anaphylaxis history"],
    medications: [
      {
        class: "Second-generation antihistamine; epinephrine if anaphylaxis",
        examples: ["Cetirizine, loratadine, fexofenadine (can up-dose under clinician advice)", "Intramuscular epinephrine for anaphylaxis", "Short steroid course sometimes used for angioedema"],
        notes: "First-generation antihistamines sedate and are inferior. Epinephrine is not delayed for antihistamines in anaphylaxis.",
      },
    ],
    selfCare: ["Cool compresses", "Avoid alcohol and NSAIDs during a bout if they worsen hives"],
    seekCare: "Call emergency services for breathing difficulty or faintness.",
  }),
  defineDisease({
    id: "anaphylaxis",
    name: "Anaphylaxis",
    icd10: "T78.2XXA",
    specialty: "emergency",
    department: "Emergency / Allergy",
    urgency: "emergency",
    setting: "Emergency medical services now",
    summary:
      "Systemic, potentially fatal hypersensitivity. Skin findings plus respiratory, cardiovascular, or GI involvement after allergen exposure (food, drug, sting). Immediate intramuscular epinephrine is first-line.",
    hallmarks: ["hives", "facial-swelling", "wheezing", "shortness-of-breath", "sweating"],
    supportive: ["nausea", "vomiting", "abdominal-pain", "dizziness", "stridor"],
    occasional: ["syncope", "cyanosis", "diarrhea"],
    vitals: { tachy: true, hypotensive: true, hypoxic: true },
    redFlags: ["Hypotension", "Stridor", "Hypoxia", "Collapse"],
    workup: ["Clinical diagnosis — treat first", "Tryptase timed after the event", "Observe for biphasic reactions"],
    prevention: ["Allergen avoidance", "Two epinephrine autoinjectors always available", "Action plan and training of contacts", "Allergy referral for immunotherapy when indicated (venom)"],
    medications: [
      {
        class: "IM epinephrine then adjuncts",
        examples: ["Epinephrine 0.3–0.5 mg IM anterolateral thigh (adult typical)", "Repeat every 5–15 min if needed", "Albuterol for wheeze", "IV fluids", "Antihistamine and steroid as adjuncts only"],
        notes: "Antihistamines do not treat airway or shock. Lay the person flat (or sit if breathless); do not make them stand.",
      },
    ],
    selfCare: ["Use the autoinjector and call emergency services", "Do not drive yourself"],
    seekCare: "Call emergency services immediately.",
  }),
  defineDisease({
    id: "allergic-rhinitis",
    name: "Allergic rhinitis",
    icd10: "J30.9",
    specialty: "allergy-immunology",
    department: "Allergy / ENT / Primary care",
    urgency: "self-care",
    setting: "Primary care / allergy",
    summary:
      "IgE-mediated nasal inflammation to pollen, dust mite, or dander. Sneezing, itch, clear rhinorrhea, and congestion, often with allergic conjunctivitis and asthma overlap.",
    hallmarks: ["sneezing", "runny-nose", "nasal-congestion", "itch"],
    supportive: ["red-eyes", "fatigue", "cough"],
    occasional: ["wheezing", "sinus-pressure", "loss-of-smell"],
    comorbidBoost: ["asthma"],
    redFlags: ["Unilateral obstruction with blood (tumor/foreign body)", "Wheeze with hypoxia"],
    workup: ["Clinical", "Specific IgE or skin testing when it would change avoidance or immunotherapy"],
    prevention: ["Allergen reduction (mite covers, remain indoors at peak pollen if needed)", "Intranasal steroid before season"],
    medications: [
      {
        class: "Intranasal corticosteroid ± antihistamine",
        examples: ["Fluticasone, budesonide, mometasone nasal", "Cetirizine / loratadine", "Montelukast in selected (psychiatric warning)", "Allergen immunotherapy"],
        notes: "Oral decongestants are cautioned in hypertension. Nasal decongestant sprays rebound after a few days.",
      },
    ],
    selfCare: ["Saline rinses", "Shower after high-pollen days"],
    seekCare: "Allergy clinic if asthma overlap or poor control.",
  }),
  defineDisease({
    id: "asthma-exacerbation",
    name: "Asthma exacerbation",
    icd10: "J45.901",
    specialty: "pulmonology",
    department: "Emergency / Pulmonology / Allergy",
    urgency: "urgent",
    setting: "ED if speaking in words, hypoxic, or not responding to rescue inhaler; otherwise urgent clinic",
    summary:
      "Reversible airway obstruction with wheeze, cough, and chest tightness. Viral infection is the usual trigger. Silent chest and hypoxia are late, dangerous signs.",
    hallmarks: ["wheezing", "shortness-of-breath", "cough", "chest-tightness"],
    supportive: ["cough", "anxiety"],
    occasional: ["fever", "runny-nose"],
    vitals: { tachy: true, hypoxic: true },
    comorbidBoost: ["asthma"],
    redFlags: ["Speaks in words only", "Silent chest", "SpO2 <92%", "Drowsiness", "Rescue inhaler every few minutes without relief"],
    workup: ["Peak flow / spirometry", "Pulse oximetry", "CXR if complication suspected", "ABG if severe"],
    prevention: ["Inhaled corticosteroid controller adherence", "Written action plan", "Vaccination", "Allergen and smoke avoidance", "Review inhaler technique"],
    medications: [
      {
        class: "Rescue bronchodilator, systemic steroid, oxygen; controller step-up",
        examples: ["Albuterol / salbutamol MDI with spacer or nebulizer", "Ipratropium in severe ED care", "Prednisone 5-day burst typical adult", "ICS-formoterol MART regimens per GINA", "Magnesium IV in life-threatening"],
        notes: "Antibiotics are not routine. Repeat short-acting beta-agonist without a controller is a danger sign.",
      },
    ],
    selfCare: ["Sit upright, spacer technique", "Follow the written action plan"],
    seekCare: "Emergency care if no improvement after the action-plan steroid/rescue steps, or if lips are blue.",
  }),
  defineDisease({
    id: "copd-exacerbation",
    name: "COPD exacerbation",
    icd10: "J44.1",
    specialty: "pulmonology",
    department: "Pulmonology / Emergency / Intensive care if hypercapnic",
    urgency: "urgent",
    setting: "ED for hypoxia, hypercapnia, or frailty; otherwise prompt respiratory clinic",
    summary:
      "Acute worsening of chronic airflow obstruction, usually from virus or bacteria. Increased dyspnea, sputum volume or purulence. Respiratory failure can be hypercapnic.",
    hallmarks: ["shortness-of-breath", "wheezing", "productive-cough", "chest-tightness"],
    supportive: ["fatigue", "fever", "edema-legs"],
    occasional: ["confusion", "cyanosis"],
    age: [40, 100],
    vitals: { hypoxic: true, tachy: true },
    comorbidBoost: ["copd", "heart-disease"],
    smokerBoost: true,
    redFlags: ["Drowsiness (CO2 narcosis)", "Cyanosis", "Cor pulmonale decompensation", "Chest pain"],
    workup: ["SpO2, ABG if severe", "CXR", "ECG, troponin if indicated", "CBC, BMP"],
    prevention: ["Smoking cessation", "LAMA/LABA/ICS as phenotyped", "Vaccines (influenza, pneumococcal, RSV, COVID)", "Pulmonary rehab", "Azithromycin chronic in selected frequent exacerbators"],
    medications: [
      {
        class: "Bronchodilators, steroid, targeted antibiotic, NIV if indicated",
        examples: ["Albuterol + ipratropium", "Prednisone 5 days often sufficient", "Amoxicillin or doxycycline if bacterial features", "NIV for pH <7.35 with high CO2"],
        notes: "Target SpO2 88–92% in known CO2 retainers. High-flow oxygen can worsen hypercapnia.",
      },
    ],
    selfCare: ["Pursed-lip breathing", "Do not keep turning oxygen up on your own"],
    seekCare: "ED for worsening work of breathing or confusion.",
  }),
  defineDisease({
    id: "osa",
    name: "Obstructive sleep apnea",
    icd10: "G47.33",
    specialty: "pulmonology",
    department: "Sleep medicine / ENT / Dentistry (oral appliance)",
    urgency: "soon",
    setting: "Sleep clinic; sooner if sleepy driving or uncontrolled AF/resistant HTN",
    summary:
      "Repetitive upper-airway collapse in sleep. Loud snoring, witnessed apneas, unrefreshing sleep, and daytime somnolence. Drives hypertension, AF, crash risk, and pulmonary hypertension.",
    hallmarks: ["snoring", "daytime-sleepiness", "fatigue", "morning-headache"],
    supportive: ["insomnia", "irritability", "nocturia"],
    occasional: ["palpitations", "depressed-mood"],
    age: [25, 90],
    sexBias: "male",
    comorbidBoost: ["hypertension", "heart-disease", "diabetes"],
    redFlags: ["Falling asleep at the wheel", "Unexplained pulmonary hypertension", "Obesity hypoventilation with hypercapnia"],
    workup: ["STOP-BANG / Epworth", "In-lab or home sleep apnea test", "Evaluate for hypothyroidism, residual sleepiness on CPAP"],
    prevention: ["Weight reduction", "Avoid alcohol and sedatives near bedtime", "Lateral sleep", "Treat nasal obstruction"],
    medications: [
      {
        class: "Device therapy is first-line; drugs adjunctive",
        examples: ["CPAP / APAP", "Mandibular advancement device", "Hypoglossal-nerve stimulation in selected", "Modafinil for residual sleepiness after optimized CPAP"],
        notes: "Do not use alcohol as a sleep aid. Driving counseling is mandatory if sleepy.",
      },
    ],
    selfCare: ["Do not drive when sleepy", "Side-sleeping as a bridge"],
    seekCare: "Sleep referral promptly if you have dozed while driving.",
  }),
  defineDisease({
    id: "iron-deficiency",
    name: "Iron-deficiency anemia",
    icd10: "D50.9",
    specialty: "hematology",
    department: "Hematology / GI / Gynecology depending on the source",
    urgency: "soon",
    setting: "Outpatient with source workup; ED if chest pain, syncope, or very low hemoglobin",
    summary:
      "The most common anemia worldwide. Fatigue, exertional dyspnea, pica, restless legs, and pallor. In adults, always ask why — menses, GI blood loss, celiac, or diet — not just replace iron blindly.",
    hallmarks: ["fatigue", "pale-skin", "shortness-of-breath"],
    supportive: ["dizziness", "headache", "hair-loss", "anorexia"],
    occasional: ["chest-pain", "polyphagia"],
    sexBias: "female",
    redFlags: ["Melena", "Syncope", "Ischemic chest pain", "Post-menopausal or male with IDA (colon evaluation)"],
    workup: ["CBC, ferritin, transferrin saturation", "Reticulocyte count", "Screen celiac", "GI endoscopy as indicated", "Gynecologic evaluation"],
    prevention: ["Dietary iron with vitamin C", "Treat menorrhagia", "Colon screening"],
    medications: [
      {
        class: "Iron repletion and source control",
        examples: ["Ferrous sulfate / gluconate / fumarate every other day often better tolerated", "IV iron if intolerant, malabsorption, or late pregnancy", "Tranexamic acid for heavy menses under clinician care"],
        notes: "Do not take iron together with tea, calcium, or PPIs if avoidable. Recheck ferritin after replacement.",
      },
    ],
    selfCare: ["Take iron as directed; stool may darken", "Keep tablets away from children (toxic)"],
    seekCare: "ED for chest pain, black stools, or fainting.",
  }),
  defineDisease({
    id: "b12-deficiency",
    name: "Vitamin B12 deficiency",
    icd10: "D51.9",
    specialty: "hematology",
    department: "Hematology / Neurology / Gastroenterology",
    urgency: "soon",
    setting: "Outpatient; sooner if neurologic deficits",
    summary:
      "Impaired DNA synthesis and demyelination from B12 lack (pernicious anemia, malabsorption, vegan diet, metformin). Megaloblastic anemia, glossitis, and subacute combined degeneration (paresthesia, ataxia).",
    hallmarks: ["fatigue", "pale-skin", "numbness", "tingling", "balance-problems"],
    supportive: ["memory-loss", "sore-throat", "anorexia"],
    occasional: ["depressed-mood", "pale-skin"],
    age: [20, 100],
    redFlags: ["Rapidly progressive gait failure", "Visual loss"],
    workup: ["B12, MMA, homocysteine", "IF antibodies / parietal cell", "CBC smear (macrocytosis)", "Do not give folate alone if B12 is low"],
    prevention: ["B12 supplementation in vegan diets, post-gastrectomy, and some metformin users", "Treat pernicious anemia lifelong"],
    medications: [
      {
        class: "B12 replacement",
        examples: ["IM hydroxocobalamin/cyanocobalamin loading then maintenance", "High-dose oral B12 in selected absorption-intact patients"],
        notes: "Neurologic deficits may take months to recover and can be permanent if delayed. Folate without B12 can worsen neuro injury.",
      },
    ],
    selfCare: ["Do not stop injections in pernicious anemia because the blood count normalized"],
    seekCare: "Urgent neurology if walking is deteriorating.",
  }),
  defineDisease({
    id: "leukemia-suspect",
    name: "Acute leukemia (suspect)",
    icd10: "C95.90",
    specialty: "hematology",
    department: "Hematology-oncology / Emergency",
    urgency: "emergency",
    setting: "Emergency department / tertiary hematology the same day",
    summary:
      "Malignant marrow replacement. Fatigue, pallor, fever, bruising, petechiae, bone pain, and recurrent infection. DIC and leukostasis are immediately life-threatening.",
    hallmarks: ["fatigue", "fever", "bruise-easily", "petechiae", "pale-skin", "bone-pain"],
    supportive: ["night-sweats", "weight-loss", "swollen-lymph", "easy-bleeding"],
    occasional: ["easy-bleeding", "confusion"],
    vitals: { fever: true },
    comorbidBoost: ["immunocompromised", "cancer"],
    redFlags: ["Petechiae with fever", "Bleeding", "Leukostasis (dyspnea, headache)", "Tumor lysis"],
    workup: ["CBC with differential and smear STAT", "Coagulation, uric acid, LDH, CMP, phosphate", "Hematology consult, marrow"],
    prevention: ["No primary prevention for most cases; occupational benzene/radiation protection", "Do not ignore unexplained cytopenias"],
    medications: [
      {
        class: "Specialist induction — not community prescribing",
        examples: ["Supportive transfusions and antibiotics for fever in neutropenia", "Differentiation syndrome precautions in APL (ATRA/ATO — hematology only)"],
        notes: "Fever plus expected neutropenia is an oncologic emergency. Do not start steroids empirically for 'viral illness' if leukemia is possible.",
      },
    ],
    selfCare: ["Go to the ED — do not wait for a clinic slot"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "lymphoma-suspect",
    name: "Lymphoma (suspect)",
    icd10: "C85.90",
    specialty: "hematology",
    department: "Hematology-oncology",
    urgency: "soon",
    setting: "Urgent oncology/hematology; ED if airway compression or SVC syndrome",
    summary:
      "Malignancy of lymphoid tissue. Painless lymphadenopathy, night sweats, fever, weight loss (B symptoms), and sometimes pruritus or alcohol-induced node pain.",
    hallmarks: ["swollen-lymph", "night-sweats", "weight-loss", "fever", "fatigue"],
    supportive: ["itch", "anorexia", "lymphadenopathy"],
    occasional: ["chest-tightness", "cough", "abdominal-pain"],
    vitals: { fever: true },
    redFlags: ["SVC syndrome", "Spinal cord compression", "Airway obstruction"],
    workup: ["Excisional node biopsy (not FNA alone when lymphoma suspected)", "CBC, LDH, HIV, hepatitis", "PET-CT staging by oncology"],
    prevention: ["HIV care reduces some lymphoma risk", "Avoid delay when nodes persist >6 weeks or B symptoms exist"],
    medications: [
      {
        class: "Histology-specific chemoimmunotherapy",
        examples: ["R-CHOP and variants for many B-cell lymphomas", "ABVD-type for Hodgkin", "Novel targeted agents"],
        notes: "Treatment is strictly specialist. Fertility counseling before therapy.",
      },
    ],
    selfCare: ["Photograph node size", "Do not start 'boosting' supplements instead of biopsy"],
    seekCare: "Same-week specialist for persistent nodes with B symptoms; ED for facial swelling or stridor.",
  }),
  defineDisease({
    id: "mdd",
    name: "Major depressive disorder",
    icd10: "F32.9",
    specialty: "psychiatry",
    department: "Primary care / Psychiatry / Crisis services if suicidal",
    urgency: "soon",
    setting: "Primary care or psychiatry; emergency/crisis line if suicidal thoughts",
    summary:
      "Two or more weeks of low mood or anhedonia with sleep, appetite, energy, concentration, or guilt changes that impair function. Medical mimics (thyroid, B12, OSA, substances) should be considered.",
    hallmarks: ["depressed-mood", "anhedonia", "fatigue", "insomnia"],
    supportive: ["anorexia", "weight-loss", "irritability", "memory-loss"],
    occasional: ["anxiety", "headache"],
    redFlags: ["Thoughts of self-harm", "Psychosis", "Inability to care for self"],
    workup: ["Clinical DSM-5-TR interview", "TSH, CBC, B12, substances as indicated", "Safety assessment every visit"],
    prevention: ["Sleep, activity, social connection", "Treat insomnia and pain", "After a first episode, continuation therapy reduces relapse"],
    medications: [
      {
        class: "First-line antidepressant plus psychotherapy",
        examples: ["SSRI (sertraline, escitalopram)", "SNRI (venlafaxine, duloxetine)", "Bupropion", "Mirtazapine", "Evidence-based psychotherapy (CBT, IPT)"],
        notes: "Benefit builds over weeks. Do not stop abruptly. Youth and young adults need suicide-risk monitoring when starting. This app cannot treat crisis — use local emergency services.",
      },
    ],
    selfCare: ["Keep a standing daily routine", "Move your body even a little", "Reach out rather than isolating"],
    seekCare: "If you have thoughts of self-harm, contact emergency services or a crisis line now. Otherwise, book primary care/psychiatry this week.",
  }),
  defineDisease({
    id: "gad",
    name: "Generalized anxiety disorder",
    icd10: "F41.1",
    specialty: "psychiatry",
    department: "Primary care / Psychiatry / Psychology",
    urgency: "routine",
    setting: "Outpatient; ED only for panic mimics of ACS or if suicidal",
    summary:
      "Excessive, hard-to-control worry on most days for months, with restlessness, muscle tension, sleep disruption, and irritability. Medical evaluation excludes hyperthyroidism and stimulant excess.",
    hallmarks: ["anxiety", "insomnia", "fatigue", "irritability", "muscle-aches"],
    supportive: ["headache", "palpitations", "nausea"],
    occasional: ["dizziness", "chest-tightness"],
    redFlags: ["Chest pain with exertional features", "Suicidal thoughts", "Substance withdrawal"],
    workup: ["Clinical", "TSH, CBC as indicated", "ECG if palpitations/chest pain"],
    prevention: ["Limit caffeine and alcohol", "Sleep schedule", "CBT skills (worry time, exposure)"],
    medications: [
      {
        class: "SSRI/SNRI first-line; CBT; avoid long-term benzodiazepines as monotherapy",
        examples: ["Escitalopram", "Sertraline", "Venlafaxine", "Buspirone", "Short-term benzo only in selected, supervised settings"],
        notes: "Benzodiazepines cause dependence and falls. Therapy is as effective as medication for many people.",
      },
    ],
    selfCare: ["Reduce caffeine", "Breathing and activity", "Delay the 3 a.m. catastrophic search"],
    seekCare: "Clinic this week; ED if you believe you are having a heart attack — chest pain still needs an ECG.",
  }),
  defineDisease({
    id: "panic-attack",
    name: "Panic attack / panic disorder",
    icd10: "F41.0",
    specialty: "psychiatry",
    department: "Emergency (first rule-out) / Psychiatry",
    urgency: "soon",
    setting: "ED for first episode with chest pain or dyspnea; psychiatry for recurrent attacks",
    summary:
      "Abrupt surge of fear with palpitations, sweating, tremor, shortness of breath, and fear of dying, peaking within minutes. First episodes are evaluated to exclude ACS, PE, arrhythmia, and thyrotoxicosis.",
    hallmarks: ["panic", "palpitations", "sweating", "shortness-of-breath", "chest-tightness", "dizziness"],
    supportive: ["nausea", "tremor", "numbness", "chest-tightness"],
    occasional: ["syncope"],
    vitals: { tachy: true },
    redFlags: ["True syncope", "Hypoxia", "Exertional chest pressure", "Focal neurology"],
    workup: ["ECG, trop if indicated", "TSH, CBC, CMP", "D-dimer/CTA only if PE features", "Clinical panic diagnosis after mimics addressed"],
    prevention: ["CBT with interoceptive exposure", "Reduce caffeine", "Treat OSA and thyroid disease"],
    medications: [
      {
        class: "SSRI for panic disorder; benzodiazepine only short-bridge",
        examples: ["Sertraline", "Paroxetine (more withdrawal)", "Venlafaxine", "Propranolol is not first-line for panic disorder"],
        notes: "A normal ECG does not make the distress 'fake' — it still deserves treatment. Avoid daily benzodiazepines.",
      },
    ],
    selfCare: ["Grounding, slow exhalation", "Do not hyperventilate into a bag as a plan of record"],
    seekCare: "ED for first severe episode with chest pain; clinic for a prevention plan.",
  }),
  defineDisease({
    id: "pid",
    name: "Pelvic inflammatory disease",
    icd10: "N73.9",
    specialty: "gynecology",
    department: "Gynecology / Emergency / Sexual health",
    urgency: "urgent",
    setting: "Urgent gyn / ED; hospitalize if pregnant, tubo-ovarian abscess, or unable to take oral therapy",
    summary:
      "Infection of the upper genital tract, usually STIs (gonorrhea, chlamydia) ± anaerobes. Pelvic pain, fever, discharge, and cervical motion tenderness. Infertility and ectopic pregnancy are sequelae.",
    hallmarks: ["pelvic-pain", "fever", "vaginal-discharge", "painful-intercourse"],
    supportive: ["dysuria", "nausea", "vaginal-bleeding"],
    occasional: ["ruq-pain", "vomiting"],
    age: [14, 45],
    sexBias: "female",
    vitals: { fever: true },
    pregnancyRisk: true,
    redFlags: ["Pregnancy (ectopic overlap)", "Peritonitis", "Sepsis", "TOA"],
    workup: ["Pregnancy test first", "NAAT for GC/CT, wet mount", "CBC, CRP", "Pelvic ultrasound if abscess or ectopic possible"],
    prevention: ["Condoms", "Screening for GC/CT in young and high-risk people", "Treat partners", "Do not douche"],
    medications: [
      {
        class: "Combination antibiotics covering GC, CT, and anaerobes",
        examples: ["Ceftriaxone IM plus doxycycline plus metronidazole (typical outpatient)", "IV cefoxitin or ceftriaxone-based inpatient regimens"],
        notes: "Partners need treatment. Abstain until therapy complete. IUDs are not automatically removed.",
      },
    ],
    selfCare: ["Partner notification", "Analgesia, rest"],
    seekCare: "Same day; ED if pregnant or vomiting.",
  }),
  defineDisease({
    id: "ectopic-pregnancy",
    name: "Ectopic pregnancy (suspect)",
    icd10: "O00.90",
    specialty: "gynecology",
    department: "Emergency / Gynecology — rupture is hemorrhagic shock",
    urgency: "emergency",
    setting: "Emergency department now",
    summary:
      "Implantation outside the uterus, usually tubal. First-trimester pain and bleeding, shoulder-tip pain, and syncope if rupture. Any woman of childbearing potential with abdominal pain needs a pregnancy test.",
    hallmarks: ["pelvic-pain", "missed-period", "abdominal-pain", "dizziness"],
    supportive: ["vaginal-bleeding", "nausea", "shoulder-tip-pain"],
    occasional: ["syncope", "rebound-pain"],
    age: [14, 45],
    sexBias: "female",
    pregnancyRisk: true,
    vitals: { tachy: true, hypotensive: true },
    redFlags: ["Syncope", "Shoulder-tip pain", "Peritonitis", "Positive pregnancy test with empty uterus"],
    workup: ["STAT urine/serum hCG", "Transvaginal ultrasound", "CBC, blood type and screen", "Rhogam if Rh-negative"],
    prevention: ["Treat PID", "Smoking cessation", "Counsel after prior ectopic"],
    medications: [
      {
        class: "Methotrexate in selected stable unruptured cases, otherwise surgery",
        examples: ["IM methotrexate with hCG follow-up", "Laparoscopic salpingectomy/ostomy", "Transfusion if ruptured"],
        notes: "Methotrexate requires reliable follow-up and contraindications review (renal, rupture, high hCG, fetal cardiac activity thresholds).",
      },
    ],
    selfCare: ["Do not wait at home with a positive test and severe one-sided pain"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "dysmenorrhea",
    name: "Primary dysmenorrhea / endometriosis spectrum",
    icd10: "N94.6",
    specialty: "gynecology",
    department: "Gynecology / Primary care",
    urgency: "routine",
    setting: "Primary care / gyn; sooner if infertility or missed school/work monthly",
    summary:
      "Cramping pelvic pain with menses. Primary dysmenorrhea is prostaglandin-mediated; endometriosis adds deep pain, dyspareunia, and sometimes infertility. Both are treatable — pain is not 'just periods.'",
    hallmarks: ["painful-menses", "pelvic-pain"],
    supportive: ["nausea", "diarrhea", "headache", "painful-intercourse"],
    occasional: ["fatigue", "constipation", "back-pain"],
    age: [12, 50],
    sexBias: "female",
    redFlags: ["Sudden severe pain mid-cycle with collapse (ruptured cyst/torsion)", "Fever (PID)", "Positive pregnancy test"],
    workup: ["History, pelvic exam as appropriate", "Pregnancy test", "Ultrasound", "Laparoscopy is diagnostic for endometriosis when indicated"],
    prevention: ["Combined hormonal contraception or LNG-IUD as suppression", "NSAIDs started at onset or the day before"],
    medications: [
      {
        class: "NSAID plus hormonal suppression; GnRH analogues / surgery for refractory endometriosis",
        examples: ["Ibuprofen, naproxen", "Combined oral contraceptive, patch, ring", "Levonorgestrel IUD", "Norethindrone", "GnRH antagonist add-back in specialist care"],
        notes: "Do not delay specialist referral if pain is monthly-disabling.",
      },
    ],
    selfCare: ["Heat, movement", "Start NSAID with the first cramp if safe"],
    seekCare: "Urgent if pain is sudden and severe, or you could be pregnant.",
  }),
  defineDisease({
    id: "perimenopause",
    name: "Perimenopause / menopausal transition",
    icd10: "N95.1",
    specialty: "gynecology",
    department: "Gynecology / Primary care / Menopause clinic",
    urgency: "routine",
    setting: "Primary care / menopause clinic",
    summary:
      "Ovarian function fluctuation typically in the 40s–50s. Irregular menses, vasomotor flushes, sleep disruption, vaginal dryness, and mood change. Postmenopausal bleeding is never assumed to be 'hormones' without evaluation.",
    hallmarks: ["heat-intolerance", "sweating", "insomnia", "irritability"],
    supportive: ["fatigue", "anxiety", "painful-intercourse", "weight-gain"],
    occasional: ["palpitations", "depressed-mood", "joint-pain"],
    age: [40, 60],
    sexBias: "female",
    redFlags: ["Bleeding after 12 months amenorrhea", "Chest pain", "Depression with self-harm thoughts"],
    workup: ["Clinical diagnosis; FSH not required in typical age", "TSH", "Evaluate AUB per gyn pathways", "Bone density later as indicated"],
    prevention: ["Weight-bearing exercise", "Calcium/vitamin D sufficiency", "Smoking cessation", "Treat GSM to prevent UTIs and sexual pain"],
    medications: [
      {
        class: "Menopausal hormone therapy when indicated; non-hormonal alternatives",
        examples: ["Transdermal estradiol plus progestogen if uterus in situ", "Micronized progesterone", "SSRI/SNRI or fezolinetant for vasomotor symptoms", "Vaginal estrogen for GSM"],
        notes: "MHT is individualized for timing, clot/breast-cancer risk, and goals. Compounded 'bioidentical' mixes are not first-line.",
      },
    ],
    selfCare: ["Cool sleeping environment", "Pelvic floor PT for pain", "Strength training"],
    seekCare: "Prompt gyn for postmenopausal bleeding.",
  }),
  defineDisease({
    id: "testicular-torsion",
    name: "Testicular torsion (suspect)",
    icd10: "N44.00",
    specialty: "urology",
    department: "Emergency / Urology — hours of ischemia",
    urgency: "emergency",
    setting: "Emergency department now — do not wait for morning clinic",
    summary:
      "Twisting of the spermatic cord cutting off testicular blood flow. Sudden severe unilateral pain, nausea, high-riding testis, and absent cremasteric reflex, often in adolescents. Salvage falls after ~6 hours.",
    hallmarks: ["testicular-pain", "nausea", "vomiting"],
    supportive: ["abdominal-pain", "sweating"],
    occasional: ["fever"],
    age: [8, 30],
    sexBias: "male",
    redFlags: ["Sudden severe testicular pain", "Vomiting", "High-riding testis"],
    workup: ["Immediate urology — Doppler ultrasound must not delay surgery if suspicion is high"],
    prevention: ["Orchiopexy of the contralateral testis after an event", "Do not ignore 'intermittent' torsion pain"],
    medications: [
      {
        class: "Emergency surgery, not antibiotics first",
        examples: ["Manual detorsion as a bridge if a urologist directs", "Bilateral orchiopexy"],
        notes: "Assuming epididymitis and sending home a teen with sudden pain is a classic pitfall.",
      },
    ],
    selfCare: ["Go to the ED immediately"],
    seekCare: "Emergency department now.",
  }),
  defineDisease({
    id: "kawasaki",
    name: "Kawasaki disease (suspect)",
    icd10: "M30.3",
    specialty: "pediatrics",
    department: "Pediatric emergency / Pediatric rheumatology / Cardiology",
    urgency: "emergency",
    setting: "Pediatric hospital — coronary risk",
    summary:
      "Medium-vessel vasculitis of young children. ≥5 days of fever plus conjunctivitis, oral changes, rash, extremity edema, and cervical nodes. Untreated, coronary aneurysms can form.",
    hallmarks: ["fever", "rash", "red-eyes", "swollen-lymph"],
    supportive: ["irritability", "oral-ulcers", "skin-redness"],
    occasional: ["diarrhea", "joint-pain"],
    age: [0, 8],
    vitals: { fever: true, highFever: true, tachy: true },
    redFlags: ["Fever ≥5 days with mucocutaneous signs", "Shock (atypical Kawasaki / MAS)"],
    workup: ["CBC, CRP/ESR, albumin, LFTs", "Echocardiogram", "Incomplete Kawasaki criteria in infants"],
    prevention: ["No known primary prevention; early IVIG prevents coronary complications"],
    medications: [
      {
        class: "IVIG plus aspirin, then cardiology follow-up",
        examples: ["IV immunoglobulin 2 g/kg", "High then low-dose aspirin per protocol", "Infliximab or steroids for IVIG resistance"],
        notes: "Delaying IVIG past day 10 raises coronary risk. Live vaccines delayed after IVIG.",
      },
    ],
    selfCare: ["Do not wait out a week of high fever in a toddler with red eyes and rash"],
    seekCare: "Pediatric emergency department.",
  }),
  defineDisease({
    id: "heat-illness",
    name: "Heat exhaustion / heat stroke spectrum",
    icd10: "T67.5XXA",
    specialty: "emergency",
    department: "Emergency / Sports medicine / Occupational",
    urgency: "emergency",
    setting: "Emergency care; heat stroke is cooled immediately",
    summary:
      "Heat exhaustion: heavy sweating, nausea, dizziness, and tachycardia after exertion or hot environments. Heat stroke: CNS change and very high core temperature — a true emergency with multi-organ risk.",
    hallmarks: ["sweating", "dizziness", "nausea", "fatigue", "headache"],
    supportive: ["vomiting", "muscle-aches", "thirst"],
    occasional: ["confusion", "syncope", "seizure"],
    vitals: { tachy: true, highFever: true, hypotensive: true },
    redFlags: ["Confusion or collapse (heat stroke)", "Hot dry skin is not required to diagnose heat stroke", "Seizure"],
    workup: ["Core temperature", "CBC, CMP, CK, coagulation, glucose", "Cool first, then labs"],
    prevention: ["Acclimatization", "Scheduled hydration", "Rest in shade", "Never leave children or older adults in cars", "Caution with anticholinergics, diuretics, and MDMA"],
    medications: [
      {
        class: "Cooling and support — no antipyretic for heat stroke",
        examples: ["Ice-water immersion for exertional heat stroke", "IV fluids", "Benzodiazepines for shivering/seizure"],
        notes: "Acetaminophen does not treat heat stroke. Delay in cooling worsens outcome more than delay in transport.",
      },
    ],
    selfCare: ["Move to shade, oral fluids if fully conscious", "Stop work/exercise"],
    seekCare: "Emergency services if confused, collapsing, or not improving after cooling.",
  }),
  defineDisease({
    id: "dehydration",
    name: "Volume depletion / dehydration",
    icd10: "E86.0",
    specialty: "general-medicine",
    department: "Emergency if severe; primary care if mild",
    urgency: "soon",
    setting: "Home ORS if mild; ED if orthostatic, anuric, or confused",
    summary:
      "Net loss of water and sodium from GI losses, fever, or poor intake. Thirst, dry mucosa, oliguria, tachycardia, and in severe cases shock and AKI.",
    hallmarks: ["thirst", "dehydration", "dizziness", "fatigue", "low-urine"],
    supportive: ["malaise", "headache", "nausea"],
    occasional: ["confusion", "syncope"],
    vitals: { tachy: true, hypotensive: true },
    comorbidBoost: ["kidney-disease", "diabetes"],
    redFlags: ["No urine", "Confusion", "Inability to drink", "Infants with sunken fontanelle"],
    workup: ["Orthostatics", "BMP, bicarbonate", "Glucose", "Source of losses"],
    prevention: ["ORS during gastroenteritis", "Sick-day fluids", "Careful diuretic use in heat"],
    medications: [
      {
        class: "Oral rehydration or IV crystalloid",
        examples: ["WHO ORS", "Isotonic saline IV if shock", "Potassium repletion as labs indicate"],
        notes: "Sports drinks are not equivalent to ORS in cholera-range losses. Hyponatremia needs measured correction.",
      },
    ],
    selfCare: ["Small frequent ORS sips", "Avoid plain water only if large diarrheal losses (need sodium)"],
    seekCare: "ED if you cannot keep fluids down or feel faint standing.",
  }),
];
