import type { BodySystem, Symptom } from "./types";

export const SYSTEM_LABEL: Record<BodySystem, string> = {
  constitutional: "Constitutional",
  heent: "Head, eyes, ears, nose, throat",
  respiratory: "Respiratory",
  cardiovascular: "Cardiovascular",
  gastrointestinal: "Gastrointestinal",
  genitourinary: "Genitourinary",
  musculoskeletal: "Musculoskeletal",
  neurologic: "Neurologic",
  skin: "Skin",
  psychiatric: "Mood and mind",
  endocrine: "Endocrine / metabolic",
  hematologic: "Blood and lymph",
};

export const SYMPTOMS: Symptom[] = [
  // Constitutional
  { id: "fever", name: "Fever", system: "constitutional", hint: "Felt hot, measured ≥38°C" },
  { id: "chills", name: "Chills or rigors", system: "constitutional" },
  { id: "night-sweats", name: "Night sweats", system: "constitutional", hint: "Drenching, change of clothes" },
  { id: "fatigue", name: "Fatigue", system: "constitutional" },
  { id: "malaise", name: "Malaise / feeling unwell", system: "constitutional" },
  { id: "anorexia", name: "Loss of appetite", system: "constitutional" },
  { id: "weight-loss", name: "Unintentional weight loss", system: "constitutional" },
  { id: "weight-gain", name: "Unintentional weight gain", system: "constitutional" },
  { id: "thirst", name: "Excessive thirst", system: "constitutional" },
  { id: "dehydration", name: "Dry mouth or poor urine output", system: "constitutional" },
  { id: "sweating", name: "Profuse sweating", system: "constitutional", redFlag: true },
  { id: "restlessness", name: "Can't sit still / agitation", system: "constitutional" },
  { id: "salt-craving", name: "Craving salt", system: "constitutional" },
  { id: "metallic-taste", name: "Metallic taste", system: "constitutional" },

  // HEENT
  { id: "headache", name: "Headache", system: "heent" },
  { id: "worst-headache", name: "Sudden worst-ever headache", system: "heent", redFlag: true },
  { id: "sore-throat", name: "Sore throat", system: "heent" },
  { id: "runny-nose", name: "Runny nose", system: "heent" },
  { id: "nasal-congestion", name: "Nasal congestion", system: "heent" },
  { id: "sinus-pressure", name: "Sinus pressure or facial pain", system: "heent" },
  { id: "sneezing", name: "Sneezing", system: "heent" },
  { id: "ear-pain", name: "Ear pain", system: "heent" },
  { id: "hearing-loss", name: "Hearing loss", system: "heent" },
  { id: "tinnitus", name: "Ringing in the ears", system: "heent" },
  { id: "ear-fullness", name: "Ear fullness or pressure", system: "heent" },
  { id: "red-eyes", name: "Red eyes", system: "heent" },
  { id: "eye-pain", name: "Eye pain", system: "heent", redFlag: true },
  { id: "eye-discharge", name: "Eye discharge or crusting", system: "heent" },
  { id: "photophobia", name: "Light sensitivity", system: "heent" },
  { id: "vision-loss", name: "Sudden vision loss", system: "heent", redFlag: true },
  { id: "double-vision", name: "Double vision", system: "heent", redFlag: true },
  { id: "blurred-vision", name: "Blurred vision", system: "heent" },
  { id: "floaters-flash", name: "New floaters or flashes of light", system: "heent", redFlag: true },
  { id: "seeing-halos", name: "Halos around lights", system: "heent" },
  { id: "curtain-vision", name: "Curtain or shadow over vision", system: "heent", redFlag: true },
  { id: "hoarseness", name: "Hoarseness", system: "heent" },
  { id: "oral-ulcers", name: "Mouth ulcers", system: "heent" },
  { id: "loss-of-smell", name: "Loss of smell or taste", system: "heent" },
  { id: "neck-stiffness", name: "Neck stiffness", system: "heent", redFlag: true },
  { id: "swollen-lymph", name: "Swollen lymph nodes", system: "heent" },
  { id: "facial-swelling", name: "Facial or lip swelling", system: "heent", redFlag: true },
  { id: "toothache", name: "Tooth or jaw pain", system: "heent" },
  { id: "stridor", name: "Noisy breathing (stridor)", system: "heent", redFlag: true },
  { id: "muffled-voice", name: "Hot-potato / muffled voice", system: "heent", redFlag: true },
  { id: "drooling", name: "Drooling / can't swallow saliva", system: "heent", redFlag: true },
  { id: "epistaxis", name: "Nosebleed", system: "heent" },
  { id: "jaw-claudication", name: "Jaw pain when chewing", system: "heent", redFlag: true },
  { id: "scalp-tenderness", name: "Tender scalp or temple", system: "heent", redFlag: true },
  { id: "dry-eyes", name: "Very dry eyes or mouth", system: "heent" },
  { id: "ptosis", name: "Drooping eyelid", system: "heent" },

  // Respiratory
  { id: "cough", name: "Cough", system: "respiratory" },
  { id: "dry-cough", name: "Dry cough", system: "respiratory" },
  { id: "productive-cough", name: "Cough with phlegm", system: "respiratory" },
  { id: "hemoptysis", name: "Coughing up blood", system: "respiratory", redFlag: true },
  { id: "shortness-of-breath", name: "Shortness of breath", system: "respiratory", redFlag: true },
  { id: "wheezing", name: "Wheezing", system: "respiratory" },
  { id: "chest-tightness", name: "Chest tightness", system: "respiratory" },
  { id: "orthopnea", name: "Breathlessness when lying flat", system: "respiratory" },
  { id: "pnd", name: "Waking at night short of breath", system: "respiratory" },
  { id: "pleuritic-pain", name: "Sharp pain with breathing", system: "respiratory" },
  { id: "snoring", name: "Loud snoring / witnessed apneas", system: "respiratory" },
  { id: "sore-chest-cough", name: "Chest sore from coughing", system: "respiratory" },
  { id: "whoop", name: "Whooping or coughing spells then gasp", system: "respiratory" },
  { id: "rusty-sputum", name: "Rusty or bloody-tinged sputum", system: "respiratory" },
  { id: "kussmaul", name: "Deep, rapid (Kussmaul) breathing", system: "respiratory", redFlag: true },
  { id: "morning-headache", name: "Morning headaches with snoring", system: "respiratory" },

  // Cardiovascular
  { id: "chest-pain", name: "Chest pain or pressure", system: "cardiovascular", redFlag: true },
  { id: "palpitations", name: "Palpitations", system: "cardiovascular" },
  { id: "edema-legs", name: "Swollen ankles or legs", system: "cardiovascular" },
  { id: "syncope", name: "Fainting or near-fainting", system: "cardiovascular", redFlag: true },
  { id: "claudication", name: "Leg pain when walking", system: "cardiovascular" },
  { id: "calf-swelling", name: "One-sided calf swelling", system: "cardiovascular", redFlag: true },
  { id: "irregular-heartbeat", name: "Irregular heartbeat", system: "cardiovascular" },
  { id: "cyanosis", name: "Blue lips or fingers", system: "cardiovascular", redFlag: true },
  { id: "radiating-arm", name: "Pain radiating to arm, jaw, or back", system: "cardiovascular", redFlag: true },
  { id: "raynaud", name: "Fingers turn white/blue in the cold", system: "cardiovascular" },
  { id: "shoulder-tip-pain", name: "Shoulder-tip pain", system: "cardiovascular", redFlag: true },

  // GI
  { id: "nausea", name: "Nausea", system: "gastrointestinal" },
  { id: "vomiting", name: "Vomiting", system: "gastrointestinal" },
  { id: "diarrhea", name: "Diarrhea", system: "gastrointestinal" },
  { id: "constipation", name: "Constipation", system: "gastrointestinal" },
  { id: "abdominal-pain", name: "Abdominal pain", system: "gastrointestinal" },
  { id: "epigastric-pain", name: "Upper-middle abdominal pain", system: "gastrointestinal" },
  { id: "ruq-pain", name: "Right-upper abdominal pain", system: "gastrointestinal" },
  { id: "rlq-pain", name: "Right-lower abdominal pain", system: "gastrointestinal", redFlag: true },
  { id: "llq-pain", name: "Left-lower abdominal pain", system: "gastrointestinal" },
  { id: "bloating", name: "Bloating", system: "gastrointestinal" },
  { id: "heartburn", name: "Heartburn / acid reflux", system: "gastrointestinal" },
  { id: "dysphagia", name: "Difficulty swallowing", system: "gastrointestinal" },
  { id: "odynophagia", name: "Painful swallowing", system: "gastrointestinal" },
  { id: "blood-stool", name: "Blood in stool", system: "gastrointestinal", redFlag: true },
  { id: "black-stool", name: "Black, tarry stools", system: "gastrointestinal", redFlag: true },
  { id: "coffee-ground", name: "Coffee-ground vomit", system: "gastrointestinal", redFlag: true },
  { id: "jaundice", name: "Yellow skin or eyes", system: "gastrointestinal", redFlag: true },
  { id: "vomiting-blood", name: "Vomiting blood", system: "gastrointestinal", redFlag: true },
  { id: "food-intolerance", name: "Food-related bloating or diarrhea", system: "gastrointestinal" },
  { id: "anal-pain", name: "Rectal pain", system: "gastrointestinal" },
  { id: "rebound-pain", name: "Abdomen rigid or worse with movement", system: "gastrointestinal", redFlag: true },
  { id: "pale-stool", name: "Pale or clay-colored stools", system: "gastrointestinal" },
  { id: "dark-urine", name: "Dark tea-colored urine", system: "gastrointestinal" },
  { id: "early-satiety", name: "Feeling full after a few bites", system: "gastrointestinal" },
  { id: "change-bowel", name: "Change in bowel habit", system: "gastrointestinal" },
  { id: "tenesmus", name: "Urgency to pass stool with little result", system: "gastrointestinal" },
  { id: "mucus-stool", name: "Mucus in stool", system: "gastrointestinal" },
  { id: "fatty-food-intolerance", name: "Pain after fatty meals", system: "gastrointestinal" },
  { id: "postprandial-pain", name: "Pain after eating", system: "gastrointestinal" },
  { id: "cannot-get-comfortable", name: "Can't find a comfortable position", system: "gastrointestinal", redFlag: true },

  // GU
  { id: "dysuria", name: "Burning with urination", system: "genitourinary" },
  { id: "frequency", name: "Urinating often", system: "genitourinary" },
  { id: "urgency", name: "Sudden urge to urinate", system: "genitourinary" },
  { id: "hematuria", name: "Blood in urine", system: "genitourinary", redFlag: true },
  { id: "flank-pain", name: "Flank or kidney-angle pain", system: "genitourinary" },
  { id: "pelvic-pain", name: "Pelvic pain", system: "genitourinary" },
  { id: "vaginal-discharge", name: "Abnormal vaginal discharge", system: "genitourinary" },
  { id: "testicular-pain", name: "Testicular pain", system: "genitourinary", redFlag: true },
  { id: "incontinence", name: "Urinary incontinence", system: "genitourinary" },
  { id: "nocturia", name: "Waking at night to urinate", system: "genitourinary" },
  { id: "low-urine", name: "Very little urine", system: "genitourinary", redFlag: true },
  { id: "missed-period", name: "Missed or late period", system: "genitourinary" },
  { id: "heavy-menses", name: "Heavy menstrual bleeding", system: "genitourinary" },
  { id: "painful-menses", name: "Painful periods", system: "genitourinary" },
  { id: "painful-intercourse", name: "Pain with intercourse", system: "genitourinary" },
  { id: "vaginal-bleeding", name: "Unexpected vaginal bleeding", system: "genitourinary", redFlag: true },
  { id: "postmenopausal-bleeding", name: "Bleeding after menopause", system: "genitourinary", redFlag: true },
  { id: "urethral-discharge", name: "Discharge from the urethra", system: "genitourinary" },
  { id: "genital-ulcers", name: "Genital sores or ulcers", system: "genitourinary" },
  { id: "urinary-retention", name: "Cannot pass urine", system: "genitourinary", redFlag: true },
  { id: "hesitancy", name: "Hesitancy starting the stream", system: "genitourinary" },
  { id: "weak-stream", name: "Weak urinary stream", system: "genitourinary" },
  { id: "foamy-urine", name: "Foamy or frothy urine", system: "genitourinary" },
  { id: "radiation-groin", name: "Pain shooting to the groin", system: "genitourinary" },
  { id: "breast-lump", name: "Breast lump", system: "genitourinary", redFlag: true },

  // MSK
  { id: "joint-pain", name: "Joint pain", system: "musculoskeletal" },
  { id: "joint-swelling", name: "Joint swelling", system: "musculoskeletal" },
  { id: "morning-stiffness", name: "Morning stiffness >30 minutes", system: "musculoskeletal" },
  { id: "back-pain", name: "Low back pain", system: "musculoskeletal" },
  { id: "neck-pain", name: "Neck pain", system: "musculoskeletal" },
  { id: "muscle-aches", name: "Muscle aches", system: "musculoskeletal" },
  { id: "muscle-weakness", name: "Muscle weakness", system: "musculoskeletal" },
  { id: "sciatica", name: "Pain shooting down a leg", system: "musculoskeletal" },
  { id: "bone-pain", name: "Deep bone pain", system: "musculoskeletal" },
  { id: "limited-motion", name: "Stiff or limited joint motion", system: "musculoskeletal" },
  { id: "shoulder-hip-stiffness", name: "Shoulder or hip girdle stiffness", system: "musculoskeletal" },
  { id: "calf-cramps", name: "Calf cramps", system: "musculoskeletal" },
  { id: "hot-swollen-joint", name: "One joint red-hot and swollen", system: "musculoskeletal", redFlag: true },
  { id: "inability-bear-weight", name: "Cannot bear weight on a limb", system: "musculoskeletal", redFlag: true },
  { id: "night-back-pain", name: "Back pain that wakes you at night", system: "musculoskeletal" },
  { id: "dactylitis", name: "Sausage finger or toe", system: "musculoskeletal" },
  { id: "proximal-weakness", name: "Trouble rising from a chair or combing hair", system: "musculoskeletal" },

  // Neurologic
  { id: "dizziness", name: "Dizziness", system: "neurologic" },
  { id: "vertigo", name: "Spinning vertigo", system: "neurologic" },
  { id: "numbness", name: "Numbness", system: "neurologic" },
  { id: "tingling", name: "Tingling", system: "neurologic" },
  { id: "weakness-one-side", name: "Weakness on one side", system: "neurologic", redFlag: true },
  { id: "facial-droop", name: "Facial droop", system: "neurologic", redFlag: true },
  { id: "speech-difficulty", name: "Trouble speaking or finding words", system: "neurologic", redFlag: true },
  { id: "confusion", name: "Confusion or altered mental state", system: "neurologic", redFlag: true },
  { id: "seizure", name: "Seizure", system: "neurologic", redFlag: true },
  { id: "tremor", name: "Tremor", system: "neurologic" },
  { id: "memory-loss", name: "Memory trouble", system: "neurologic" },
  { id: "aura", name: "Visual aura before headache", system: "neurologic" },
  { id: "insomnia", name: "Insomnia", system: "neurologic" },
  { id: "daytime-sleepiness", name: "Daytime sleepiness", system: "neurologic" },
  { id: "balance-problems", name: "Unsteady gait or balance problems", system: "neurologic" },
  { id: "loss-of-consciousness", name: "Loss of consciousness", system: "neurologic", redFlag: true },
  { id: "saddle-numbness", name: "Numbness in the saddle / groin area", system: "neurologic", redFlag: true },
  { id: "ascending-weakness", name: "Weakness climbing from the feet up", system: "neurologic", redFlag: true },
  { id: "fatigable-weakness", name: "Weakness that worsens as the day goes on", system: "neurologic" },
  { id: "bilateral-leg-weakness", name: "Both legs weak", system: "neurologic", redFlag: true },
  { id: "fluctuating-confusion", name: "Alertness that waxes and wanes", system: "neurologic", redFlag: true },
  { id: "shuffling-gait", name: "Shuffling, stooped walk", system: "neurologic" },
  { id: "rest-tremor", name: "Tremor at rest (pill-rolling)", system: "neurologic" },
  { id: "burning-feet", name: "Burning pain in the feet", system: "neurologic" },
  { id: "electric-spine", name: "Electric shock down the spine on neck flexion", system: "neurologic" },

  // Skin
  { id: "rash", name: "Rash", system: "skin" },
  { id: "itch", name: "Itching", system: "skin" },
  { id: "hives", name: "Hives", system: "skin" },
  { id: "skin-redness", name: "Spreading skin redness", system: "skin" },
  { id: "skin-warmth", name: "Hot, tender skin", system: "skin" },
  { id: "blisters", name: "Blisters", system: "skin" },
  { id: "dermatomal-rash", name: "Painful rash in a stripe", system: "skin" },
  { id: "target-lesion", name: "Bull's-eye or target skin lesion", system: "skin" },
  { id: "pale-skin", name: "Pale skin or inner eyelids", system: "skin" },
  { id: "bruise-easily", name: "Bruises easily", system: "skin" },
  { id: "petechiae", name: "Tiny pinpoint spots on skin", system: "skin", redFlag: true },
  { id: "jaundice-skin", name: "Yellowing of the skin", system: "skin", redFlag: true },
  { id: "wound", name: "Red, draining wound", system: "skin" },
  { id: "malar-rash", name: "Butterfly rash across the cheeks", system: "skin" },
  { id: "photosensitivity", name: "Rash after sun exposure", system: "skin" },
  { id: "mole-change", name: "Changing mole or new dark spot", system: "skin" },
  { id: "nonhealing-sore", name: "Sore that will not heal", system: "skin" },
  { id: "peeling-skin", name: "Skin peeling on hands or feet", system: "skin" },
  { id: "strawberry-tongue", name: "Strawberry-red tongue", system: "skin" },
  { id: "pruritus-after-water", name: "Itching after a hot bath", system: "skin" },
  { id: "periorbital-edema", name: "Puffy eyelids in the morning", system: "skin" },
  { id: "nail-pitting", name: "Pitted nails", system: "skin" },
  { id: "dry-skin", name: "Very dry, coarse skin", system: "skin" },
  { id: "hyperpigmentation", name: "New dark skin creases or tanning", system: "skin" },
  { id: "purple-striae", name: "Purple stretch marks", system: "skin" },

  // Psychiatric
  { id: "anxiety", name: "Anxiety", system: "psychiatric" },
  { id: "depressed-mood", name: "Low mood", system: "psychiatric" },
  { id: "anhedonia", name: "Loss of interest or pleasure", system: "psychiatric" },
  { id: "panic", name: "Sudden panic attacks", system: "psychiatric" },
  { id: "irritability", name: "Irritability", system: "psychiatric" },
  { id: "hallucinations", name: "Seeing or hearing things others do not", system: "psychiatric", redFlag: true },
  {
    id: "suicidal-thoughts",
    name: "Thoughts of self-harm",
    system: "psychiatric",
    redFlag: true,
    hint: "If present, skip the checker and use crisis resources immediately",
  },
  { id: "mania", name: "Need little sleep, racing thoughts, grand plans", system: "psychiatric", redFlag: true },
  { id: "flashbacks", name: "Flashbacks or reliving trauma", system: "psychiatric" },
  { id: "agitation", name: "Severe agitation", system: "psychiatric", redFlag: true },
  { id: "postpartum-mood", name: "Low mood after childbirth", system: "psychiatric", redFlag: true },

  // Endocrine
  { id: "heat-intolerance", name: "Heat intolerance", system: "endocrine" },
  { id: "cold-intolerance", name: "Cold intolerance", system: "endocrine" },
  { id: "hair-loss", name: "Hair thinning or loss", system: "endocrine" },
  { id: "polyuria", name: "Urinating large volumes", system: "endocrine" },
  { id: "polyphagia", name: "Eating much more than usual", system: "endocrine" },
  { id: "goiter", name: "Neck swelling / goiter", system: "endocrine" },
  { id: "fruity-breath", name: "Fruity-smelling breath", system: "endocrine", redFlag: true },
  { id: "hirsutism", name: "Excess coarse hair (face/body)", system: "endocrine" },
  { id: "central-weight", name: "Weight gain mainly at the trunk", system: "endocrine" },
  { id: "delayed-wound", name: "Cuts that heal slowly", system: "endocrine" },

  // Hematologic
  { id: "easy-bleeding", name: "Easy bleeding of gums or nose", system: "hematologic" },
  { id: "lymphadenopathy", name: "Glands swollen in several areas", system: "hematologic" },
  { id: "night-itch", name: "Itching worse at night", system: "hematologic" },
  { id: "bone-tenderness", name: "Breastbone or long-bone tenderness", system: "hematologic" },
];

export const SYMPTOM_BY_ID: Record<string, Symptom> = Object.fromEntries(
  SYMPTOMS.map((s) => [s.id, s]),
);

export const SYMPTOM_IDS = SYMPTOMS.map((s) => s.id);

export const RED_FLAG_SYMPTOM_IDS = SYMPTOMS.filter((s) => s.redFlag).map((s) => s.id);

export function symptomsBySystem(): { system: BodySystem; label: string; items: Symptom[] }[] {
  const order: BodySystem[] = [
    "constitutional",
    "heent",
    "respiratory",
    "cardiovascular",
    "gastrointestinal",
    "genitourinary",
    "musculoskeletal",
    "neurologic",
    "skin",
    "psychiatric",
    "endocrine",
    "hematologic",
  ];
  return order.map((system) => ({
    system,
    label: SYSTEM_LABEL[system],
    items: SYMPTOMS.filter((s) => s.system === system),
  }));
}
